/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Codex (GPT-6-Sol).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 ***************************************************************************/

#include "tx_api.h"
#include "nx_api.h"
#include "nxd_dhcp_client.h"

extern VOID test_control_return(UINT status);

#if defined(NX_DHCP_CLIENT_SEND_ARP_PROBE) && !defined(NX_DISABLE_IPV4)

#define TEST_STACK_SIZE        4096
#define TEST_PACKET_SIZE       1536
#define TEST_POOL_SIZE         (TEST_PACKET_SIZE * 12)
#define TEST_ADDRESS           IP_ADDRESS(192, 0, 2, 10)
#define TEST_NETMASK           IP_ADDRESS(255, 255, 255, 0)

static TX_THREAD      test_thread;
static NX_PACKET_POOL test_pool;
static NX_IP          test_ip;
static NX_DHCP        test_dhcp;
static UINT           setup_errors;
static UINT           test_errors;
static UINT           bound_notifications;

static VOID test_thread_entry(ULONG thread_input);
static VOID conflict_notification(NX_IP *ip_ptr, UINT interface_index, ULONG ip_address,
                                  ULONG physical_msw, ULONG physical_lsw);
static VOID state_change_notification(NX_DHCP *dhcp_ptr, UCHAR new_state);
static VOID prepare_final_probe(VOID);
extern VOID _nx_ram_network_driver_256(NX_IP_DRIVER *driver_req_ptr);

/* Create the objects used to drive DHCP timer events.  */
#ifdef CTEST
VOID test_application_define(VOID *first_unused_memory)
#else
VOID netx_dhcp_final_probe_wait_test_application_define(VOID *first_unused_memory)
#endif
{
UCHAR *memory = (UCHAR *)first_unused_memory;

    nx_system_initialize();

    if (tx_thread_create(&test_thread, "DHCP probe test", test_thread_entry, 0,
                         memory, TEST_STACK_SIZE, 2, 2, TX_NO_TIME_SLICE, TX_AUTO_START) != TX_SUCCESS)
    {
        setup_errors++;
    }
    memory += TEST_STACK_SIZE;

    if (nx_packet_pool_create(&test_pool, "DHCP probe packets", TEST_PACKET_SIZE,
                              memory, TEST_POOL_SIZE) != NX_SUCCESS)
    {
        setup_errors++;
    }
    memory += TEST_POOL_SIZE;

    if (nx_ip_create(&test_ip, "DHCP probe IP", 0, 0, &test_pool,
                     _nx_ram_network_driver_256, memory, 2048, 1) != NX_SUCCESS)
    {
        setup_errors++;
    }
    memory += 2048;

    if (nx_arp_enable(&test_ip, memory, 1024) != NX_SUCCESS)
    {
        setup_errors++;
    }

    if (nx_udp_enable(&test_ip) != NX_SUCCESS)
    {
        setup_errors++;
    }
}

/* Record entry into the BOUND state.  */
static VOID state_change_notification(NX_DHCP *dhcp_ptr, UCHAR new_state)
{
    NX_PARAMETER_NOT_USED(dhcp_ptr);

    if (new_state == NX_DHCP_STATE_BOUND)
    {
        bound_notifications++;
    }
}

/* Deliver a detected address conflict to the DHCP thread.  */
static VOID conflict_notification(NX_IP *ip_ptr, UINT interface_index, ULONG ip_address,
                                  ULONG physical_msw, ULONG physical_lsw)
{
    NX_PARAMETER_NOT_USED(ip_ptr);
    NX_PARAMETER_NOT_USED(ip_address);
    NX_PARAMETER_NOT_USED(physical_msw);
    NX_PARAMETER_NOT_USED(physical_lsw);

    test_dhcp.nx_dhcp_interface_conflict_flag |= (UINT)(1U << interface_index);
    tx_event_flags_set(&(test_dhcp.nx_dhcp_events), NX_DHCP_CLIENT_CONFLICT_EVENT, TX_OR);
}

/* Place the client at its last ARP probe with a valid address offer.  */
static VOID prepare_final_probe(VOID)
{
NX_DHCP_INTERFACE_RECORD *record = &(test_dhcp.nx_dhcp_interface_record[0]);

    record -> nx_dhcp_record_valid = NX_TRUE;
    record -> nx_dhcp_interface_index = 0;
    record -> nx_dhcp_state = NX_DHCP_STATE_ADDRESS_PROBING;
    record -> nx_dhcp_probe_count = 1;
    record -> nx_dhcp_timeout = 1;
    record -> nx_dhcp_ip_address = TEST_ADDRESS;
    record -> nx_dhcp_network_mask = TEST_NETMASK;
    record -> nx_dhcp_gateway_address = 0;
    record -> nx_dhcp_renewal_time = 10 * NX_IP_PERIODIC_RATE;
    test_ip.nx_ip_interface[0].nx_interface_ip_conflict_notify_handler = conflict_notification;
}

/* Verify the final wait and a conflict arriving with its timer event.  */
static VOID test_thread_entry(ULONG thread_input)
{
NX_DHCP_INTERFACE_RECORD *record = &(test_dhcp.nx_dhcp_interface_record[0]);

    NX_PARAMETER_NOT_USED(thread_input);

    if (setup_errors != 0)
    {
        test_control_return(1);
        return;
    }

    if (nx_dhcp_create(&test_dhcp, &test_ip, "DHCP probe client") != NX_SUCCESS)
    {
        test_control_return(1);
        return;
    }
#ifdef NX_DHCP_CLIENT_USER_CREATE_PACKET_POOL
    if (nx_dhcp_packet_pool_set(&test_dhcp, &test_pool) != NX_SUCCESS)
    {
        test_control_return(1);
        return;
    }
#endif
    if (nx_dhcp_state_change_notify(&test_dhcp, state_change_notification) != NX_SUCCESS)
    {
        test_control_return(1);
        return;
    }
    if (nx_dhcp_start(&test_dhcp) != NX_SUCCESS)
    {
        test_control_return(1);
        return;
    }
    tx_timer_deactivate(&(test_dhcp.nx_dhcp_timer));
    tx_thread_sleep(1);
    bound_notifications = 0;

    prepare_final_probe();
    tx_event_flags_set(&(test_dhcp.nx_dhcp_events), NX_DHCP_CLIENT_TIMER_EVENT, TX_OR);
    tx_thread_sleep(1);
    if ((record -> nx_dhcp_state != NX_DHCP_STATE_ADDRESS_PROBING) ||
        (record -> nx_dhcp_probe_count != 0) ||
        (record -> nx_dhcp_timeout != NX_DHCP_ARP_ANNOUNCE_WAIT) ||
        (test_ip.nx_ip_interface[0].nx_interface_ip_conflict_notify_handler == NX_NULL) ||
        (test_ip.nx_ip_interface[0].nx_interface_ip_address != 0))
    {
        test_errors++;
    }

    if (test_ip.nx_ip_interface[0].nx_interface_ip_conflict_notify_handler != NX_NULL)
    {
        (test_ip.nx_ip_interface[0].nx_interface_ip_conflict_notify_handler)(&test_ip, 0, TEST_ADDRESS, 0, 0);
    }
    record -> nx_dhcp_timeout = 1;
    tx_event_flags_set(&(test_dhcp.nx_dhcp_events), NX_DHCP_CLIENT_TIMER_EVENT, TX_OR);
    tx_thread_sleep(1);
    if ((record -> nx_dhcp_state != NX_DHCP_STATE_INIT) ||
        (bound_notifications != 0) ||
        (test_ip.nx_ip_interface[0].nx_interface_ip_address != 0))
    {
        test_errors++;
    }

    prepare_final_probe();
    tx_event_flags_set(&(test_dhcp.nx_dhcp_events), NX_DHCP_CLIENT_TIMER_EVENT, TX_OR);
    tx_thread_sleep(1);
    if ((record -> nx_dhcp_state != NX_DHCP_STATE_ADDRESS_PROBING) ||
        (record -> nx_dhcp_timeout != NX_DHCP_ARP_ANNOUNCE_WAIT) ||
        (bound_notifications != 0))
    {
        test_errors++;
    }

    tx_event_flags_set(&(test_dhcp.nx_dhcp_events), NX_DHCP_CLIENT_TIMER_EVENT, TX_OR);
    tx_thread_sleep(1);
    if ((record -> nx_dhcp_state != NX_DHCP_STATE_ADDRESS_PROBING) ||
        (record -> nx_dhcp_timeout != (NX_DHCP_ARP_ANNOUNCE_WAIT - NX_DHCP_TIME_INTERVAL)))
    {
        test_errors++;
    }

    tx_event_flags_set(&(test_dhcp.nx_dhcp_events), NX_DHCP_CLIENT_TIMER_EVENT, TX_OR);
    tx_thread_sleep(1);
    if ((record -> nx_dhcp_state != NX_DHCP_STATE_BOUND) ||
        (bound_notifications != 1) ||
        (test_ip.nx_ip_interface[0].nx_interface_ip_conflict_notify_handler != NX_NULL) ||
        (test_ip.nx_ip_interface[0].nx_interface_ip_address != TEST_ADDRESS))
    {
        test_errors++;
    }

    if (test_errors != 0)
    {
        test_control_return(1);
    }
    else
    {
        test_control_return(0);
    }
}

#else

/* Report configurations without IPv4 ARP probing as not applicable.  */
#ifdef CTEST
VOID test_application_define(VOID *first_unused_memory)
#else
VOID netx_dhcp_final_probe_wait_test_application_define(VOID *first_unused_memory)
#endif
{
    NX_PARAMETER_NOT_USED(first_unused_memory);
    test_control_return(3);
}

#endif
