#!/bin/bash
##############################################################################
# Copyright (c) 2026 Eclipse ThreadX contributors
#
# This program and the accompanying materials are made available under the
# terms of the MIT License which is available at
# https://opensource.org/licenses/MIT.
#
# AI Disclosure: This file was largely AI-generated by Codex (gpt-5.6-sol).
# The AI-generated portions may be considered public domain (CC0-1.0)
# and not subject to the project's licence. The human contributor has
# reviewed and verified that the code is correct.
#
# SPDX-License-Identifier: MIT AND CC0-1.0
##############################################################################

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
OPENSSL_COMMAND=${OPENSSL_COMMAND:-openssl}
VALIDITY_DAYS=${VALIDITY_DAYS:-7305}
TEMPORARY_DIRECTORY=$(mktemp -d)

trap 'rm -rf "$TEMPORARY_DIRECTORY"' EXIT

certificate_serial()
{
    "$OPENSSL_COMMAND" x509 -in "$1" -noout -serial | cut -d= -f2
}

certificate_key_matches()
{
    "$OPENSSL_COMMAND" x509 -in "$1" -pubkey -noout | \
        "$OPENSSL_COMMAND" pkey -pubin -outform DER \
        > "$TEMPORARY_DIRECTORY/certificate-public-key.der"
    "$OPENSSL_COMMAND" pkey -in "$2" -pubout -outform DER \
        > "$TEMPORARY_DIRECTORY/private-public-key.der"
    cmp -s "$TEMPORARY_DIRECTORY/certificate-public-key.der" \
        "$TEMPORARY_DIRECTORY/private-public-key.der"
}

write_certificate()
{
    local generated_certificate=$1
    local destination=$2

    if head -n 1 "$destination" | grep -q '^Certificate:'; then
        "$OPENSSL_COMMAND" x509 -in "$generated_certificate" -text -out "$destination"
    else
        cp "$generated_certificate" "$destination"
    fi
    sed -i 's/[[:space:]]*$//' "$destination"
}

renew_self_signed_certificate()
{
    local certificate=$1
    local private_key=$2
    local certificate_name
    local serial

    certificate_name=$(basename "$certificate" .crt)
    serial=$(certificate_serial "$certificate")
    "$OPENSSL_COMMAND" x509 -x509toreq -in "$certificate" \
        -signkey "$private_key" -copy_extensions copyall \
        -out "$TEMPORARY_DIRECTORY/$certificate_name.csr"
    "$OPENSSL_COMMAND" x509 -req \
        -in "$TEMPORARY_DIRECTORY/$certificate_name.csr" \
        -signkey "$private_key" -set_serial "0x$serial" \
        -days "$VALIDITY_DAYS" -copy_extensions copyall -sha256 \
        -out "$TEMPORARY_DIRECTORY/$certificate_name.crt"
    write_certificate "$TEMPORARY_DIRECTORY/$certificate_name.crt" "$certificate"
}

renew_signed_certificate()
{
    local certificate=$1
    local private_key=$2
    local issuer_certificate=$3
    local issuer_private_key=$4
    local certificate_name
    local serial

    certificate_name=$(basename "$certificate" .crt)
    serial=$(certificate_serial "$certificate")
    "$OPENSSL_COMMAND" x509 -x509toreq -in "$certificate" \
        -signkey "$private_key" -copy_extensions copyall \
        -out "$TEMPORARY_DIRECTORY/$certificate_name.csr"
    "$OPENSSL_COMMAND" x509 -req \
        -in "$TEMPORARY_DIRECTORY/$certificate_name.csr" \
        -CA "$issuer_certificate" -CAkey "$issuer_private_key" \
        -set_serial "0x$serial" -days "$VALIDITY_DAYS" \
        -copy_extensions copyall -sha256 \
        -out "$TEMPORARY_DIRECTORY/$certificate_name.crt"
    write_certificate "$TEMPORARY_DIRECTORY/$certificate_name.crt" "$certificate"
}

create_ca_certificate()
{
    local old_certificate=$1
    local private_key=$2
    local subject
    local serial

    subject=$("$OPENSSL_COMMAND" x509 -in "$old_certificate" -noout \
        -subject -nameopt compat)
    subject=${subject#subject=}
    serial=$(certificate_serial "$old_certificate")

    if [ ! -f "$private_key" ]; then
        "$OPENSSL_COMMAND" genpkey -algorithm RSA \
            -pkeyopt rsa_keygen_bits:4096 -quiet -out "$private_key"
    fi

    "$OPENSSL_COMMAND" req -new -x509 -key "$private_key" \
        -out "$TEMPORARY_DIRECTORY/new-ca.crt" \
        -days "$VALIDITY_DAYS" -set_serial "0x$serial" -subj "$subject" \
        -addext 'keyUsage=critical,keyCertSign,cRLSign' \
        -addext 'basicConstraints=critical,CA:TRUE' \
        -addext 'subjectKeyIdentifier=hash' \
        -addext 'authorityKeyIdentifier=keyid:always'
    write_certificate "$TEMPORARY_DIRECTORY/new-ca.crt" "$old_certificate"
}

create_version_one_ca_certificate()
{
    local old_certificate=$1
    local private_key=$2
    local subject
    local serial

    subject=$("$OPENSSL_COMMAND" x509 -in "$old_certificate" -noout \
        -subject -nameopt compat)
    subject=${subject#subject=}
    serial=$(certificate_serial "$old_certificate")
    "$OPENSSL_COMMAND" x509 -new -key "$private_key" \
        -out "$TEMPORARY_DIRECTORY/new-version-one-ca.crt" \
        -days "$VALIDITY_DAYS" -set_serial "0x$serial" -subj "$subject"
    write_certificate "$TEMPORARY_DIRECTORY/new-version-one-ca.crt" \
        "$old_certificate"
}

create_crl()
{
    local issuer_certificate=$1
    local issuer_private_key=$2
    local output=$3
    shift 3
    local configuration="$TEMPORARY_DIRECTORY/ca.cnf"
    local database="$TEMPORARY_DIRECTORY/index"
    local revocation_time
    local serial

    revocation_time=$(date -u +%y%m%d%H%M%SZ)
    : > "$database"
    for serial in "$@"; do
        printf 'R\t461231235959Z\t%s\t%s\tunknown\t/CN=revoked-%s\n' \
            "$revocation_time" "$serial" "$serial" >> "$database"
    done
    : > "$database.attr"
    printf '01\n' > "$TEMPORARY_DIRECTORY/crlnumber"
    printf '%s\n' \
        '[ ca ]' \
        'default_ca = CA_default' \
        '[ CA_default ]' \
        "database = $database" \
        "private_key = $issuer_private_key" \
        "certificate = $issuer_certificate" \
        'default_md = sha256' \
        "default_crl_days = $VALIDITY_DAYS" > "$configuration"

    "$OPENSSL_COMMAND" ca -config "$configuration" -gencrl -batch \
        -out "$TEMPORARY_DIRECTORY/generated.crl"
    "$OPENSSL_COMMAND" crl -in "$TEMPORARY_DIRECTORY/generated.crl" \
        -outform DER -out "$output"
}

replace_c_array()
{
    local input=$1
    local variable=$2
    local target=$3
    local storage=$4
    local columns=$5
    local array_file="$TEMPORARY_DIRECTORY/$variable.array"
    local output_file="$TEMPORARY_DIRECTORY/$variable.output"

    od -An -v -tx1 "$input" | awk -v variable="$variable" \
        -v storage="$storage" -v columns="$columns" '
        {
            for (field = 1; field <= NF; field++) {
                bytes[++byte_count] = $field
            }
        }
        END {
            prefix = (storage == "static") ? "static " : ""
            print prefix "unsigned char " variable "[] = {"
            for (byte_number = 1; byte_number <= byte_count; byte_number++) {
                if (((byte_number - 1) % columns) == 0) {
                    printf "  "
                }
                printf "0x%s%s", bytes[byte_number], \
                    (byte_number < byte_count) ? "," : ""
                if ((byte_number % columns) == 0 || byte_number == byte_count) {
                    printf "\n"
                } else {
                    printf " "
                }
            }
            print "};"
            print prefix "unsigned int " variable "_len = " byte_count ";"
        }
    ' > "$array_file"

    awk -v variable="$variable" -v replacement="$array_file" '
        BEGIN {
            while ((getline line < replacement) > 0) {
                generated = generated line "\n"
            }
        }
        $0 == "static unsigned char " variable "[] = {" ||
        $0 == "unsigned char " variable "[] = {" {
            printf "%s", generated
            replacing = 1
            next
        }
        replacing && $0 ~ "^(static )?unsigned int " variable "_len = [0-9]+;" {
            replacing = 0
            next
        }
        !replacing { print }
    ' "$target" > "$output_file"
    cp "$output_file" "$target"
}

certificate_to_der()
{
    "$OPENSSL_COMMAND" x509 -in "$1" -outform DER -out "$2"
}

ECC_DIRECTORY="$SCRIPT_DIR/ecc_certificates"
if certificate_key_matches "$ECC_DIRECTORY/ECCA.crt" "$ECC_DIRECTORY/ECCA.key"; then
    renew_self_signed_certificate "$ECC_DIRECTORY/ECCA.crt" "$ECC_DIRECTORY/ECCA.key"
else
    create_version_one_ca_certificate "$ECC_DIRECTORY/ECCA.crt" \
        "$ECC_DIRECTORY/ECCA.key"
fi
for ca_name in ECCA2 ECCA3 ECCA4; do
    renew_self_signed_certificate "$ECC_DIRECTORY/$ca_name.crt" \
        "$ECC_DIRECTORY/$ca_name.key"
done

renew_signed_certificate "$ECC_DIRECTORY/ECTest.crt" "$ECC_DIRECTORY/ECTest.key" \
    "$ECC_DIRECTORY/ECCA.crt" "$ECC_DIRECTORY/ECCA.key"
renew_signed_certificate "$ECC_DIRECTORY/ECTestServer2.crt" "$ECC_DIRECTORY/ECTestServer2.key" \
    "$ECC_DIRECTORY/ECCA2.crt" "$ECC_DIRECTORY/ECCA2.key"
renew_signed_certificate "$ECC_DIRECTORY/ECTestServer3.crt" "$ECC_DIRECTORY/ECTestServer3.key" \
    "$ECC_DIRECTORY/ECCA3.crt" "$ECC_DIRECTORY/ECCA3.key"
for certificate_name in ECTestServer4 ECTestServer6 ECTestServer7_256 \
    ECRevoked ECIntm ECTestClient1; do
    renew_signed_certificate "$ECC_DIRECTORY/$certificate_name.crt" \
        "$ECC_DIRECTORY/$certificate_name.key" "$ECC_DIRECTORY/ECCA4.crt" \
        "$ECC_DIRECTORY/ECCA4.key"
done
for certificate_name in ECTestServer8_224 ECTestServer9_192 ECTestServer10; do
    renew_signed_certificate "$ECC_DIRECTORY/$certificate_name.crt" \
        "$ECC_DIRECTORY/$certificate_name.key" "$ECC_DIRECTORY/ECCA2.crt" \
        "$ECC_DIRECTORY/ECCA2.key"
done
renew_signed_certificate "$ECC_DIRECTORY/ECRevoked2.crt" "$ECC_DIRECTORY/ECRevoked2.key" \
    "$ECC_DIRECTORY/ECIntm.crt" "$ECC_DIRECTORY/ECIntm.key"
create_crl "$ECC_DIRECTORY/ECCA4.crt" "$ECC_DIRECTORY/ECCA4.key" \
    "$ECC_DIRECTORY/ECCA4.crl" 09
create_crl "$ECC_DIRECTORY/ECIntm.crt" "$ECC_DIRECTORY/ECIntm.key" \
    "$ECC_DIRECTORY/ECIntm.crl" 09 0B

renew_self_signed_certificate "$SCRIPT_DIR/nx_secure_test/cert.pem" \
    "$SCRIPT_DIR/nx_secure_test/key.pem"

RSA_DIRECTORY="$SCRIPT_DIR/certificates"
create_ca_certificate "$RSA_DIRECTORY/test.crt" "$RSA_DIRECTORY/test.key"
for certificate_name in test_server test_client; do
    renew_signed_certificate "$RSA_DIRECTORY/$certificate_name.crt" \
        "$RSA_DIRECTORY/$certificate_name.key" "$RSA_DIRECTORY/test.crt" \
        "$RSA_DIRECTORY/test.key"
done

MQTT_CA_DIRECTORY="$SCRIPT_DIR/mqtt_test/test_scripts/CA"
create_ca_certificate "$MQTT_CA_DIRECTORY/ca/ca.crt" "$MQTT_CA_DIRECTORY/ca/ca.key"
for certificate_name in broker.server ew2017.client; do
    renew_signed_certificate "$MQTT_CA_DIRECTORY/certs/$certificate_name.crt" \
        "$MQTT_CA_DIRECTORY/private/$certificate_name.key" \
        "$MQTT_CA_DIRECTORY/ca/ca.crt" "$MQTT_CA_DIRECTORY/ca/ca.key"
done

EMBEDDED_ECC="$SCRIPT_DIR/../nx_secure_test/ecc_certs.c"
for mapping in \
    ECCA:ECCA_der ECCA:ECCArsa_der ECCA2:ECCA2_der ECCA3:ECCA3_der \
    ECCA4:ECCA4_der ECTest:ECTest_der ECTest:ecdhcert_der \
    ECTestServer2:ECTestServer2_der ECTestServer3:ECTestServer3_der \
    ECTestServer4:ECTestServer4_der ECTestServer6:ECTestServer6_der \
    ECTestServer7_256:ECTestServer7_256_der \
    ECTestServer8_224:ECTestServer8_224_der \
    ECTestServer9_192:ECTestServer9_192_der \
    ECTestServer10:ECTestServer10_der ECIntm:ECIntm_der \
    ECRevoked2:ECRevoked2_der ECTestClient1:ECTestClient1_der; do
    certificate_name=${mapping%%:*}
    variable=${mapping#*:}
    certificate_to_der "$ECC_DIRECTORY/$certificate_name.crt" \
        "$TEMPORARY_DIRECTORY/$variable.der"
    replace_c_array "$TEMPORARY_DIRECTORY/$variable.der" "$variable" \
        "$EMBEDDED_ECC" static 12
done
replace_c_array "$ECC_DIRECTORY/ECIntm.crl" ECIntm_crl "$EMBEDDED_ECC" static 12

certificate_to_der "$SCRIPT_DIR/nx_secure_test/cert.pem" \
    "$TEMPORARY_DIRECTORY/cert_der.der"
replace_c_array "$TEMPORARY_DIRECTORY/cert_der.der" cert_der \
    "$SCRIPT_DIR/nx_secure_test/cert.c" global 16

for certificate_name in test test_server test_client; do
    certificate_to_der "$RSA_DIRECTORY/$certificate_name.crt" \
        "$TEMPORARY_DIRECTORY/${certificate_name}_der.der"
    for embedded_directory in "$RSA_DIRECTORY" "$SCRIPT_DIR/nx_secure_test"; do
        replace_c_array "$TEMPORARY_DIRECTORY/${certificate_name}_der.der" \
            "${certificate_name}_der" "$embedded_directory/$certificate_name.der.c" \
            global 16
    done
done

certificate_to_der "$MQTT_CA_DIRECTORY/ca/ca.crt" "$TEMPORARY_DIRECTORY/ca_der.der"
replace_c_array "$TEMPORARY_DIRECTORY/ca_der.der" ca_der \
    "$SCRIPT_DIR/mqtt_test/ca.c" global 12

"$SCRIPT_DIR/verify_test_certificates.sh"
