#!/bin/bash
##############################################################################
# Copyright (c) 2026 Eclipse ThreadX contributors
#
# This program and the accompanying materials are made available under the
# terms of the MIT License which is available at
# https://opensource.org/licenses/MIT.
#
# AI Disclosure: This file was largely AI-generated by Codex (gpt-5.6-sol).
# The AI-generated portions may be considered public domain (CC0-1.0)
# and not subject to the project's licence. The human contributor has
# reviewed and verified that the code is correct.
#
# SPDX-License-Identifier: MIT AND CC0-1.0
##############################################################################

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
OPENSSL_COMMAND=${OPENSSL_COMMAND:-openssl}
MINIMUM_VALIDITY_SECONDS=${MINIMUM_VALIDITY_SECONDS:-2592000}
TEMPORARY_DIRECTORY=$(mktemp -d)

trap 'rm -rf "$TEMPORARY_DIRECTORY"' EXIT

check_certificate()
{
    local certificate=$1
    local private_key=$2

    "$OPENSSL_COMMAND" x509 -in "$certificate" -noout \
        -checkend "$MINIMUM_VALIDITY_SECONDS"
    "$OPENSSL_COMMAND" x509 -in "$certificate" -pubkey -noout | \
        "$OPENSSL_COMMAND" pkey -pubin -outform DER \
        > "$TEMPORARY_DIRECTORY/certificate-public-key.der"
    "$OPENSSL_COMMAND" pkey -in "$private_key" -pubout -outform DER \
        > "$TEMPORARY_DIRECTORY/private-public-key.der"
    cmp "$TEMPORARY_DIRECTORY/certificate-public-key.der" \
        "$TEMPORARY_DIRECTORY/private-public-key.der"
}

check_chain()
{
    "$OPENSSL_COMMAND" verify -auth_level 0 -CAfile "$2" "$1"
}

check_crl()
{
    local crl=$1
    local issuer=$2
    local next_update
    local minimum_epoch

    "$OPENSSL_COMMAND" crl -inform DER -in "$crl" -verify \
        -CAfile "$issuer" -noout
    next_update=$("$OPENSSL_COMMAND" crl -inform DER -in "$crl" \
        -nextupdate -noout | cut -d= -f2-)
    minimum_epoch=$(($(date -u +%s) + MINIMUM_VALIDITY_SECONDS))
    test "$(date -u -d "$next_update" +%s)" -ge "$minimum_epoch"
}

check_embedded_array()
{
    local input=$1
    local input_format=$2
    local variable=$3
    local source_file=$4
    local expected="$TEMPORARY_DIRECTORY/$variable.expected"
    local actual="$TEMPORARY_DIRECTORY/$variable.actual"

    if [ "$input_format" = "certificate" ]; then
        "$OPENSSL_COMMAND" x509 -in "$input" -outform DER \
            -out "$TEMPORARY_DIRECTORY/$variable.der"
        input="$TEMPORARY_DIRECTORY/$variable.der"
    fi
    od -An -v -tx1 "$input" | tr -d ' \n' > "$expected"
    awk -v variable="$variable" '
        $0 ~ "unsigned char " variable "\\[\\] = \\{" { reading = 1 }
        reading { print }
        reading && $0 == "};" { exit }
    ' "$source_file" | sed 's/0x/\n0x/g' | \
        sed -n 's/^0x\([0-9a-fA-F][0-9a-fA-F]\).*/\1/p' | \
        tr -d '\n' > "$actual"
    cmp "$expected" "$actual"
}

ECC_DIRECTORY="$SCRIPT_DIR/ecc_certificates"
for ca_name in ECCA ECCA2 ECCA3 ECCA4; do
    check_certificate "$ECC_DIRECTORY/$ca_name.crt" "$ECC_DIRECTORY/$ca_name.key"
    check_chain "$ECC_DIRECTORY/$ca_name.crt" "$ECC_DIRECTORY/$ca_name.crt"
done

for mapping in \
    ECTest:ECCA ECTestServer2:ECCA2 ECTestServer3:ECCA3 \
    ECTestServer4:ECCA4 ECTestServer6:ECCA4 ECTestServer7_256:ECCA4 \
    ECTestServer8_224:ECCA2 ECTestServer9_192:ECCA2 \
    ECTestServer10:ECCA2 ECRevoked:ECCA4 ECIntm:ECCA4 \
    ECTestClient1:ECCA4; do
    certificate_name=${mapping%%:*}
    issuer_name=${mapping#*:}
    check_certificate "$ECC_DIRECTORY/$certificate_name.crt" \
        "$ECC_DIRECTORY/$certificate_name.key"
    check_chain "$ECC_DIRECTORY/$certificate_name.crt" \
        "$ECC_DIRECTORY/$issuer_name.crt"
done
check_certificate "$ECC_DIRECTORY/ECRevoked2.crt" "$ECC_DIRECTORY/ECRevoked2.key"
check_crl "$ECC_DIRECTORY/ECCA4.crl" "$ECC_DIRECTORY/ECCA4.crt"
check_crl "$ECC_DIRECTORY/ECIntm.crl" "$ECC_DIRECTORY/ECIntm.crt"

EMBEDDED_ECC="$SCRIPT_DIR/../nx_secure_test/ecc_certs.c"
for mapping in \
    ECCA:ECCA_der ECCA:ECCArsa_der ECCA2:ECCA2_der ECCA3:ECCA3_der \
    ECCA4:ECCA4_der ECTest:ECTest_der ECTest:ecdhcert_der \
    ECTestServer2:ECTestServer2_der ECTestServer3:ECTestServer3_der \
    ECTestServer4:ECTestServer4_der ECTestServer6:ECTestServer6_der \
    ECTestServer7_256:ECTestServer7_256_der \
    ECTestServer8_224:ECTestServer8_224_der \
    ECTestServer9_192:ECTestServer9_192_der \
    ECTestServer10:ECTestServer10_der ECIntm:ECIntm_der \
    ECRevoked2:ECRevoked2_der ECTestClient1:ECTestClient1_der; do
    certificate_name=${mapping%%:*}
    variable=${mapping#*:}
    check_embedded_array "$ECC_DIRECTORY/$certificate_name.crt" certificate \
        "$variable" "$EMBEDDED_ECC"
done
check_embedded_array "$ECC_DIRECTORY/ECIntm.crl" binary ECIntm_crl "$EMBEDDED_ECC"

check_certificate "$SCRIPT_DIR/nx_secure_test/cert.pem" \
    "$SCRIPT_DIR/nx_secure_test/key.pem"
check_chain "$SCRIPT_DIR/nx_secure_test/cert.pem" \
    "$SCRIPT_DIR/nx_secure_test/cert.pem"
check_embedded_array "$SCRIPT_DIR/nx_secure_test/cert.pem" certificate cert_der \
    "$SCRIPT_DIR/nx_secure_test/cert.c"

RSA_DIRECTORY="$SCRIPT_DIR/certificates"
check_certificate "$RSA_DIRECTORY/test.crt" "$RSA_DIRECTORY/test.key"
check_chain "$RSA_DIRECTORY/test.crt" "$RSA_DIRECTORY/test.crt"
for certificate_name in test_server test_client; do
    check_certificate "$RSA_DIRECTORY/$certificate_name.crt" \
        "$RSA_DIRECTORY/$certificate_name.key"
    check_chain "$RSA_DIRECTORY/$certificate_name.crt" "$RSA_DIRECTORY/test.crt"
done
for certificate_name in test test_server test_client; do
    for embedded_directory in "$RSA_DIRECTORY" "$SCRIPT_DIR/nx_secure_test"; do
        check_embedded_array "$RSA_DIRECTORY/$certificate_name.crt" certificate \
            "${certificate_name}_der" "$embedded_directory/$certificate_name.der.c"
    done
done

MQTT_CA_DIRECTORY="$SCRIPT_DIR/mqtt_test/test_scripts/CA"
check_certificate "$MQTT_CA_DIRECTORY/ca/ca.crt" "$MQTT_CA_DIRECTORY/ca/ca.key"
check_chain "$MQTT_CA_DIRECTORY/ca/ca.crt" "$MQTT_CA_DIRECTORY/ca/ca.crt"
for certificate_name in broker.server ew2017.client; do
    check_certificate "$MQTT_CA_DIRECTORY/certs/$certificate_name.crt" \
        "$MQTT_CA_DIRECTORY/private/$certificate_name.key"
    check_chain "$MQTT_CA_DIRECTORY/certs/$certificate_name.crt" \
        "$MQTT_CA_DIRECTORY/ca/ca.crt"
done
check_embedded_array "$MQTT_CA_DIRECTORY/ca/ca.crt" certificate ca_der \
    "$SCRIPT_DIR/mqtt_test/ca.c"

echo "Interoperability test certificates are valid."
