#!/usr/bin/env python3
###################################################################################
# Copyright (c) 2026 Eclipse ThreadX contributors
#
# This program and the accompanying materials are made available under the
# terms of the MIT License which is available at
# https://opensource.org/licenses/MIT.
#
# AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
# The AI-generated portions may be considered public domain (CC0-1.0)
# and not subject to the project's licence. The human contributor has
# reviewed and verified that the code is correct.
#
# SPDX-License-Identifier: MIT and CC0-1.0
###################################################################################
"""Enumerate the uncovered lines and branch outcomes in the certified source.

coverage_union.py reports the figure. This reports the set behind it: every
line and every branch outcome the union leaves uncovered, with the function
that encloses it. That set is the input to the work that closes the gaps, and
it has to be the *same* set the published figure is the complement of -- not a
similar one derived a second way.

So the keying is not reimplemented here. This imports union() from
coverage_union and filters what it already computed, for one reason: a branch
is keyed by (file, line, branch count on that line, ordinal) rather than by
position alone, because five common/src lines compile to different numbers of
branches in different configurations. A second implementation of that key is a
second thing to get wrong, and a gap inventory that disagrees with the figure
by even one item is worse than none -- it puts two numbers in the evidence and
no way to tell which is the coverage.

The totals are printed so they can be cross-footed against the published
figure before anything downstream is written. On this tree that is 586 lines
and 603 branch outcomes. Cross-footing an extraction against the source
document's own totals is what catches a silent omission: a row-dropping regex
once cost seven files out of a coverage table read the same careless way.

gcovr's merged report is NOT a substitute source for this listing, and the
difference is not academic. nx_ipv6_option_error.c:91 compiles to four
branches in 61 configurations and three in two others; gcovr's merge calls the
line 4/4 fully covered, and the union finds two outcomes that are never taken
in the three-branch form. An inventory built from the gcovr report would omit
them and would not sum to 603.

Usage: coverage_gaps.py <tracefile-dir> [--tsv]

<tracefile-dir> is searched recursively for *.json, so it can be pointed at
either a flat merge directory or the extracted 'coverage_detail <Suite>'
artifacts, whose tracefiles sit under d-<Suite>/certified/.
"""

import collections
import glob
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from coverage_union import union, exclude_hook_sites, multiform_lines


def enclosing_functions(tracefiles):
    """Map each certified file to its functions, as (start line, name), sorted.

    gcovr's JSON carries a per-file "functions" list with a lineno for each.
    The enclosing function of a line is the one with the greatest start line
    not after it. A file's function set can differ between configurations --
    a feature gate can compile a function away -- so the union of all
    configurations is taken, which is the same basis the line map uses.
    """

    by_file = collections.defaultdict(dict)
    for path in tracefiles:
        with open(path, encoding="utf-8") as handle:
            data = json.load(handle)
        for entry in data.get("files", []):
            for function in entry.get("functions", []) or []:
                name = function.get("name")
                if not name:
                    continue
                start = function.get("lineno")
                end = None
                # gcovr 8.6 emits "pos": ["<start line>:<col>", "<end line>:<col>"],
                # which gives the function's real extent. Measured on this tree:
                # 518 of 518 functions in a configuration carry it. Using the
                # extent rather than "the nearest preceding start" matters for a
                # line that belongs to no function -- a file-scope declaration or
                # a gap between two bodies -- which the nearest-start rule would
                # silently attribute to whichever function came before it.
                position = function.get("pos")
                if position and len(position) == 2:
                    try:
                        start = int(str(position[0]).split(":")[0])
                        end = int(str(position[1]).split(":")[0])
                    except ValueError:
                        end = None
                if start is not None:
                    by_file[entry["file"]][int(start)] = (name, end)
    return {name: sorted((s, v[0], v[1]) for s, v in table.items())
            for name, table in by_file.items()}


def enclosing(table, number):
    """The function containing a line, or None when no function contains it.

    None is a real answer and is printed as such rather than guessed at. A
    line outside every function extent is a file-scope construct, and calling
    it part of the function above it would put a wrong name in an evidence
    document.
    """

    found = None
    for start, name, end in table:
        if start <= number and (end is None or number <= end):
            found = name
        elif start > number:
            break
    return found


def main():
    if len(sys.argv) < 2:
        print(__doc__.strip().splitlines()[-1], file=sys.stderr)
        return 2

    directory = sys.argv[1]
    as_tsv = "--tsv" in sys.argv[2:]

    tracefiles = sorted(glob.glob(os.path.join(directory, "**", "*.json"), recursive=True))
    if not tracefiles:
        print("coverage_gaps.py: no JSON under %s." % directory, file=sys.stderr)
        return 1

    lines, branches, shapes, silent = union(tracefiles)
    if not lines:
        print("coverage_gaps.py: the tracefiles contain no files.", file=sys.stderr)
        return 1

    # Same order as coverage_union.main: the key's soundness is established
    # before any set derived from it is reported.
    multiform = multiform_lines(shapes)
    excluded, missing = exclude_hook_sites(lines, branches)
    if missing:
        for path, number, macro in missing:
            print("coverage_gaps.py: %s:%d is not in the report -- %s has moved."
                  % (path, number, macro), file=sys.stderr)
        return 1

    functions = enclosing_functions(tracefiles)

    uncovered_lines = sorted(key for key, hit in lines.items() if not hit)
    uncovered_branches = sorted(key for key, hit in branches.items() if not hit)

    multiform_keys = {(path, number) for path, number, _ in multiform}

    if as_tsv:
        print("kind\tfile\tline\tforms\tordinal\tfunction")
        for path, number in uncovered_lines:
            print("line\t%s\t%d\t\t\t%s"
                  % (path, number, enclosing(functions.get(path, []), number) or "?"))
        for path, number, count, index in uncovered_branches:
            print("branch\t%s\t%d\t%d\t%d\t%s"
                  % (path, number, count, index,
                     enclosing(functions.get(path, []), number) or "?"))
        return 0

    print("coverage_gaps.py: unioned over %d configuration(s)" % len(tracefiles))
    print()
    print("    lines    %d uncovered of %d" % (len(uncovered_lines), len(lines)))
    print("    branches %d uncovered of %d" % (len(uncovered_branches), len(branches)))
    print("    files    %d in the denominator, %d carrying a gap"
          % (len({p for p, _ in lines}),
             len({p for p, _ in uncovered_lines} | {b[0] for b in uncovered_branches})))
    print()

    per_file = collections.defaultdict(lambda: [0, 0])
    for path, _ in uncovered_lines:
        per_file[path][0] += 1
    for key in uncovered_branches:
        per_file[key[0]][1] += 1

    print("    %-52s %6s %9s" % ("file", "lines", "outcomes"))
    for path in sorted(per_file, key=lambda p: (-sum(per_file[p]), p)):
        count = per_file[path]
        print("    %-52s %6d %9d" % (path, count[0], count[1]))

    if multiform:
        print()
        print("    %d line(s) compile to more than one branch form; an uncovered"
              % len(multiform))
        print("    outcome on one of these is uncovered in that form only:")
        for path, number, counts in multiform:
            marked = " <- carries a gap" if (path, number) in multiform_keys and any(
                b[0] == path and b[1] == number for b in uncovered_branches) else ""
            spread = ", ".join("%d branches in %d configuration(s)" % (n, c)
                               for n, c in sorted(collections.Counter(counts.values()).items()))
            print("        %s:%d  %s%s" % (path, number, spread, marked))

    return 0


if __name__ == "__main__":
    sys.exit(main())
