/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* This is the shared-port companion of netx_bsd_tcp_accept_socket_limit_test.
 *
 * bind() clears an address conflict for an SO_REUSEADDR socket whose address
 * family or whose bind interface differs from the socket that already holds the
 * port, so two master sockets can share one port and with it one secondary
 * socket - one NetX listen serves both.  When accept() cannot allocate the
 * replacement secondary socket, because every BSD socket is in use, it
 * invalidates the secondary socket id of both master sockets, and from then on
 * the listen is only reachable through them.
 *
 * soc_close() then has to release that listen exactly once, at the close of the
 * last master socket on the port: releasing it earlier would break the master
 * socket that is still listening, never releasing it would leave an
 * NX_TCP_LISTEN entry behind that refers to a deleted socket and blocks the port.
 *
 * The same sequence runs for both ways of sharing a port:
 *
 *  1. An IPv4 and an IPv6 master socket.  bind() gives the second one the port of
 *     the first because the families differ.
 *
 *  2. Two IPv4 master sockets bound to different local interfaces.  bind() gives
 *     the second one the port because the bind interfaces differ, and - unlike
 *     the IPv6 case - it leaves that socket's own NetX socket unbound, so its
 *     nx_tcp_socket_port stays zero.  The release has to work from the port the
 *     BSD socket carries instead.
 *
 * Each phase checks that the listen survives the close of the first master
 * socket, is gone after the close of the last one, and that the port can be
 * listened on again afterwards.
 */

#include "tx_api.h"
#include "nx_api.h"
#if defined(NX_BSD_ENABLE) && !defined(NX_DISABLE_IPV4) && \
    (defined(FEATURE_NX_IPV6) || (NX_MAX_PHYSICAL_INTERFACES > 1))
#include "nxd_bsd.h"

#define DEMO_STACK_SIZE     4096
#define BSD_THREAD_PRIORITY 2

#define SERVER_ADDRESS      IP_ADDRESS(1, 2, 3, 4)
#define SERVER_ADDRESS_2    IP_ADDRESS(2, 2, 3, 4)
#define CLIENT_ADDRESS      IP_ADDRESS(1, 2, 3, 5)

#define IPV6_PHASE_PORT     5555
#define IF_PHASE_PORT       5556

static TX_THREAD        ntest_0;
static TX_THREAD        ntest_1;

static NX_PACKET_POOL   pool_0;
static NX_IP            ip_0;
static NX_IP            ip_1;
static TX_SEMAPHORE     sema_0;
static TX_SEMAPHORE     sema_1;

static ULONG            error_counter;

/* Phase the test is in, and the phase of the first failure, so that a failure of
   this test still says where to look. */
static INT              test_phase;
static INT              error_phase;

/* Port the peer thread has to connect to, or 0 when it is done. */
static UINT             client_port;

static ULONG            packet_pool_area[(512 + sizeof(NX_PACKET)) * 32 / 4];

static void ntest_0_entry(ULONG thread_input);
static void ntest_1_entry(ULONG thread_input);
static void record_error(void);
extern void test_control_return(UINT status);
extern void _nx_ram_network_driver_256(struct NX_IP_DRIVER_STRUCT *driver_req);

static ULONG bsd_thread_area[DEMO_STACK_SIZE / sizeof(ULONG)];

/* Count a failure and remember the phase it happened in. */
static void record_error(void)
{
    if (error_phase < 0)
        error_phase = test_phase;

    error_counter = error_counter + 1;
}

#ifdef CTEST
VOID test_application_define(void *first_unused_memory)
#else
void netx_bsd_tcp_accept_socket_limit_shared_test_application_define(void *first_unused_memory)
#endif
{
CHAR   *pointer = (CHAR *)first_unused_memory;
UINT    status;

    error_counter = 0;
    test_phase = 0;
    error_phase = -1;
    client_port = 0;

    tx_thread_create(&ntest_0, "thread 0", ntest_0_entry, 0,
                     pointer, DEMO_STACK_SIZE, 3, 3,
                     TX_NO_TIME_SLICE, TX_AUTO_START);
    pointer += DEMO_STACK_SIZE;

    tx_thread_create(&ntest_1, "thread 1", ntest_1_entry, 0,
                     pointer, DEMO_STACK_SIZE, 3, 3,
                     TX_NO_TIME_SLICE, TX_AUTO_START);
    pointer += DEMO_STACK_SIZE;

    nx_system_initialize();

    status = nx_packet_pool_create(&pool_0, "NetX Main Packet Pool", 512,
                                   packet_pool_area, sizeof(packet_pool_area));
    if (status)
        record_error();

    status = nx_ip_create(&ip_0, "NetX IP Instance 0",
                          SERVER_ADDRESS, 0xFFFFFF00UL,
                          &pool_0, _nx_ram_network_driver_256,
                          pointer, 2048, 1);
    pointer += 2048;
    if (status)
        record_error();

#if (NX_MAX_PHYSICAL_INTERFACES > 1)
    /* The second master socket of the interface phase is bound to this
       interface, which is what makes bind() share the port. */
    status = nx_ip_interface_attach(&ip_0, "NetX IP Interface 1", SERVER_ADDRESS_2,
                                    0xFFFFFF00UL, _nx_ram_network_driver_256);
    if (status)
        record_error();
#endif /* NX_MAX_PHYSICAL_INTERFACES > 1 */

    status = nx_ip_create(&ip_1, "NetX IP Instance 1",
                          CLIENT_ADDRESS, 0xFFFFFF00UL,
                          &pool_0, _nx_ram_network_driver_256,
                          pointer, 2048, 1);
    pointer += 2048;
    if (status)
        record_error();

    status = nx_arp_enable(&ip_0, (void *)pointer, 1024);
    pointer += 1024;
    if (status)
        record_error();

    status = nx_arp_enable(&ip_1, (void *)pointer, 1024);
    pointer += 1024;
    if (status)
        record_error();

    status = nx_tcp_enable(&ip_0);
    status += nx_tcp_enable(&ip_1);
    if (status)
        record_error();

    status = bsd_initialize(&ip_0, &pool_0, (CHAR *)&bsd_thread_area[0],
                            sizeof(bsd_thread_area), BSD_THREAD_PRIORITY);
    if (status)
        record_error();

    status = tx_semaphore_create(&sema_0, "SEMA 0", 0);
    status += tx_semaphore_create(&sema_1, "SEMA 1", 0);
    if (status)
        record_error();
}

/* Determine whether the IP instance still has an active TCP listen request on
   the given port.  The list is only modified by the listen/unlisten calls this
   test makes, so it is walked without the IP protection mutex.  */
static UINT listen_request_active(NX_IP *ip_ptr, UINT port)
{
NX_TCP_LISTEN   *listen_ptr;

    listen_ptr = ip_ptr -> nx_ip_tcp_active_listen_requests;

    if (listen_ptr == NX_NULL)
        return(NX_FALSE);

    /* The active listen list is circular, so stop on the head.  */
    do
    {

        if (listen_ptr -> nx_tcp_listen_port == port)
            return(NX_TRUE);

        listen_ptr = listen_ptr -> nx_tcp_listen_next;
    } while (listen_ptr != ip_ptr -> nx_ip_tcp_active_listen_requests);

    return(NX_FALSE);
}

/* Take every free BSD socket, so that accept() cannot allocate the replacement
   secondary socket.  Returns the number of sockets taken. */
static INT socket_table_exhaust(INT *filler)
{
INT count;

    for (count = 0; count < NX_BSD_MAX_SOCKETS; count++)
    {

        filler[count] = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);

        if (filler[count] < 0)
            break;
    }

    /* One socket() call has to have failed, otherwise the table was not full and
       the rest of the phase would not exercise the intended path. */
    if (count == NX_BSD_MAX_SOCKETS)
        record_error();

    return(count);
}

static VOID socket_table_release(INT *filler, INT count)
{
INT i;

    for (i = 0; i < count; i++)
        soc_close(filler[i]);
}

/* Run one shared-port phase.  The first master socket is bound to first_address,
   the second one joins the port through the SO_REUSEADDR branch of bind(), either
   from the other address family or from the second interface. */
static void shared_port_phase(INT second_family, ULONG second_address, UINT port)
{
struct sockaddr_in   server_addr;
struct sockaddr_in   second_addr;
#ifdef FEATURE_NX_IPV6
struct sockaddr_in6  second6_addr;
#endif /* FEATURE_NX_IPV6 */
struct sockaddr_in   client_addr;
INT                  master_sock;
INT                  master2_sock;
INT                  conn_sock;
INT                  reuse_sock;
INT                  filler[NX_BSD_MAX_SOCKETS];
INT                  filler_count;
INT                  client_addr_len;
INT                  option_value;
INT                  n;
CHAR                 buf[16];

#ifndef FEATURE_NX_IPV6
    NX_PARAMETER_NOT_USED(second_family);
#endif /* FEATURE_NX_IPV6 */

    /* The first master socket owns the secondary socket that carries the NetX
       listen on the port. */
    master_sock = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    if (master_sock < 0)
        record_error();

    memset(&server_addr, 0, sizeof(server_addr));
    server_addr.sin_family      = AF_INET;
    server_addr.sin_port        = htons(port);
    server_addr.sin_addr.s_addr = htonl(SERVER_ADDRESS);

    if (bind(master_sock, (struct sockaddr *)&server_addr, sizeof(server_addr)) < 0)
        record_error();

    if (listen(master_sock, 5) < 0)
        record_error();

    if (listen_request_active(&ip_0, port) != NX_TRUE)
        record_error();

    /* The second master socket on the same port. */
    master2_sock = socket(second_family, SOCK_STREAM, IPPROTO_TCP);
    if (master2_sock < 0)
        record_error();

    option_value = 1;
    if (setsockopt(master2_sock, SOL_SOCKET, SO_REUSEADDR,
                   &option_value, sizeof(option_value)) < 0)
        record_error();

#ifdef FEATURE_NX_IPV6
    if (second_family == AF_INET6)
    {

        /* in6addr_any needs no IPv6 address on the instance: this socket only has
           to be a second master socket on the port, all traffic here is IPv4. */
        memset(&second6_addr, 0, sizeof(second6_addr));
        second6_addr.sin6_family = AF_INET6;
        second6_addr.sin6_port   = htons(port);

        if (bind(master2_sock, (struct sockaddr *)&second6_addr, sizeof(second6_addr)) < 0)
            record_error();
    }
    else
#endif /* FEATURE_NX_IPV6 */
    {

        memset(&second_addr, 0, sizeof(second_addr));
        second_addr.sin_family      = AF_INET;
        second_addr.sin_port        = htons(port);
        second_addr.sin_addr.s_addr = htonl(second_address);

        if (bind(master2_sock, (struct sockaddr *)&second_addr, sizeof(second_addr)) < 0)
            record_error();
    }

    if (listen(master2_sock, 5) < 0)
        record_error();

    /* The second listen() shares the existing secondary socket, so there is still
       exactly one listen request on the port. */
    if (listen_request_active(&ip_0, port) != NX_TRUE)
        record_error();

    /* Let the peer connect and send.  Its socket has to be allocated before the
       socket table is exhausted below. */
    client_port = port;
    tx_semaphore_put(&sema_1);
    tx_semaphore_get(&sema_0, 5 * NX_IP_PERIODIC_RATE);

    filler_count = socket_table_exhaust(filler);

    /* accept() hands over the pending connection although it cannot create the
       replacement listen socket.  That invalidates the secondary socket id of
       both master sockets. */
    client_addr_len = sizeof(client_addr);

    conn_sock = accept(master_sock, (struct sockaddr *)&client_addr, &client_addr_len);

    if (conn_sock < 0)
        record_error();
    else
    {

        memset(buf, 0, sizeof(buf));

        n = recv(conn_sock, buf, sizeof(buf), 0);

        if ((n != 5) || memcmp(buf, "Hello", 5))
            record_error();

        soc_close(conn_sock);
    }

    socket_table_release(filler, filler_count);

    /* Let the peer close its side. */
    tx_semaphore_put(&sema_1);
    tx_semaphore_get(&sema_0, 5 * NX_IP_PERIODIC_RATE);

    /* The other master socket is still listening on the port, so closing the
       first one must not release the listen. */
    if (soc_close(master_sock) < 0)
        record_error();

    if (listen_request_active(&ip_0, port) != NX_TRUE)
        record_error();

    /* The second master socket is now the last one on the port, so closing it
       must release the listen. */
    if (soc_close(master2_sock) < 0)
        record_error();

    if (listen_request_active(&ip_0, port) != NX_FALSE)
        record_error();

    /* With the listen released the port is free again. */
    reuse_sock = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    if (reuse_sock < 0)
        record_error();

    if (bind(reuse_sock, (struct sockaddr *)&server_addr, sizeof(server_addr)) < 0)
        record_error();

    if (listen(reuse_sock, 5) < 0)
        record_error();

    if (listen_request_active(&ip_0, port) != NX_TRUE)
        record_error();

    soc_close(reuse_sock);
}

static void ntest_0_entry(ULONG thread_input)
{
    NX_PARAMETER_NOT_USED(thread_input);

    /* Print out test information banner.  */
    printf("NetX Test:   BSD TCP Accept Socket Limit Shared Test.......");

#ifdef FEATURE_NX_IPV6

    /* ================================================================
     * Test 1: an IPv4 and an IPv6 master socket on one port.
     * ================================================================ */
    test_phase = 1;

    shared_port_phase(AF_INET6, 0, IPV6_PHASE_PORT);
#endif /* FEATURE_NX_IPV6 */

#if (NX_MAX_PHYSICAL_INTERFACES > 1)

    /* ================================================================
     * Test 2: two IPv4 master sockets, one per interface.  The second one
     *         has no NetX port of its own, so this is the phase that needs
     *         the release to use the port of the BSD socket.
     * ================================================================ */
    test_phase = 2;

    shared_port_phase(AF_INET, SERVER_ADDRESS_2, IF_PHASE_PORT);
#endif /* NX_MAX_PHYSICAL_INTERFACES > 1 */

    /* Let the peer thread finish. */
    client_port = 0;
    tx_semaphore_put(&sema_1);
    tx_semaphore_get(&sema_0, 5 * NX_IP_PERIODIC_RATE);

    if (error_counter)
    {
        printf("ERROR! (phase %d)\n", error_phase);
        test_control_return(1);
    }
    else
    {
        printf("SUCCESS!\n");
        test_control_return(0);
    }
}

/* Peer thread: one client socket per phase, on the port the server asks for. */
static void ntest_1_entry(ULONG thread_input)
{
struct sockaddr_in  server_addr;
INT                 client_sock;
ULONG               actual_status;

    NX_PARAMETER_NOT_USED(thread_input);

    nx_ip_status_check(&ip_1, NX_IP_INITIALIZE_DONE, &actual_status,
                       5 * NX_IP_PERIODIC_RATE);

    while (1)
    {

        tx_semaphore_get(&sema_1, 5 * NX_IP_PERIODIC_RATE);

        if (client_port == 0)
            break;

        client_sock = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
        if (client_sock < 0)
            record_error();

        memset(&server_addr, 0, sizeof(server_addr));
        server_addr.sin_family      = AF_INET;
        server_addr.sin_port        = htons(client_port);
        server_addr.sin_addr.s_addr = htonl(SERVER_ADDRESS);

        if (connect(client_sock, (struct sockaddr *)&server_addr,
                    sizeof(server_addr)) < 0)
            record_error();

        if (send(client_sock, "Hello", 5, 0) != 5)
            record_error();

        tx_semaphore_put(&sema_0);

        /* Wait until the server is done with the connection. */
        tx_semaphore_get(&sema_1, 5 * NX_IP_PERIODIC_RATE);

        soc_close(client_sock);

        tx_semaphore_put(&sema_0);
    }

    tx_semaphore_put(&sema_0);
}

#else

extern void test_control_return(UINT status);

#ifdef CTEST
VOID test_application_define(void *first_unused_memory)
#else
void netx_bsd_tcp_accept_socket_limit_shared_test_application_define(void *first_unused_memory)
#endif
{
    NX_PARAMETER_NOT_USED(first_unused_memory);

    /* Print out test information banner.  */
    printf("NetX Test:   BSD TCP Accept Socket Limit Shared Test.......N/A\n");

    test_control_return(3);
}

#endif /* NX_BSD_ENABLE && !NX_DISABLE_IPV4 && (FEATURE_NX_IPV6 || NX_MAX_PHYSICAL_INTERFACES > 1) */
