/***************************************************************************
 * Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* This test covers the MSG_OOB entry points of the BSD layer that need no
 * urgent data on the wire, so it runs against the plain RAM driver.
 *
 * NetX Duo has no service to send TCP urgent data - URG handling is receive
 * side only - so the BSD layer rejects MSG_OOB on the send side instead of
 * putting the byte in the normal stream where the caller could not notice.  On
 * the receive side MSG_OOB is served from the per socket out-of-band queue,
 * never suspends, and reports EWOULDBLOCK when that queue is empty.
 *
 *  1. send() with MSG_OOB on a connected TCP socket must fail with EOPNOTSUPP.
 *
 *  2. sendto() with MSG_OOB on a UDP socket must fail with EOPNOTSUPP.
 *
 *  3. recv() with MSG_OOB on a blocking TCP socket with no urgent data must
 *     return EWOULDBLOCK without suspending, even though in-band data is
 *     waiting, and it must not consume that in-band data.
 *
 *  4. recvfrom(), recvfromto() and recvmsg() with MSG_OOB behave the same way.
 *
 *  5. MSG_OOB on a UDP socket must fail with EOPNOTSUPP - there is no urgent
 *     data outside TCP.
 *
 *  6. A UDP socket with a datagram waiting must be reported in readfds only.
 *     UDP has no out-of-band concept, so exceptfds must stay clear.
 */

#include "tx_api.h"
#include "nx_api.h"
#if defined(NX_BSD_ENABLE) && !defined(NX_DISABLE_IPV4)
#include "nxd_bsd.h"

#define DEMO_STACK_SIZE     4096
#define BSD_THREAD_PRIORITY 2

#define SERVER_ADDRESS      IP_ADDRESS(1, 2, 3, 4)
#define CLIENT_ADDRESS      IP_ADDRESS(1, 2, 3, 5)
#define SERVER_PORT         5555
#define UDP_PORT            5556

static TX_THREAD        ntest_0;
static TX_THREAD        ntest_1;

static NX_PACKET_POOL   pool_0;
static NX_IP            ip_0;
static NX_IP            ip_1;
static TX_SEMAPHORE     sema_0;
static TX_SEMAPHORE     sema_1;

static ULONG            error_counter;

static ULONG            packet_pool_area[(512 + sizeof(NX_PACKET)) * 32 / 4];

static void ntest_0_entry(ULONG thread_input);
static void ntest_1_entry(ULONG thread_input);
extern void test_control_return(UINT status);
extern void _nx_ram_network_driver_256(struct NX_IP_DRIVER_STRUCT *driver_req);

static ULONG bsd_thread_area[DEMO_STACK_SIZE / sizeof(ULONG)];

#ifdef CTEST
VOID test_application_define(void *first_unused_memory)
#else
void netx_bsd_tcp_oob_errno_test_application_define(void *first_unused_memory)
#endif
{
CHAR   *pointer = (CHAR *)first_unused_memory;
UINT    status;

    error_counter = 0;

    tx_thread_create(&ntest_0, "thread 0", ntest_0_entry, 0,
                     pointer, DEMO_STACK_SIZE, 3, 3,
                     TX_NO_TIME_SLICE, TX_AUTO_START);
    pointer += DEMO_STACK_SIZE;

    tx_thread_create(&ntest_1, "thread 1", ntest_1_entry, 0,
                     pointer, DEMO_STACK_SIZE, 3, 3,
                     TX_NO_TIME_SLICE, TX_AUTO_START);
    pointer += DEMO_STACK_SIZE;

    nx_system_initialize();

    status = nx_packet_pool_create(&pool_0, "NetX Main Packet Pool", 512,
                                   packet_pool_area, sizeof(packet_pool_area));
    if (status)
        error_counter++;

    status = nx_ip_create(&ip_0, "NetX IP Instance 0",
                          SERVER_ADDRESS, 0xFFFFFF00UL,
                          &pool_0, _nx_ram_network_driver_256,
                          pointer, 2048, 1);
    pointer += 2048;
    if (status)
        error_counter++;

    status = nx_ip_create(&ip_1, "NetX IP Instance 1",
                          CLIENT_ADDRESS, 0xFFFFFF00UL,
                          &pool_0, _nx_ram_network_driver_256,
                          pointer, 2048, 1);
    pointer += 2048;
    if (status)
        error_counter++;

    status = nx_arp_enable(&ip_0, (void *)pointer, 1024);
    pointer += 1024;
    if (status)
        error_counter++;

    status = nx_arp_enable(&ip_1, (void *)pointer, 1024);
    pointer += 1024;
    if (status)
        error_counter++;

    status = nx_tcp_enable(&ip_0);
    status += nx_tcp_enable(&ip_1);
    status += nx_udp_enable(&ip_0);
    status += nx_udp_enable(&ip_1);
    if (status)
        error_counter++;

    status = bsd_initialize(&ip_0, &pool_0, (CHAR *)&bsd_thread_area[0],
                            sizeof(bsd_thread_area), BSD_THREAD_PRIORITY);
    if (status)
        error_counter++;

    status = tx_semaphore_create(&sema_0, "SEMA 0", 0);
    status += tx_semaphore_create(&sema_1, "SEMA 1", 0);
    if (status)
        error_counter++;
}

static void ntest_0_entry(ULONG thread_input)
{
struct sockaddr_in  server_addr;
struct sockaddr_in  udp_addr;
struct sockaddr_in  client_addr;
struct sockaddr_in  from_addr;
struct sockaddr_in  to_addr;
struct nx_bsd_iovec iov[2];
struct nx_bsd_msghdr msg;
struct timeval      tv;
fd_set              readfds;
fd_set              exceptfds;
INT                 master_sock;
INT                 conn_sock;
INT                 udp_sock;
INT                 client_addr_len;
INT                 from_addr_len;
INT                 to_addr_len;
INT                 n;
INT                 nfd;
ULONG               start_time;
CHAR                buf[16];
CHAR                buf2[16];

    NX_PARAMETER_NOT_USED(thread_input);

    /* Print out test information banner.  */
    printf("NetX Test:   BSD TCP OOB Errno Test........................");

    /* ================================================================
     * Set up a connected TCP socket.
     * ================================================================ */
    master_sock = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    if (master_sock < 0)
        error_counter++;

    memset(&server_addr, 0, sizeof(server_addr));
    server_addr.sin_family      = AF_INET;
    server_addr.sin_port        = htons(SERVER_PORT);
    server_addr.sin_addr.s_addr = INADDR_ANY;

    if (bind(master_sock, (struct sockaddr *)&server_addr, sizeof(server_addr)) < 0)
        error_counter++;

    if (listen(master_sock, 5) < 0)
        error_counter++;

    /* Let the client connect and send its in-band data. */
    tx_semaphore_put(&sema_1);
    tx_semaphore_get(&sema_0, 5 * NX_IP_PERIODIC_RATE);

    client_addr_len = sizeof(client_addr);
    conn_sock = accept(master_sock, (struct sockaddr *)&client_addr, &client_addr_len);
    if (conn_sock < 0)
        error_counter++;

    /* ================================================================
     * Test 1: send() with MSG_OOB is rejected - there is no service to
     *         put urgent data on the wire.
     * ================================================================ */
    n = send(conn_sock, "u", 1, MSG_OOB);

    if ((n != NX_SOC_ERROR) || (errno != EOPNOTSUPP))
        error_counter++;

    /* The same has to hold when MSG_OOB is combined with another flag. */
    n = send(conn_sock, "u", 1, MSG_OOB | MSG_DONTWAIT);

    if ((n != NX_SOC_ERROR) || (errno != EOPNOTSUPP))
        error_counter++;

    /* ================================================================
     * Test 3: recv() with MSG_OOB on a blocking socket must report
     *         EWOULDBLOCK right away, although in-band data is waiting.
     * ================================================================ */
    start_time = tx_time_get();

    n = recv(conn_sock, buf, sizeof(buf), MSG_OOB);

    if ((n != NX_SOC_ERROR) || (errno != EWOULDBLOCK))
        error_counter++;

    /* It must not have suspended.  The socket is blocking and holds in-band
       data, so a call that waits or falls back to the in-band stream shows up
       either as elapsed time or as a positive return above. */
    if ((tx_time_get() - start_time) > (NX_IP_PERIODIC_RATE / 10))
        error_counter++;

    /* ================================================================
     * Test 4: the same through recvfrom(), recvfromto() and recvmsg().
     * ================================================================ */
    from_addr_len = sizeof(from_addr);

    n = recvfrom(conn_sock, buf, sizeof(buf), MSG_OOB,
                 (struct sockaddr *)&from_addr, &from_addr_len);

    if ((n != NX_SOC_ERROR) || (errno != EWOULDBLOCK))
        error_counter++;

    from_addr_len = sizeof(from_addr);
    to_addr_len   = sizeof(to_addr);

    n = recvfromto(conn_sock, buf, sizeof(buf), MSG_OOB,
                   (struct sockaddr *)&from_addr, &from_addr_len,
                   (struct sockaddr *)&to_addr, &to_addr_len);

    if ((n != NX_SOC_ERROR) || (errno != EWOULDBLOCK))
        error_counter++;

    /* recvmsg() with more than one buffer takes the iovec path of the
       out-of-band read. */
    iov[0].iov_base = buf;
    iov[0].iov_len  = 1;
    iov[1].iov_base = buf2;
    iov[1].iov_len  = sizeof(buf2);

    memset(&msg, 0, sizeof(msg));
    msg.msg_iov    = iov;
    msg.msg_iovlen = 2;

    n = recvmsg(conn_sock, &msg, MSG_OOB);

    if ((n != NX_SOC_ERROR) || (errno != EWOULDBLOCK))
        error_counter++;

    /* ================================================================
     * Test 3 (continued): none of the failed out-of-band reads may have
     *         consumed the in-band data.
     * ================================================================ */
    n = recv(conn_sock, buf, sizeof(buf), 0);

    if ((n != 5) || memcmp(buf, "Hello", 5))
        error_counter++;

    /* ================================================================
     * Test 2 and 5: MSG_OOB on a UDP socket.
     * ================================================================ */
    udp_sock = socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP);
    if (udp_sock < 0)
        error_counter++;

    memset(&udp_addr, 0, sizeof(udp_addr));
    udp_addr.sin_family      = AF_INET;
    udp_addr.sin_port        = htons(UDP_PORT);
    udp_addr.sin_addr.s_addr = INADDR_ANY;

    if (bind(udp_sock, (struct sockaddr *)&udp_addr, sizeof(udp_addr)) < 0)
        error_counter++;

    /* Test 2: the sendto() path rejects MSG_OOB as well. */
    udp_addr.sin_addr.s_addr = htonl(SERVER_ADDRESS);

    n = sendto(udp_sock, "u", 1, MSG_OOB, (struct sockaddr *)&udp_addr, sizeof(udp_addr));

    if ((n != NX_SOC_ERROR) || (errno != EOPNOTSUPP))
        error_counter++;

    /* Test 5: there is no urgent data outside TCP. */
    n = recv(udp_sock, buf, sizeof(buf), MSG_OOB);

    if ((n != NX_SOC_ERROR) || (errno != EOPNOTSUPP))
        error_counter++;

    from_addr_len = sizeof(from_addr);

    n = recvfrom(udp_sock, buf, sizeof(buf), MSG_OOB,
                 (struct sockaddr *)&from_addr, &from_addr_len);

    if ((n != NX_SOC_ERROR) || (errno != EOPNOTSUPP))
        error_counter++;

    /* ================================================================
     * Test 6: a UDP socket with a datagram waiting is readable and must
     *         never be reported in exceptfds.
     * ================================================================ */
    tx_semaphore_put(&sema_1);
    tx_semaphore_get(&sema_0, 5 * NX_IP_PERIODIC_RATE);

    FD_ZERO(&readfds);
    FD_ZERO(&exceptfds);
    FD_SET(udp_sock, &readfds);
    FD_SET(udp_sock, &exceptfds);

    nfd = udp_sock + 1;
    tv.tv_sec  = 5;
    tv.tv_usec = 0;

    n = select(nfd, &readfds, NX_NULL, &exceptfds, &tv);

    if (n <= 0)
        error_counter++;
    if (!FD_ISSET(udp_sock, &readfds))
        error_counter++;
    if (FD_ISSET(udp_sock, &exceptfds))
        error_counter++;

    /* The datagram is in-band data, so a plain recv() returns it. */
    n = recv(udp_sock, buf, sizeof(buf), 0);

    if ((n != 3) || memcmp(buf, "udp", 3))
        error_counter++;

    soc_close(udp_sock);
    soc_close(conn_sock);
    soc_close(master_sock);

    /* Let the client close its socket. */
    tx_semaphore_put(&sema_1);
    tx_semaphore_get(&sema_0, 5 * NX_IP_PERIODIC_RATE);

    if (error_counter)
    {
        printf("ERROR!\n");
        test_control_return(1);
    }
    else
    {
        printf("SUCCESS!\n");
        test_control_return(0);
    }
}

/* Client thread: supplies the in-band TCP data and the UDP datagram. */
static void ntest_1_entry(ULONG thread_input)
{
struct sockaddr_in  server_addr;
INT                 client_sock;
INT                 udp_sock;
ULONG               actual_status;

    NX_PARAMETER_NOT_USED(thread_input);

    nx_ip_status_check(&ip_1, NX_IP_INITIALIZE_DONE, &actual_status,
                       5 * NX_IP_PERIODIC_RATE);

    /* Wait for the server socket to listen. */
    tx_semaphore_get(&sema_1, 5 * NX_IP_PERIODIC_RATE);

    client_sock = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    if (client_sock < 0)
        error_counter++;

    memset(&server_addr, 0, sizeof(server_addr));
    server_addr.sin_family      = AF_INET;
    server_addr.sin_port        = htons(SERVER_PORT);
    server_addr.sin_addr.s_addr = htonl(SERVER_ADDRESS);

    if (connect(client_sock, (struct sockaddr *)&server_addr,
                sizeof(server_addr)) < 0)
        error_counter++;

    if (send(client_sock, "Hello", 5, 0) < 0)
        error_counter++;

    tx_semaphore_put(&sema_0);

    /* Wait until the server is ready for the datagram. */
    tx_semaphore_get(&sema_1, 5 * NX_IP_PERIODIC_RATE);

    udp_sock = socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP);
    if (udp_sock < 0)
        error_counter++;

    memset(&server_addr, 0, sizeof(server_addr));
    server_addr.sin_family      = AF_INET;
    server_addr.sin_port        = htons(UDP_PORT);
    server_addr.sin_addr.s_addr = htonl(SERVER_ADDRESS);

    if (sendto(udp_sock, "udp", 3, 0, (struct sockaddr *)&server_addr,
               sizeof(server_addr)) < 0)
        error_counter++;

    tx_semaphore_put(&sema_0);

    /* Wait until the server is done with its sockets. */
    tx_semaphore_get(&sema_1, 5 * NX_IP_PERIODIC_RATE);

    soc_close(udp_sock);
    soc_close(client_sock);

    tx_semaphore_put(&sema_0);
}

#else

extern void test_control_return(UINT status);

#ifdef CTEST
VOID test_application_define(void *first_unused_memory)
#else
void netx_bsd_tcp_oob_errno_test_application_define(void *first_unused_memory)
#endif
{
    NX_PARAMETER_NOT_USED(first_unused_memory);

    /* Print out test information banner.  */
    printf("NetX Test:   BSD TCP OOB Errno Test........................N/A\n");

    test_control_return(3);
}

#endif /* NX_BSD_ENABLE && !NX_DISABLE_IPV4 */
