/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* This test covers accept() on a master socket while every BSD socket is in use,
 * and everything that follows from it.
 *
 * accept() hands the connected secondary socket to the caller and then creates a
 * replacement secondary socket to keep listening on the port.  When no BSD socket
 * is left that replacement cannot be created, so accept() invalidates the
 * secondary socket id of the master socket - the socket the application now owns
 * is still referenced there - and returns the connection anyway.  Four things
 * follow from that, and this test pins all of them on one master socket:
 *
 *  1. accept() still returns the pending connection, and the socket it returns is
 *     a working connection.
 *
 *  2. The master socket recovers on its own.  Once a socket is free again, its
 *     next accept() allocates a new secondary socket and takes the next
 *     connection normally.
 *
 *  3. Closing the master socket while its secondary socket id is invalid releases
 *     the listen that the failed accept() left on the port - it is only reachable
 *     through that master socket - and leaves every accepted connection alone.
 *     Without the invalidation the close would disconnect and release the socket
 *     the application owns.
 *
 *  4. With the listen released the port is free again, so a new socket can listen
 *     on it.
 *
 * The shared-port side of the same clean-up, where more than one master socket
 * sits on the port, is covered by netx_bsd_tcp_accept_socket_limit_shared_test.
 */

#include "tx_api.h"
#include "nx_api.h"
#if defined(NX_BSD_ENABLE) && !defined(NX_DISABLE_IPV4)
#include "nxd_bsd.h"

#define DEMO_STACK_SIZE     4096
#define BSD_THREAD_PRIORITY 2

#define SERVER_ADDRESS      IP_ADDRESS(1, 2, 3, 4)
#define CLIENT_ADDRESS      IP_ADDRESS(1, 2, 3, 5)
#define SERVER_PORT         5555

static TX_THREAD        ntest_0;
static TX_THREAD        ntest_1;

static NX_PACKET_POOL   pool_0;
static NX_IP            ip_0;
static NX_IP            ip_1;
static TX_SEMAPHORE     sema_0;
static TX_SEMAPHORE     sema_1;

static ULONG            error_counter;

/* Phase the test is in, and the phase of the first failure, so that a failure of
   this test still says where to look. */
static INT              test_phase;
static INT              error_phase;

static ULONG            packet_pool_area[(512 + sizeof(NX_PACKET)) * 32 / 4];

static void ntest_0_entry(ULONG thread_input);
static void ntest_1_entry(ULONG thread_input);
static void record_error(void);
extern void test_control_return(UINT status);
extern void _nx_ram_network_driver_256(struct NX_IP_DRIVER_STRUCT *driver_req);

static ULONG bsd_thread_area[DEMO_STACK_SIZE / sizeof(ULONG)];

/* Count a failure and remember the phase it happened in. */
static void record_error(void)
{
    if (error_phase < 0)
        error_phase = test_phase;

    error_counter = error_counter + 1;
}

#ifdef CTEST
VOID test_application_define(void *first_unused_memory)
#else
void netx_bsd_tcp_accept_socket_limit_test_application_define(void *first_unused_memory)
#endif
{
CHAR   *pointer = (CHAR *)first_unused_memory;
UINT    status;

    error_counter = 0;
    test_phase = 0;
    error_phase = -1;

    tx_thread_create(&ntest_0, "thread 0", ntest_0_entry, 0,
                     pointer, DEMO_STACK_SIZE, 3, 3,
                     TX_NO_TIME_SLICE, TX_AUTO_START);
    pointer += DEMO_STACK_SIZE;

    tx_thread_create(&ntest_1, "thread 1", ntest_1_entry, 0,
                     pointer, DEMO_STACK_SIZE, 3, 3,
                     TX_NO_TIME_SLICE, TX_AUTO_START);
    pointer += DEMO_STACK_SIZE;

    nx_system_initialize();

    status = nx_packet_pool_create(&pool_0, "NetX Main Packet Pool", 512,
                                   packet_pool_area, sizeof(packet_pool_area));
    if (status)
        record_error();

    status = nx_ip_create(&ip_0, "NetX IP Instance 0",
                          SERVER_ADDRESS, 0xFFFFFF00UL,
                          &pool_0, _nx_ram_network_driver_256,
                          pointer, 2048, 1);
    pointer += 2048;
    if (status)
        record_error();

    status = nx_ip_create(&ip_1, "NetX IP Instance 1",
                          CLIENT_ADDRESS, 0xFFFFFF00UL,
                          &pool_0, _nx_ram_network_driver_256,
                          pointer, 2048, 1);
    pointer += 2048;
    if (status)
        record_error();

    status = nx_arp_enable(&ip_0, (void *)pointer, 1024);
    pointer += 1024;
    if (status)
        record_error();

    status = nx_arp_enable(&ip_1, (void *)pointer, 1024);
    pointer += 1024;
    if (status)
        record_error();

    status = nx_tcp_enable(&ip_0);
    status += nx_tcp_enable(&ip_1);
    if (status)
        record_error();

    status = bsd_initialize(&ip_0, &pool_0, (CHAR *)&bsd_thread_area[0],
                            sizeof(bsd_thread_area), BSD_THREAD_PRIORITY);
    if (status)
        record_error();

    status = tx_semaphore_create(&sema_0, "SEMA 0", 0);
    status += tx_semaphore_create(&sema_1, "SEMA 1", 0);
    if (status)
        record_error();
}

/* Determine whether the IP instance still has an active TCP listen request on
   the given port.  The list is only modified by the listen/unlisten calls this
   test makes, so it is walked without the IP protection mutex.  */
static UINT listen_request_active(NX_IP *ip_ptr, UINT port)
{
NX_TCP_LISTEN   *listen_ptr;

    listen_ptr = ip_ptr -> nx_ip_tcp_active_listen_requests;

    if (listen_ptr == NX_NULL)
        return(NX_FALSE);

    /* The active listen list is circular, so stop on the head.  */
    do
    {

        if (listen_ptr -> nx_tcp_listen_port == port)
            return(NX_TRUE);

        listen_ptr = listen_ptr -> nx_tcp_listen_next;
    } while (listen_ptr != ip_ptr -> nx_ip_tcp_active_listen_requests);

    return(NX_FALSE);
}

/* Take every free BSD socket, so that accept() cannot allocate the replacement
   secondary socket.  Returns the number of sockets taken. */
static INT socket_table_exhaust(INT *filler)
{
INT count;

    for (count = 0; count < NX_BSD_MAX_SOCKETS; count++)
    {

        filler[count] = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);

        if (filler[count] < 0)
            break;
    }

    /* One socket() call has to have failed, otherwise the table was not full and
       the phase that follows would not exercise the intended path. */
    if (count == NX_BSD_MAX_SOCKETS)
        record_error();

    return(count);
}

static VOID socket_table_release(INT *filler, INT count)
{
INT i;

    for (i = 0; i < count; i++)
        soc_close(filler[i]);
}

static void ntest_0_entry(ULONG thread_input)
{
struct sockaddr_in  server_addr;
struct sockaddr_in  client_addr;
INT                 master_sock;
INT                 conn_sock[3];
INT                 reuse_sock;
INT                 filler[NX_BSD_MAX_SOCKETS];
INT                 filler_count;
INT                 client_addr_len;
INT                 i;
INT                 n;
CHAR                buf[16];

    NX_PARAMETER_NOT_USED(thread_input);

    /* Print out test information banner.  */
    printf("NetX Test:   Basic BSD TCP Accept Socket Limit Test........");

    master_sock = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    if (master_sock < 0)
        record_error();

    memset(&server_addr, 0, sizeof(server_addr));
    server_addr.sin_family      = AF_INET;
    server_addr.sin_port        = htons(SERVER_PORT);
    server_addr.sin_addr.s_addr = INADDR_ANY;

    if (bind(master_sock, (struct sockaddr *)&server_addr, sizeof(server_addr)) < 0)
        record_error();

    if (listen(master_sock, 5) < 0)
        record_error();

    /* listen() creates the secondary socket that carries the NetX listen, so the
       port is on the active listen list from here on. */
    if (listen_request_active(&ip_0, SERVER_PORT) != NX_TRUE)
        record_error();

    /* ================================================================
     * Test 1: the first connection is accepted while no socket is left,
     *         so the master socket ends up with an invalid secondary
     *         socket id, and the accepted socket has to work.
     * ================================================================ */
    test_phase = 1;
    tx_semaphore_put(&sema_1);
    tx_semaphore_get(&sema_0, 5 * NX_IP_PERIODIC_RATE);

    filler_count = socket_table_exhaust(filler);

    client_addr_len = sizeof(client_addr);
    conn_sock[0] = accept(master_sock, (struct sockaddr *)&client_addr, &client_addr_len);
    if (conn_sock[0] < 0)
        record_error();

    memset(buf, 0, sizeof(buf));

    n = recv(conn_sock[0], buf, sizeof(buf), 0);

    if ((n != 2) || memcmp(buf, "c1", 2))
        record_error();

    /* ================================================================
     * Test 2: with a socket free again, the next accept() on the master
     *         socket has to allocate a new secondary socket and take the
     *         connection that arrives afterwards.
     * ================================================================ */
    test_phase = 2;
    socket_table_release(filler, filler_count);

    /* The peer reports that it is about to connect.  There is no listening
       secondary socket at this moment, so its connect() only completes once the
       accept() below has created one. */
    tx_semaphore_put(&sema_1);
    tx_semaphore_get(&sema_0, 5 * NX_IP_PERIODIC_RATE);

    client_addr_len = sizeof(client_addr);
    conn_sock[1] = accept(master_sock, (struct sockaddr *)&client_addr, &client_addr_len);
    if (conn_sock[1] < 0)
        record_error();

    if (conn_sock[1] == conn_sock[0])
        record_error();

    tx_semaphore_get(&sema_0, 5 * NX_IP_PERIODIC_RATE);

    memset(buf, 0, sizeof(buf));

    n = recv(conn_sock[1], buf, sizeof(buf), 0);

    if ((n != 2) || memcmp(buf, "c2", 2))
        record_error();

    /* ================================================================
     * Test 3: the master socket is healthy again, so the third connection
     *         needs no help.  The socket table is exhausted afterwards, so
     *         this accept() invalidates the secondary socket id once more -
     *         that is the state in which the master socket is closed.
     * ================================================================ */
    test_phase = 3;
    tx_semaphore_put(&sema_1);
    tx_semaphore_get(&sema_0, 5 * NX_IP_PERIODIC_RATE);

    filler_count = socket_table_exhaust(filler);

    client_addr_len = sizeof(client_addr);
    conn_sock[2] = accept(master_sock, (struct sockaddr *)&client_addr, &client_addr_len);
    if (conn_sock[2] < 0)
        record_error();

    if ((conn_sock[2] == conn_sock[0]) || (conn_sock[2] == conn_sock[1]))
        record_error();

    memset(buf, 0, sizeof(buf));

    n = recv(conn_sock[2], buf, sizeof(buf), 0);

    if ((n != 2) || memcmp(buf, "c3", 2))
        record_error();

    socket_table_release(filler, filler_count);

    /* The listen left behind by the failed accept() is still there: it is only
       reachable through the master socket now. */
    if (listen_request_active(&ip_0, SERVER_PORT) != NX_TRUE)
        record_error();

    /* Closing the master socket has to release that listen and leave every
       accepted connection alone. */
    if (soc_close(master_sock) < 0)
        record_error();

    if (listen_request_active(&ip_0, SERVER_PORT) != NX_FALSE)
        record_error();

    for (i = 0; i < 3; i++)
    {

        if (send(conn_sock[i], "ping", 4, 0) != 4)
            record_error();
    }

    /* The peer echoes on all three connections. */
    tx_semaphore_put(&sema_1);
    tx_semaphore_get(&sema_0, 5 * NX_IP_PERIODIC_RATE);

    for (i = 0; i < 3; i++)
    {

        memset(buf, 0, sizeof(buf));

        n = recv(conn_sock[i], buf, sizeof(buf), 0);

        if ((n != 4) || memcmp(buf, "echo", 4))
            record_error();
    }

    for (i = 0; i < 3; i++)
        soc_close(conn_sock[i]);

    /* ================================================================
     * Test 4: with the listen released the port is free, so a new socket
     *         can listen on it again.
     * ================================================================ */
    test_phase = 4;

    reuse_sock = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    if (reuse_sock < 0)
        record_error();

    if (bind(reuse_sock, (struct sockaddr *)&server_addr, sizeof(server_addr)) < 0)
        record_error();

    if (listen(reuse_sock, 5) < 0)
        record_error();

    if (listen_request_active(&ip_0, SERVER_PORT) != NX_TRUE)
        record_error();

    soc_close(reuse_sock);

    /* Let the peer close its sockets. */
    tx_semaphore_put(&sema_1);
    tx_semaphore_get(&sema_0, 5 * NX_IP_PERIODIC_RATE);

    if (error_counter)
    {
        printf("ERROR! (phase %d)\n", error_phase);
        test_control_return(1);
    }
    else
    {
        printf("SUCCESS!\n");
        test_control_return(0);
    }
}

/* Peer thread: three client sockets, one per connection. */
static void ntest_1_entry(ULONG thread_input)
{
struct sockaddr_in  server_addr;
INT                 client_sock[3];
INT                 i;
INT                 n;
ULONG               actual_status;
CHAR                buf[16];

    NX_PARAMETER_NOT_USED(thread_input);

    nx_ip_status_check(&ip_1, NX_IP_INITIALIZE_DONE, &actual_status,
                       5 * NX_IP_PERIODIC_RATE);

    memset(&server_addr, 0, sizeof(server_addr));
    server_addr.sin_family      = AF_INET;
    server_addr.sin_port        = htons(SERVER_PORT);
    server_addr.sin_addr.s_addr = htonl(SERVER_ADDRESS);

    /* First connection: the master socket is listening, so this connects right
       away.  It has to be allocated before the socket table is exhausted. */
    tx_semaphore_get(&sema_1, 5 * NX_IP_PERIODIC_RATE);

    client_sock[0] = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    if (client_sock[0] < 0)
        record_error();

    if (connect(client_sock[0], (struct sockaddr *)&server_addr,
                sizeof(server_addr)) < 0)
        record_error();

    if (send(client_sock[0], "c1", 2, 0) != 2)
        record_error();

    tx_semaphore_put(&sema_0);

    /* Second connection: there is no listening secondary socket at this point,
       so report first and let connect() wait for the server's accept(). */
    tx_semaphore_get(&sema_1, 5 * NX_IP_PERIODIC_RATE);

    client_sock[1] = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    if (client_sock[1] < 0)
        record_error();

    tx_semaphore_put(&sema_0);

    if (connect(client_sock[1], (struct sockaddr *)&server_addr,
                sizeof(server_addr)) < 0)
        record_error();

    if (send(client_sock[1], "c2", 2, 0) != 2)
        record_error();

    tx_semaphore_put(&sema_0);

    /* Third connection: the master socket has recovered, so this connects right
       away again. */
    tx_semaphore_get(&sema_1, 5 * NX_IP_PERIODIC_RATE);

    client_sock[2] = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    if (client_sock[2] < 0)
        record_error();

    if (connect(client_sock[2], (struct sockaddr *)&server_addr,
                sizeof(server_addr)) < 0)
        record_error();

    if (send(client_sock[2], "c3", 2, 0) != 2)
        record_error();

    tx_semaphore_put(&sema_0);

    /* Echo on all three connections, to show that none of them was affected by
       the close of the master socket. */
    tx_semaphore_get(&sema_1, 5 * NX_IP_PERIODIC_RATE);

    for (i = 0; i < 3; i++)
    {

        memset(buf, 0, sizeof(buf));

        n = recv(client_sock[i], buf, sizeof(buf), 0);

        if ((n != 4) || memcmp(buf, "ping", 4))
            record_error();

        if (send(client_sock[i], "echo", 4, 0) != 4)
            record_error();
    }

    tx_semaphore_put(&sema_0);

    tx_semaphore_get(&sema_1, 5 * NX_IP_PERIODIC_RATE);

    for (i = 0; i < 3; i++)
        soc_close(client_sock[i]);

    tx_semaphore_put(&sema_0);
}

#else

extern void test_control_return(UINT status);

#ifdef CTEST
VOID test_application_define(void *first_unused_memory)
#else
void netx_bsd_tcp_accept_socket_limit_test_application_define(void *first_unused_memory)
#endif
{
    NX_PARAMETER_NOT_USED(first_unused_memory);

    /* Print out test information banner.  */
    printf("NetX Test:   Basic BSD TCP Accept Socket Limit Test........N/A\n");

    test_control_return(3);
}

#endif /* NX_BSD_ENABLE && !NX_DISABLE_IPV4 */
