/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/
// Some portions generated by Codex (gpt-5.6-sol).

/* This test covers the TCP urgent (out-of-band) data path of the BSD layer.
 *
 * NetX Duo cannot send urgent data, so the peer here is a plain NetX TCP socket
 * and the URG bit plus the urgent pointer are written into the segment on its way
 * into the receiving IP instance, by hooking nx_ip_tcp_packet_receive (the same
 * technique netx_tcp_urgent_packet_test uses).  The TCP checksum is recomputed
 * after the change, so the segment passes the receive checks.
 *
 * All phases run on one connection, and the urgent pointers are chosen so that
 * the absolute urgent sequence grows from phase to phase - the socket takes each
 * urgent byte only once, so a phase pointing back into an earlier one would be
 * skipped by that very rule.
 *
 *   1. A blocked select() that asks for readfds and exceptfds reports both when a
 *      segment carrying an urgent byte arrives, even when the selecting thread
 *      preempts the IP thread as soon as the readable-data callback wakes it.
 *
 *   2. The indication is level triggered - it stays up while the urgent byte is
 *      unread - recv(MSG_OOB) returns that byte, and the indication is gone once
 *      the out-of-band queue has been drained.
 *
 *   3. The urgent byte is removed from the in-band stream, so a plain recv()
 *      returns the payload without it.
 *
 *   4. An urgent pointer of zero is rejected.  It cannot be turned into a byte
 *      offset (the pointer is one past the urgent byte), and the subtraction
 *      would wrap, so no exception is raised and the payload stays intact.
 *
 *   5. An urgent pointer past the end of its segment raises the exception but
 *      queues no byte: recv(MSG_OOB) reports EWOULDBLOCK, that call clears the
 *      mark, and the payload stays intact.
 *
 *   6. With the default out-of-band queue depth of one, a second urgent byte that
 *      arrives before the first is read replaces it - POSIX keeps only the newest
 *      urgent byte.
 *
 *   7. MSG_OOB combined with MSG_PEEK returns the urgent byte without consuming
 *      it or clearing the exception indication.
 *
 *   8. An urgent byte in a chained packet extension is extracted without invalid
 *      pointer arithmetic and removed from the in-band stream.
 *
 *   9. Front-overlap trimming reduces the urgent pointer so it still identifies
 *      the intended urgent byte in the retained payload.
 *
 *  10. Front-overlap trimming clears an urgent pointer whose byte was discarded.
 *
 *  11. An urgent byte in a segment that arrives out of order is found by walking
 *      the receive queue: the segment that triggers the callback is normally the
 *      queue tail, but an out-of-order segment is inserted ahead of it, so the
 *      tail holds nothing new.  On the way the walk passes an earlier segment
 *      whose urgent byte was already taken, and the sequence number of that byte
 *      is what keeps it from being taken a second time.
 *
 *  12. The receive window is intact at the end.  Each urgent byte is cut out of
 *      the queued segment, and NetX hands window space back from the packet
 *      length at delivery time, so every urgent byte has to be added back to the
 *      window explicitly.
 *
 *  13. soc_close() drops an urgent byte the application never took, so the next
 *      socket that lands in that slot starts without a mark and without data.
 *
 * The MSG_OOB error paths that need no urgent data on the wire are covered by
 * netx_bsd_tcp_oob_errno_test.
 */

#include "tx_api.h"
#include "nx_api.h"
#include "nx_tcp.h"
#include "nx_ip.h"
#if defined(NX_BSD_ENABLE) && !defined(NX_DISABLE_IPV4)
#include "nxd_bsd.h"

#define DEMO_STACK_SIZE     4096
#define BSD_THREAD_PRIORITY 2

#define SERVER_ADDRESS      IP_ADDRESS(1, 2, 3, 4)
#define CLIENT_ADDRESS      IP_ADDRESS(1, 2, 3, 5)
#define SERVER_PORT         5555

static TX_THREAD        ntest_0;
static TX_THREAD        ntest_1;

static NX_PACKET_POOL   pool_0;
static NX_IP            ip_0;
static NX_IP            ip_1;
static NX_TCP_SOCKET    client_socket;
static TX_SEMAPHORE     sema_0;
static TX_SEMAPHORE     sema_1;

static ULONG            error_counter;

/* Urgent information for the next data segment that carries payload for the
   server port.  The hook disarms itself, so each arming affects one segment. */
static UINT             urg_arm;
static ULONG            urg_pointer;

/* Keep the armed segment back instead of delivering it, so that the segment
   after it arrives first and this one becomes an out-of-order arrival. */
static UINT             urg_hold;
static NX_PACKET       *held_packet_ptr;

/* Deliver a plain prefix copy before the armed segment.  The original then
   overlaps data already accepted by TCP and has to be trimmed at the front. */
static ULONG            urg_overlap_prefix;

/* Number of segments the hook has changed, and of held segments it has released
   behind a later one. */
static ULONG            urg_injected;
static ULONG            urg_reordered;
static ULONG            urg_chained_segments;

/* Payload the peer thread sends on request, and how long it waits first - the
   delay lets the server thread reach select() before the segment arrives. */
static const CHAR      *client_payload;
static ULONG            client_payload_length;
static ULONG            client_delay;

/* Phase the test is in, and the phase of the first failure, so that a failure of
   this test still says where to look. */
static INT              test_phase;
static INT              error_phase;

static CHAR             chain_payload[500];

static ULONG            packet_pool_area[(512 + sizeof(NX_PACKET)) * 48 / 4];

static void ntest_0_entry(ULONG thread_input);
static void ntest_1_entry(ULONG thread_input);
static void my_tcp_packet_receive(NX_IP *ip_ptr, NX_PACKET *packet_ptr);
static void record_error(void);
extern void test_control_return(UINT status);
extern void _nx_ram_network_driver_1500(struct NX_IP_DRIVER_STRUCT *driver_req);

static ULONG bsd_thread_area[DEMO_STACK_SIZE / sizeof(ULONG)];

/* Count a failure and remember the phase it happened in. */
static void record_error(void)
{
    if (error_phase < 0)
        error_phase = test_phase;

    error_counter = error_counter + 1;
}

#ifdef CTEST
VOID test_application_define(void *first_unused_memory)
#else
void netx_bsd_tcp_oob_test_application_define(void *first_unused_memory)
#endif
{
CHAR   *pointer = (CHAR *)first_unused_memory;
ULONG   i;
UINT    status;

    error_counter = 0;
    urg_arm = NX_FALSE;
    urg_pointer = 0;
    urg_hold = NX_FALSE;
    held_packet_ptr = NX_NULL;
    urg_overlap_prefix = 0;
    urg_injected = 0;
    urg_reordered = 0;
    urg_chained_segments = 0;
    client_delay = 0;
    test_phase = 0;
    error_phase = -1;

    for (i = 0; i < sizeof(chain_payload); i++)
    {
        chain_payload[i] = (CHAR)('a' + (i % 26));
    }

    tx_thread_create(&ntest_0, "thread 0", ntest_0_entry, 0,
                     pointer, DEMO_STACK_SIZE, 3, 3,
                     TX_NO_TIME_SLICE, TX_AUTO_START);
    pointer += DEMO_STACK_SIZE;

    tx_thread_create(&ntest_1, "thread 1", ntest_1_entry, 0,
                     pointer, DEMO_STACK_SIZE, 3, 3,
                     TX_NO_TIME_SLICE, TX_AUTO_START);
    pointer += DEMO_STACK_SIZE;

    nx_system_initialize();

    status = nx_packet_pool_create(&pool_0, "NetX Main Packet Pool", 512,
                                   packet_pool_area, sizeof(packet_pool_area));
    if (status)
        record_error();

    status = nx_ip_create(&ip_0, "NetX IP Instance 0",
                          SERVER_ADDRESS, 0xFFFFFF00UL,
                          &pool_0, _nx_ram_network_driver_1500,
                          pointer, 2048, 1);
    pointer += 2048;
    if (status)
        record_error();

    status = nx_ip_create(&ip_1, "NetX IP Instance 1",
                          CLIENT_ADDRESS, 0xFFFFFF00UL,
                          &pool_0, _nx_ram_network_driver_1500,
                          pointer, 2048, 1);
    pointer += 2048;
    if (status)
        record_error();

    status = nx_arp_enable(&ip_0, (void *)pointer, 1024);
    pointer += 1024;
    if (status)
        record_error();

    status = nx_arp_enable(&ip_1, (void *)pointer, 1024);
    pointer += 1024;
    if (status)
        record_error();

    status = nx_tcp_enable(&ip_0);
    status += nx_tcp_enable(&ip_1);
    if (status)
        record_error();

    status = bsd_initialize(&ip_0, &pool_0, (CHAR *)&bsd_thread_area[0],
                            sizeof(bsd_thread_area), BSD_THREAD_PRIORITY);
    if (status)
        record_error();

    status = tx_semaphore_create(&sema_0, "SEMA 0", 0);
    status += tx_semaphore_create(&sema_1, "SEMA 1", 0);
    if (status)
        record_error();

    /* Take over the TCP receive path of the BSD instance so that the urgent
       information can be written into a segment on its way in.  */
    ip_0.nx_ip_tcp_packet_receive = my_tcp_packet_receive;
}

/* Write the URG bit and the armed urgent pointer into the next TCP segment that
   carries payload for the server port and repair the TCP checksum.  A segment can
   also be kept back, in which case it is delivered right after the next data
   segment - which makes it an out-of-order arrival for the receiving socket. */
static void my_tcp_packet_receive(NX_IP *ip_ptr, NX_PACKET *packet_ptr)
{
NX_TCP_HEADER   *tcp_header_ptr;
NX_TCP_HEADER   *prefix_header_ptr;
NX_PACKET       *release_packet_ptr = NX_NULL;
NX_PACKET       *prefix_packet_ptr = NX_NULL;
ULONG            word_0;
ULONG            word_3;
ULONG            header_length;
ULONG            checksum;
ULONG            prefix_length;
ULONG            source_ip = CLIENT_ADDRESS;
ULONG            dest_ip = SERVER_ADDRESS;
UINT             status;

    tcp_header_ptr = (NX_TCP_HEADER *)packet_ptr -> nx_packet_prepend_ptr;

    /* The header is still in network order at this point, so work on copies. */
    word_0 = tcp_header_ptr -> nx_tcp_header_word_0;
    word_3 = tcp_header_ptr -> nx_tcp_header_word_3;
    NX_CHANGE_ULONG_ENDIAN(word_0);
    NX_CHANGE_ULONG_ENDIAN(word_3);

    header_length = ((word_3 >> NX_TCP_HEADER_SHIFT) * (ULONG)sizeof(ULONG));

    /* Only a data segment for the server port is of interest. */
    if (((word_0 & NX_LOWER_16_MASK) == SERVER_PORT) &&
        (packet_ptr -> nx_packet_length > header_length))
    {

        if (urg_arm == NX_TRUE)
        {

            urg_arm = NX_FALSE;

#ifndef NX_DISABLE_PACKET_CHAIN
            if (packet_ptr -> nx_packet_next != NX_NULL)
            {
                urg_chained_segments++;
            }
#endif /* NX_DISABLE_PACKET_CHAIN */

            /* Preserve a non-urgent prefix when this phase needs the original
               segment to overlap bytes TCP has already accepted. */
            if (urg_overlap_prefix != 0)
            {
                prefix_length = urg_overlap_prefix;
                urg_overlap_prefix = 0;

                status = nx_packet_copy(packet_ptr, &prefix_packet_ptr, &pool_0, NX_NO_WAIT);

                if (status != NX_SUCCESS)
                {
                    record_error();
                }
                else
                {
                    prefix_header_ptr = (NX_TCP_HEADER *)prefix_packet_ptr -> nx_packet_prepend_ptr;
                    prefix_packet_ptr -> nx_packet_append_ptr =
                        prefix_packet_ptr -> nx_packet_prepend_ptr + header_length + prefix_length;
                    prefix_packet_ptr -> nx_packet_length = header_length + prefix_length;

                    /* Recompute the checksum after shortening the duplicate. */
                    prefix_header_ptr -> nx_tcp_header_word_4 = 0;
                    checksum = _nx_ip_checksum_compute(prefix_packet_ptr, NX_PROTOCOL_TCP,
                                                       (UINT)prefix_packet_ptr -> nx_packet_length,
                                                       &source_ip, &dest_ip);
                    checksum = ~checksum & NX_LOWER_16_MASK;
                    prefix_header_ptr -> nx_tcp_header_word_4 = checksum << NX_SHIFT_BY_16;
                    NX_CHANGE_ULONG_ENDIAN(prefix_header_ptr -> nx_tcp_header_word_4);
                }
            }

            /* Set the URG bit. */
            NX_CHANGE_ULONG_ENDIAN(tcp_header_ptr -> nx_tcp_header_word_3);
            tcp_header_ptr -> nx_tcp_header_word_3 |= NX_TCP_URG_BIT;
            NX_CHANGE_ULONG_ENDIAN(tcp_header_ptr -> nx_tcp_header_word_3);

            /* Install the urgent pointer with a zero checksum field, so that the
               checksum below covers the urgent pointer as well. */
            tcp_header_ptr -> nx_tcp_header_word_4 = urg_pointer;
            NX_CHANGE_ULONG_ENDIAN(tcp_header_ptr -> nx_tcp_header_word_4);

            checksum = _nx_ip_checksum_compute(packet_ptr, NX_PROTOCOL_TCP,
                                               (UINT)packet_ptr -> nx_packet_length,
                                               &source_ip, &dest_ip);
            checksum = ~checksum & NX_LOWER_16_MASK;

            tcp_header_ptr -> nx_tcp_header_word_4 = (checksum << NX_SHIFT_BY_16) | urg_pointer;
            NX_CHANGE_ULONG_ENDIAN(tcp_header_ptr -> nx_tcp_header_word_4);

            urg_injected++;

            /* Keep this segment back, if this phase asks for it.  The packet belongs
               to this hook until it is handed on, so it can simply wait here. */
            if (urg_hold == NX_TRUE)
            {

                urg_hold = NX_FALSE;
                held_packet_ptr = packet_ptr;

                return;
            }
        }

        /* A segment was kept back: deliver this one first, so that the held one
           arrives behind it and fills the gap it left. */
        if (held_packet_ptr != NX_NULL)
        {

            release_packet_ptr = held_packet_ptr;
            held_packet_ptr = NX_NULL;
        }
    }

    /* Deliver the accepted prefix first.  Processing the original immediately
       afterwards exercises TCP's front-overlap trimming path. */
    if (prefix_packet_ptr != NX_NULL)
    {
        _nx_tcp_packet_receive(ip_ptr, prefix_packet_ptr);
    }

    /* Hand the segment to the real TCP receive processing. */
    _nx_tcp_packet_receive(ip_ptr, packet_ptr);

    if (release_packet_ptr != NX_NULL)
    {

        urg_reordered++;

        _nx_tcp_packet_receive(ip_ptr, release_packet_ptr);
    }
}

/* Find the NetX socket behind the accepted BSD socket, to look at the receive
   window the BSD layer maintains for it. */
static NX_TCP_SOCKET *server_socket_get(VOID)
{
NX_TCP_SOCKET   *socket_ptr;
ULONG            i;

    socket_ptr = ip_0.nx_ip_tcp_created_sockets_ptr;

    for (i = 0; (i < ip_0.nx_ip_tcp_created_sockets_count) && (socket_ptr != NX_NULL); i++)
    {

        if ((socket_ptr -> nx_tcp_socket_port == SERVER_PORT) &&
            (socket_ptr -> nx_tcp_socket_state == NX_TCP_ESTABLISHED))
        {
            return(socket_ptr);
        }

        socket_ptr = socket_ptr -> nx_tcp_socket_created_next;
    }

    return(NX_NULL);
}

/* Have the peer send one segment and wait until it has been delivered.  With
   hold set the segment is kept back by the hook until the next one arrives. */
static void urgent_segment_send(const CHAR *payload, ULONG length, ULONG pointer, UINT hold)
{
    client_payload = payload;
    client_payload_length = length;
    client_delay = 0;
    urg_pointer = pointer;
    urg_hold = hold;
    urg_overlap_prefix = 0;
    urg_arm = (UINT)((pointer != 0) || (hold == NX_TRUE) || (length != 0));

    tx_semaphore_put(&sema_1);
    tx_semaphore_get(&sema_0, 5 * NX_IP_PERIODIC_RATE);

    /* The peer returns from nx_tcp_socket_send() once the segment is acknowledged,
       so the receiving side has processed it by now. */
}

/* Send an urgent segment after first delivering a plain prefix with the same
   sequence number, forcing TCP to trim the front of the urgent segment. */
static void urgent_overlap_segment_send(const CHAR *payload, ULONG length, ULONG pointer,
                                        ULONG prefix_length)
{
    client_payload = payload;
    client_payload_length = length;
    client_delay = 0;
    urg_pointer = pointer;
    urg_hold = NX_FALSE;
    urg_overlap_prefix = prefix_length;
    urg_arm = NX_TRUE;

    tx_semaphore_put(&sema_1);
    tx_semaphore_get(&sema_0, 5 * NX_IP_PERIODIC_RATE);
}

/* Arm the urgent information and release the peer without waiting for it: the
   caller goes on to block in select(), and the peer waits a moment before it
   sends, so the segment arrives while the caller is suspended.  The caller has to
   collect the peer's semaphore afterwards. */
static void urgent_segment_arm(const CHAR *payload, ULONG length, ULONG pointer)
{
    client_payload = payload;
    client_payload_length = length;
    client_delay = NX_IP_PERIODIC_RATE / 10;
    urg_pointer = pointer;
    urg_hold = NX_FALSE;
    urg_overlap_prefix = 0;
    urg_arm = NX_TRUE;

    tx_semaphore_put(&sema_1);
}

/* Have the peer send one segment without any urgent information. */
static void plain_segment_send(const CHAR *payload, ULONG length)
{
    client_payload = payload;
    client_payload_length = length;
    client_delay = 0;
    urg_arm = NX_FALSE;
    urg_overlap_prefix = 0;

    tx_semaphore_put(&sema_1);
    tx_semaphore_get(&sema_0, 5 * NX_IP_PERIODIC_RATE);
}

static void ntest_0_entry(ULONG thread_input)
{
struct sockaddr_in  server_addr;
struct sockaddr_in  client_addr;
struct timeval      tv;
fd_set              readfds;
fd_set              exceptfds;
NX_TCP_SOCKET      *server_socket_ptr;
INT                 master_sock;
INT                 conn_sock;
INT                 reuse_sock;
INT                 probe[NX_BSD_MAX_SOCKETS];
INT                 probe_count = 0;
INT                 i;
INT                 client_addr_len;
INT                 n;
INT                 nfd;
CHAR                buf[512];
UINT                discarded_priority;
UINT                old_priority = 1;
UINT                status;
#ifndef NX_DISABLE_TCP_INFO
ULONG               packets_received;
ULONG               checksum_errors;
ULONG               packets_dropped;
#endif /* NX_DISABLE_TCP_INFO */

    NX_PARAMETER_NOT_USED(thread_input);

    /* Print out test information banner.  */
    printf("NetX Test:   BSD TCP OOB Test..............................");

    master_sock = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    if (master_sock < 0)
        record_error();

    memset(&server_addr, 0, sizeof(server_addr));
    server_addr.sin_family      = AF_INET;
    server_addr.sin_port        = htons(SERVER_PORT);
    server_addr.sin_addr.s_addr = INADDR_ANY;

    if (bind(master_sock, (struct sockaddr *)&server_addr, sizeof(server_addr)) < 0)
        record_error();

    if (listen(master_sock, 5) < 0)
        record_error();

    /* Let the peer connect. */
    tx_semaphore_put(&sema_1);
    tx_semaphore_get(&sema_0, 5 * NX_IP_PERIODIC_RATE);

    client_addr_len = sizeof(client_addr);
    conn_sock = accept(master_sock, (struct sockaddr *)&client_addr, &client_addr_len);
    if (conn_sock < 0)
        record_error();

    nfd = conn_sock + 1;

    /* ================================================================
     * Test 1: a blocked select() asking for readfds and exceptfds must
     *         report both for a segment that carries an urgent byte.  The
     *         urgent byte is the last one of "ABCDE", so the urgent pointer
     *         is 5 - it points one octet past the urgent data.
     * ================================================================ */
    test_phase = 1;

    /* Make the BSD caller higher priority than the receiving IP thread.  This
       deterministically exposes a wake-up that happens before the OOB mark is
       installed. */
    status = tx_thread_priority_change(&ip_0.nx_ip_thread, 4, &old_priority);

    if (status != TX_SUCCESS)
        record_error();

    urgent_segment_arm("ABCDE", 5, 5);

    FD_ZERO(&readfds);
    FD_ZERO(&exceptfds);
    FD_SET(conn_sock, &readfds);
    FD_SET(conn_sock, &exceptfds);
    tv.tv_sec  = 5;
    tv.tv_usec = 0;

    n = select(nfd, &readfds, NX_NULL, &exceptfds, &tv);

    if (n <= 0)
        record_error();
    if (!FD_ISSET(conn_sock, &readfds))
        record_error();
    if (!FD_ISSET(conn_sock, &exceptfds))
        record_error();

    status = tx_thread_priority_change(&ip_0.nx_ip_thread, old_priority, &discarded_priority);

    if (status != TX_SUCCESS)
        record_error();

    /* Collect the peer, and make sure the segment really was changed. */
    tx_semaphore_get(&sema_0, 5 * NX_IP_PERIODIC_RATE);

    if (urg_injected != 1)
        record_error();

    /* ================================================================
     * Test 2: the indication is level triggered, so it is reported again
     *         while the urgent byte is unread, recv(MSG_OOB) returns that
     *         byte, and the indication is gone afterwards.
     * ================================================================ */
    test_phase = 2;

    FD_ZERO(&exceptfds);
    FD_SET(conn_sock, &exceptfds);
    tv.tv_sec  = 0;
    tv.tv_usec = 0;

    n = select(nfd, NX_NULL, NX_NULL, &exceptfds, &tv);

    if (n <= 0)
        record_error();
    if (!FD_ISSET(conn_sock, &exceptfds))
        record_error();

    memset(buf, 0, sizeof(buf));

    n = recv(conn_sock, buf, sizeof(buf), MSG_OOB);

    if ((n != 1) || (buf[0] != 'E'))
        record_error();

    /* The out-of-band queue is empty again, so the next one fails. */
    n = recv(conn_sock, buf, sizeof(buf), MSG_OOB);

    if ((n != NX_SOC_ERROR) || (errno != EWOULDBLOCK))
        record_error();

    /* The exception is gone, while the in-band data keeps the socket readable. */
    FD_ZERO(&readfds);
    FD_ZERO(&exceptfds);
    FD_SET(conn_sock, &readfds);
    FD_SET(conn_sock, &exceptfds);
    tv.tv_sec  = 0;
    tv.tv_usec = 0;

    n = select(nfd, &readfds, NX_NULL, &exceptfds, &tv);

    if (n <= 0)
        record_error();
    if (!FD_ISSET(conn_sock, &readfds))
        record_error();
    if (FD_ISSET(conn_sock, &exceptfds))
        record_error();

    /* ================================================================
     * Test 3: the urgent byte is out of the in-band stream.
     * ================================================================ */
    test_phase = 3;

    memset(buf, 0, sizeof(buf));

    n = recv(conn_sock, buf, sizeof(buf), 0);

    if ((n != 4) || memcmp(buf, "ABCD", 4))
        record_error();

    /* ================================================================
     * Test 4: an urgent pointer of zero is not a byte offset and must be
     *         rejected without raising an exception.
     * ================================================================ */
    test_phase = 4;

    urgent_segment_send("AB", 2, 0, NX_FALSE);

    FD_ZERO(&readfds);
    FD_ZERO(&exceptfds);
    FD_SET(conn_sock, &readfds);
    FD_SET(conn_sock, &exceptfds);
    tv.tv_sec  = 0;
    tv.tv_usec = 0;

    n = select(nfd, &readfds, NX_NULL, &exceptfds, &tv);

    if (n <= 0)
        record_error();
    if (!FD_ISSET(conn_sock, &readfds))
        record_error();
    if (FD_ISSET(conn_sock, &exceptfds))
        record_error();

    n = recv(conn_sock, buf, sizeof(buf), MSG_OOB);

    if ((n != NX_SOC_ERROR) || (errno != EWOULDBLOCK))
        record_error();

    /* The payload is untouched. */
    memset(buf, 0, sizeof(buf));

    n = recv(conn_sock, buf, sizeof(buf), 0);

    if ((n != 2) || memcmp(buf, "AB", 2))
        record_error();

    /* ================================================================
     * Test 5: an urgent pointer past the end of the segment.  "CD" plus a
     *         pointer of 3 puts the urgent byte one octet behind the
     *         payload, so the indication is raised but no byte is queued.
     * ================================================================ */
    test_phase = 5;

    urgent_segment_send("CD", 2, 3, NX_FALSE);

    FD_ZERO(&exceptfds);
    FD_SET(conn_sock, &exceptfds);
    tv.tv_sec  = 0;
    tv.tv_usec = 0;

    n = select(nfd, NX_NULL, NX_NULL, &exceptfds, &tv);

    if (n <= 0)
        record_error();
    if (!FD_ISSET(conn_sock, &exceptfds))
        record_error();

    n = recv(conn_sock, buf, sizeof(buf), MSG_OOB);

    if ((n != NX_SOC_ERROR) || (errno != EWOULDBLOCK))
        record_error();

    /* That failed read has taken the indication down again, so such an urgent
       pointer is reported exactly once. */
    FD_ZERO(&exceptfds);
    FD_SET(conn_sock, &exceptfds);
    tv.tv_sec  = 0;
    tv.tv_usec = 0;

    n = select(nfd, NX_NULL, NX_NULL, &exceptfds, &tv);

    if (FD_ISSET(conn_sock, &exceptfds))
        record_error();

    /* The payload is untouched. */
    memset(buf, 0, sizeof(buf));

    n = recv(conn_sock, buf, sizeof(buf), 0);

    if ((n != 2) || memcmp(buf, "CD", 2))
        record_error();

    /* ================================================================
     * Test 6: two urgent bytes without a read in between.  The queue holds
     *         one byte by default, so the newer byte wins.
     * ================================================================ */
    test_phase = 6;

    /* Pointer 1 identifies the same absolute sequence announced one byte past
       the preceding segment in Test 5.  It must now be extracted, not rejected
       as an already consumed sequence. */
    urgent_segment_send("EFGH", 4, 1, NX_FALSE);   /* urgent byte 'E' */
    urgent_segment_send("IJKL", 4, 3, NX_FALSE);   /* urgent byte 'K' */

    memset(buf, 0, sizeof(buf));

    n = recv(conn_sock, buf, sizeof(buf), MSG_OOB);

    if ((n != 1) || (buf[0] != 'K'))
        record_error();

    /* Both urgent bytes are out of the in-band stream. */
    memset(buf, 0, sizeof(buf));

    n = recv(conn_sock, buf, sizeof(buf), 0);

    if ((n != 3) || memcmp(buf, "FGH", 3))
        record_error();

    memset(buf, 0, sizeof(buf));

    n = recv(conn_sock, buf, sizeof(buf), 0);

    if ((n != 3) || memcmp(buf, "IJL", 3))
        record_error();

    /* ================================================================
     * Test 7: MSG_OOB together with MSG_PEEK leaves the urgent byte and
     *         exception mark pending for a subsequent receive.
     * ================================================================ */
    test_phase = 7;

    urgent_segment_send("MNOP", 4, 1, NX_FALSE);   /* urgent byte 'M' */

    memset(buf, 0, sizeof(buf));

    n = recv(conn_sock, buf, sizeof(buf), MSG_OOB | MSG_PEEK);

    if ((n != 1) || (buf[0] != 'M'))
        record_error();

    FD_ZERO(&exceptfds);
    FD_SET(conn_sock, &exceptfds);
    tv.tv_sec  = 0;
    tv.tv_usec = 0;

    n = select(nfd, NX_NULL, NX_NULL, &exceptfds, &tv);

    if ((n <= 0) || !FD_ISSET(conn_sock, &exceptfds))
        record_error();

    /* A non-peeking read returns the same byte and consumes it. */
    n = recv(conn_sock, buf, sizeof(buf), MSG_OOB);

    if ((n != 1) || (buf[0] != 'M'))
        record_error();

    n = recv(conn_sock, buf, sizeof(buf), MSG_OOB);

    if ((n != NX_SOC_ERROR) || (errno != EWOULDBLOCK))
        record_error();

    memset(buf, 0, sizeof(buf));

    n = recv(conn_sock, buf, sizeof(buf), 0);

    if ((n != 3) || memcmp(buf, "NOP", 3))
        record_error();

    /* ================================================================
     * Test 8: an urgent byte can reside in a packet-chain extension.  The
     *         512-byte pool cannot hold this 500-byte payload and all TCP/IP
     *         headers in one packet, while the 1500-byte MTU keeps it in one
     *         TCP segment.
     * ================================================================ */
    test_phase = 8;

#ifndef NX_DISABLE_PACKET_CHAIN
    urgent_segment_send(chain_payload, sizeof(chain_payload), 490, NX_FALSE);

    if (urg_chained_segments != 1)
        record_error();

    memset(buf, 0, sizeof(buf));

    n = recv(conn_sock, buf, sizeof(buf), MSG_OOB);

    if ((n != 1) || (buf[0] != chain_payload[489]))
        record_error();

    memset(buf, 0, sizeof(buf));

    n = recv(conn_sock, buf, sizeof(buf), 0);

    if ((n != ((INT)sizeof(chain_payload) - 1)) ||
        memcmp(buf, chain_payload, 489) ||
        memcmp(&buf[489], &chain_payload[490], sizeof(chain_payload) - 490))
        record_error();
#endif /* NX_DISABLE_PACKET_CHAIN */

    /* ================================================================
     * Test 9: front-overlap trimming adjusts an urgent pointer that still
     *         refers to retained payload.  A plain "AB" prefix arrives
     *         before the full urgent "ABCD" segment, so pointer 4 becomes
     *         pointer 2 and still identifies 'D'.
     * ================================================================ */
    test_phase = 9;

    urgent_overlap_segment_send("ABCD", 4, 4, 2);

    memset(buf, 0, sizeof(buf));

    n = recv(conn_sock, buf, sizeof(buf), MSG_OOB);

    if ((n != 1) || (buf[0] != 'D'))
        record_error();

    n = recv(conn_sock, buf, sizeof(buf), 0);

    if ((n != 2) || memcmp(buf, "AB", 2))
        record_error();

    n = recv(conn_sock, buf, sizeof(buf), 0);

    if ((n != 1) || (buf[0] != 'C'))
        record_error();

    /* ================================================================
     * Test 10: if overlap trimming discards the urgent byte, the pointer
     *          is cleared rather than left pointing at retained payload.
     * ================================================================ */
    test_phase = 10;

    urgent_overlap_segment_send("WXYZ", 4, 2, 2);

    FD_ZERO(&exceptfds);
    FD_SET(conn_sock, &exceptfds);
    tv.tv_sec  = 0;
    tv.tv_usec = 0;

    n = select(nfd, NX_NULL, NX_NULL, &exceptfds, &tv);

    if ((n != 0) || FD_ISSET(conn_sock, &exceptfds))
        record_error();

    n = recv(conn_sock, buf, sizeof(buf), MSG_OOB);

    if ((n != NX_SOC_ERROR) || (errno != EWOULDBLOCK))
        record_error();

    n = recv(conn_sock, buf, sizeof(buf), 0);

    if ((n != 2) || memcmp(buf, "WX", 2))
        record_error();

    n = recv(conn_sock, buf, sizeof(buf), 0);

    if ((n != 2) || memcmp(buf, "YZ", 2))
        record_error();

    /* ================================================================
     * Test 11: an urgent byte in an out-of-order segment.  "QRST" stays in
     *         the receive queue with its urgent byte already taken, then
     *         "UVWX" is kept back and "YZ12" is delivered ahead of it, so
     *         "UVWX" is inserted in front of the queue tail.  The urgent
     *         byte can only be found by walking the queue, and the walk has
     *         to skip "QRST" instead of taking a second byte out of it.
     * ================================================================ */
    test_phase = 11;

    urgent_segment_send("QRST", 4, 2, NX_FALSE);   /* urgent byte 'R' */

    memset(buf, 0, sizeof(buf));

    n = recv(conn_sock, buf, sizeof(buf), MSG_OOB);

    if ((n != 1) || (buf[0] != 'R'))
        record_error();

#ifndef NX_DISABLE_TCP_INFO
    packets_received = ip_0.nx_ip_tcp_packets_received;
    checksum_errors  = ip_0.nx_ip_tcp_checksum_errors;
    packets_dropped  = ip_0.nx_ip_tcp_receive_packets_dropped;
#endif /* NX_DISABLE_TCP_INFO */

    /* "QRST" is still queued, so the walk will pass it. */
    urgent_segment_send("UVWX", 4, 2, NX_TRUE);    /* urgent byte 'V', kept back */
    plain_segment_send("YZ12", 4);                 /* arrives first, no URG bit */

    if (urg_reordered != 1)
        record_error();

#ifndef NX_DISABLE_TCP_INFO
    /* Both segments have to be accepted by the socket, otherwise this phase would
       pass without the queue ever being walked. */
    if ((ip_0.nx_ip_tcp_packets_received - packets_received) < 2)
        record_error();

    if (ip_0.nx_ip_tcp_checksum_errors != checksum_errors)
        record_error();

    if (ip_0.nx_ip_tcp_receive_packets_dropped != packets_dropped)
        record_error();
#endif /* NX_DISABLE_TCP_INFO */

    /* The urgent byte of the out-of-order segment.  The queue tail is the plain
       segment, so nothing but the walk could have found this. */
    memset(buf, 0, sizeof(buf));

    n = recv(conn_sock, buf, sizeof(buf), MSG_OOB);

    if ((n != 1) || (buf[0] != 'V'))
        record_error();

    /* "QRST" kept its three remaining bytes: the walk skipped it instead of
       taking another byte out of it. */
    memset(buf, 0, sizeof(buf));

    n = recv(conn_sock, buf, sizeof(buf), 0);

    if ((n != 3) || memcmp(buf, "QST", 3))
        record_error();

    memset(buf, 0, sizeof(buf));

    n = recv(conn_sock, buf, sizeof(buf), 0);

    if ((n != 3) || memcmp(buf, "UWX", 3))
        record_error();

    memset(buf, 0, sizeof(buf));

    n = recv(conn_sock, buf, sizeof(buf), 0);

    if ((n != 4) || memcmp(buf, "YZ12", 4))
        record_error();

    /* ================================================================
     * Test 12: the receive window is back where it started.  Every urgent
     *          byte cut out of the stream over this connection had to be
     *          handed back to the window.
     * ================================================================ */
    test_phase = 12;

    server_socket_ptr = server_socket_get();

    if (server_socket_ptr == NX_NULL)
        record_error();
    else if (server_socket_ptr -> nx_tcp_socket_rx_window_current !=
             server_socket_ptr -> nx_tcp_socket_rx_window_default)
        record_error();

    /* Nothing may be left in the in-band stream either. */
    FD_ZERO(&readfds);
    FD_SET(conn_sock, &readfds);
    tv.tv_sec  = 0;
    tv.tv_usec = 0;

    n = select(nfd, &readfds, NX_NULL, NX_NULL, &tv);

    if (FD_ISSET(conn_sock, &readfds))
        record_error();

    /* ================================================================
     * Test 13: an urgent byte the application never took must not survive
     *          the socket.  Take one more, leave it, and close.
     * ================================================================ */
    test_phase = 13;

    urgent_segment_arm("XY", 2, 2);

    FD_ZERO(&readfds);
    FD_ZERO(&exceptfds);
    FD_SET(conn_sock, &readfds);
    FD_SET(conn_sock, &exceptfds);
    tv.tv_sec  = 5;
    tv.tv_usec = 0;

    n = select(nfd, &readfds, NX_NULL, &exceptfds, &tv);

    if (n <= 0)
        record_error();
    if (!FD_ISSET(conn_sock, &exceptfds))
        record_error();

    tx_semaphore_get(&sema_0, 5 * NX_IP_PERIODIC_RATE);

    /* Every phase must really have been changed on the way in. */
#ifndef NX_DISABLE_PACKET_CHAIN
    if (urg_injected != 12)
#else
    if (urg_injected != 11)
#endif /* NX_DISABLE_PACKET_CHAIN */
        record_error();

    /* Close without reading the urgent byte. */
    if (soc_close(conn_sock) < 0)
        record_error();

    /* Get hold of the released slot again.  The socket table is handed out in a
       rotating manner, so keep allocating until that descriptor comes back. */
    reuse_sock = NX_SOC_ERROR;

    while (probe_count < NX_BSD_MAX_SOCKETS)
    {

        n = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);

        if (n < 0)
            break;

        probe[probe_count++] = n;

        if (n == conn_sock)
        {
            reuse_sock = n;
            break;
        }
    }

    if (reuse_sock < 0)
        record_error();
    else
    {

        FD_ZERO(&exceptfds);
        FD_SET(reuse_sock, &exceptfds);

        tv.tv_sec  = 0;
        tv.tv_usec = 0;

        n = select(reuse_sock + 1, NX_NULL, NX_NULL, &exceptfds, &tv);

        if (FD_ISSET(reuse_sock, &exceptfds))
            record_error();

        n = recv(reuse_sock, buf, sizeof(buf), MSG_OOB);

        if ((n != NX_SOC_ERROR) || (errno != EWOULDBLOCK))
            record_error();
    }

    for (i = 0; i < probe_count; i++)
        soc_close(probe[i]);

    soc_close(master_sock);

    /* Let the peer tear down its socket. */
    client_payload_length = 0;
    tx_semaphore_put(&sema_1);
    tx_semaphore_get(&sema_0, 5 * NX_IP_PERIODIC_RATE);

    if (error_counter)
    {
        printf("ERROR! (phase %d)\n", error_phase);
        test_control_return(1);
    }
    else
    {
        printf("SUCCESS!\n");
        test_control_return(0);
    }
}

/* Peer thread: a plain NetX TCP socket, so the payload of every segment is
   known and the BSD socket table stays untouched. */
static void ntest_1_entry(ULONG thread_input)
{
NX_PACKET  *packet_ptr;
ULONG       actual_status;
UINT        status;

    NX_PARAMETER_NOT_USED(thread_input);

    nx_ip_status_check(&ip_1, NX_IP_INITIALIZE_DONE, &actual_status,
                       5 * NX_IP_PERIODIC_RATE);

    /* Wait for the server socket to listen. */
    tx_semaphore_get(&sema_1, 5 * NX_IP_PERIODIC_RATE);

    status = nx_tcp_socket_create(&ip_1, &client_socket, "Client Socket",
                                  NX_IP_NORMAL, NX_FRAGMENT_OKAY,
                                  NX_IP_TIME_TO_LIVE, 512, NX_NULL, NX_NULL);
    if (status)
        record_error();

    status = nx_tcp_client_socket_bind(&client_socket, NX_ANY_PORT,
                                       5 * NX_IP_PERIODIC_RATE);
    if (status)
        record_error();

    status = nx_tcp_client_socket_connect(&client_socket, SERVER_ADDRESS, SERVER_PORT,
                                          5 * NX_IP_PERIODIC_RATE);
    if (status)
        record_error();

    tx_semaphore_put(&sema_0);

    /* Send whatever the server thread asks for, until it asks for nothing. */
    while (1)
    {

        tx_semaphore_get(&sema_1, 5 * NX_IP_PERIODIC_RATE);

        if (client_payload_length == 0)
            break;

        if (client_delay != 0)
            tx_thread_sleep(client_delay);

        status = nx_packet_allocate(&pool_0, &packet_ptr, NX_TCP_PACKET,
                                    5 * NX_IP_PERIODIC_RATE);
        if (status)
            record_error();
        else
        {

            status = nx_packet_data_append(packet_ptr, (VOID *)client_payload,
                                           client_payload_length, &pool_0,
                                           5 * NX_IP_PERIODIC_RATE);
            if (status)
            {
                nx_packet_release(packet_ptr);
                record_error();
            }
            else
            {

                status = nx_tcp_socket_send(&client_socket, packet_ptr,
                                            5 * NX_IP_PERIODIC_RATE);
                if (status)
                {
                    nx_packet_release(packet_ptr);
                    record_error();
                }
            }
        }

        tx_semaphore_put(&sema_0);
    }

    nx_tcp_socket_disconnect(&client_socket, NX_IP_PERIODIC_RATE);
    nx_tcp_client_socket_unbind(&client_socket);
    nx_tcp_socket_delete(&client_socket);

    tx_semaphore_put(&sema_0);
}

#else

extern void test_control_return(UINT status);

#ifdef CTEST
VOID test_application_define(void *first_unused_memory)
#else
void netx_bsd_tcp_oob_test_application_define(void *first_unused_memory)
#endif
{
    NX_PARAMETER_NOT_USED(first_unused_memory);

    /* Print out test information banner.  */
    printf("NetX Test:   BSD TCP OOB Test..............................N/A\n");

    test_control_return(3);
}

#endif /* NX_BSD_ENABLE && !NX_DISABLE_IPV4 */
