#!/bin/bash
##############################################################################
# Copyright (c) 2026 Eclipse ThreadX contributors
#
# This program and the accompanying materials are made available under the
# terms of the MIT License which is available at
# https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: MIT
##############################################################################
# Some portions generated by Codex (gpt-5.6-sol).

set -euo pipefail

readonly script_directory="$(dirname "$(realpath "$0")")"
readonly supervisor="${script_directory}/../run_interoperability_wsl.sh"
readonly test_root="$(mktemp -d)"
readonly repository_root="${test_root}/repository"
readonly pid_file="$(mktemp)"

cleanup()
{
    rm -f -- "${pid_file}"
    rm -rf -- "${test_root}"
}
trap cleanup EXIT INT TERM

bash -n "${supervisor}"
mkdir -p "${repository_root}/scripts" \
    "${repository_root}/test/cmake/mqtt_interoperability" \
    "${repository_root}/test/cmake/nx_secure_interoperability"
printf '#!/bin/bash\n' > "${repository_root}/scripts/run_cmake_suite.sh"
chmod +x "${repository_root}/scripts/run_cmake_suite.sh"
ln -s ../mqtt/CMakeLists.txt \
    "${repository_root}/test/cmake/mqtt_interoperability/CMakeLists.txt"
for suite in mqtt_interoperability nx_secure_interoperability; do
    ln -s ../libs "${repository_root}/test/cmake/${suite}/libs"
    ln -s ../coverage.sh "${repository_root}/test/cmake/${suite}/coverage.sh"
done
"${supervisor}" --check "${repository_root}" \
    mqtt_interoperability nx_secure_interoperability

setsid sleep 60 &
process_group_id="$!"
printf '%s\n' "${process_group_id}" > "${pid_file}"
"${supervisor}" --cleanup "${pid_file}"

if kill -0 "${process_group_id}" 2>/dev/null; then
    echo 'Supervisor cleanup left the test process running.' >&2
    exit 1
fi

if [ -e "${pid_file}" ]; then
    echo 'Supervisor cleanup left its PID file behind.' >&2
    exit 1
fi

echo 'WSL interoperability supervisor tests passed.'
