/***************************************************************************/
/* Copyright (c) 2024 Microsoft Corporation                                */
/* Copyright (c) 2026 Eclipse ThreadX contributors                         */
/*                                                                         */
/* This program and the accompanying materials are made available under    */
/* the terms of the MIT License which is available at                      */
/* https://opensource.org/licenses/MIT.                                    */
/*                                                                         */
/* SPDX-License-Identifier: MIT                                            */
/***************************************************************************/

// Some portions generated by Codex (gpt-5.6-sol).

#include "tls_test_frame.h"

extern TLS_TEST_SEMAPHORE* semaphore_echo_server_prepared;

/* Openssl echo server entry. */
INT openssl_echo_server_entry(TLS_TEST_INSTANCE* instance_ptr)
{

#if !defined(NX_SECURE_TLS_CLIENT_DISABLED) && (NX_SECURE_TLS_TLS_1_3_ENABLED)

INT status, exit_status;

/* Added -naccept 1 to close the server after one tls session. */
/* Added -named_curve to use specific curve(secp384r1). Client is using secp256r1, so server will send HelloRetryRequest for the mismatch of "key_share". */
/* Added -stateless to include "cookie" in the HelloRetryRequest. */
CHAR* external_cmd[] = { "openssl_echo_server.sh",
                         "../../ecc_certificates/ECTestServer2.key", 
                         "../../ecc_certificates/ECTestServer2.crt", 
                         "-port", DEVICE_SERVER_PORT_STRING,
                         "-naccept", "2", 
                         "-tls1_3", 
                         "-named_curve", "secp384r1", 
                         "-stateless", (CHAR*)NULL};

    /* Launch the OpenSSL server and notify the client when it is ready. */
    status = tls_test_launch_external_test_server(&exit_status, external_cmd, semaphore_echo_server_prepared,
                                                   DEVICE_SERVER_PORT_STRING, TLS_TEST_EXTERNAL_SERVER_TCP);
    return_value_if_fail(TLS_TEST_SUCCESS == status, status);

#if 0 /* openssl exit with 0 no matter TLS session is established or not. */
    /* Check for the exit status of external program. */
    return_value_if_fail(0 == exit_status, TLS_TEST_INSTANCE_EXTERNAL_PROGRAM_FAILED);
#endif
    return TLS_TEST_SUCCESS;

#else

    return TLS_TEST_NOT_AVAILABLE;

#endif

}
