/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* This case covers control and data frames that carry no payload at all.

   An empty frame is two bytes on the wire, so trimming its header consumes the
   whole packet and _nx_websocket_client_packet_trim() reports NX_NO_PACKET with
   the packet pointer set to NX_NULL.  Every arm of the frame switch in
   _nx_websocket_client_data_process() has to cope with that:

     - an empty PING must be answered with an empty PONG and consumed;
     - an empty PONG must be consumed and not surfaced to the application;
     - an empty CLOSE must reach the status callback and return
       NX_WEBSOCKET_DISCONNECTED;
     - an empty data frame must be consumed without being handed over, since
       there is no packet to hand over.

   Each frame is sent in its own TCP segment so that it arrives alone and the
   NX_NULL case is actually exercised.  The test also checks the client mutex is
   released on every path and that the packet pool is intact at the end.  */

#include    "tx_api.h"
#include    "nx_api.h"

extern void test_control_return(UINT);

#if !defined(NX_DISABLE_IPV4) && defined(__PRODUCT_NETXDUO__) && !defined(NX_DISABLE_PACKET_CHAIN)
#include    "nx_websocket_client.h"
#include    "netx_websocket_common_process.c"

#define     DEMO_STACK_SIZE         4096
#define     PACKET_SIZE             1536
#define     TOTAL_SIZE              DEMO_STACK_SIZE + (PACKET_SIZE * 8) + 2048 + 1024

#define TEST_HOST_NAME       "1.2.3.4"
#define TEST_URI_PATH        "/test"
#define TEST_PROTOCOL        "test"
#define TEST_BEARER          ""

/* Define device drivers.  */
extern void _nx_ram_network_driver_1024(NX_IP_DRIVER *driver_req_ptr);

static UINT                test_done = NX_FALSE;

static TX_THREAD           client_thread;
static NX_PACKET_POOL      client_pool;
static NX_TCP_SOCKET       test_client;
static NX_IP               client_ip;

static NX_TCP_SOCKET       test_server;
static NX_PACKET_POOL      server_pool;
static TX_THREAD           server_thread;
static NX_IP               server_ip;
static UINT                test_server_start = 0;
static UINT                test_client_stop = 0;

/* Set up the websocket global variables */
static NX_WEBSOCKET_CLIENT client_websocket;
static UCHAR               *client_websocket_host;
static UINT                client_websocket_host_length;
static UCHAR               *client_websocket_uri_path;
static UINT                client_websocket_uri_path_length;


static void thread_client_entry(ULONG thread_input);
static void thread_server_entry(ULONG thread_input);

#define TEST_SERVER_ADDRESS  IP_ADDRESS(1,2,3,4)
#define TEST_CLIENT_ADDRESS  IP_ADDRESS(1,2,3,5)
#define TEST_SERVER_PORT     80
#define TEST_BEARER          ""

static UCHAR server_switch_101[] =
{
0x48, 0x54, 0x54, 0x50, 0x2f, 0x31, 0x2e, 0x31, 0x20,                                      // HTTP1.1/
0x31, 0x30, 0x31, 0x20, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x20,        // 101 Switching
0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x0d, 0x0a,                          // Protocols\r\n
0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x3a, 0x20,                                      // Upgrade:
0x57, 0x65, 0x62, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x0d, 0x0a,                          // WebSocket\r\n
0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x3a, 0x20,                    // Connection:
0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x0d, 0x0a,                                      // Upgrade\r\n
0x53, 0x65, 0x63, 0x2d, 0x57, 0x65, 0x62, 0x53, 0x6f, 0x63, 0x6b, 0x65,                    // Sec-WebSocket-Protocol:
0x74, 0x2d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x3a, 0x20,
0x74, 0x65, 0x73, 0x74, 0x0d, 0x0a,                                                        // test
0x53, 0x65, 0x63, 0x2d, 0x57, 0x65, 0x62, 0x53, 0x6f, 0x63, 0x6b,                          // Sec-WebSocket-Accept:
0x65, 0x74, 0x2d, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x3a, 0x20,
0x35, 0x75, 0x31, 0x6c, 0x55, 0x72, 0x32, 0x57, 0x68, 0x70, 0x34, 0x64, 0x44, 0x57, 0x6e,  // 5u1lUr2Whp4dDWnskk9JcJZobO0=
0x73, 0x6b, 0x6b, 0x39, 0x4a, 0x63, 0x4a, 0x5a, 0x6f, 0x62, 0x4f, 0x30, 0x3d, 0x0d, 0x0a,
0x0d, 0x0a,
};

static UCHAR server_empty_ping[]  = { 0x89, 0x00 };  /* FIN, PING,  no payload */
static UCHAR server_empty_pong[]  = { 0x8A, 0x00 };  /* FIN, PONG,  no payload */
static UCHAR server_empty_text[]  = { 0x81, 0x00 };  /* FIN, TEXT,  no payload */
static UCHAR server_empty_close[] = { 0x88, 0x00 };  /* FIN, CLOSE, no payload */

static ULONG                   error_counter;
static UINT                    disconnect_callback_called = NX_FALSE;
static UINT                    pong_seen = NX_FALSE;
static UINT                    close_reported = NX_FALSE;

extern void SET_ERROR_COUNTER(ULONG *error_counter, CHAR *filename, int line_number);

/* Records that the stack reported the peer's CLOSE to the application.  */
static void connection_status_callback(NX_WEBSOCKET_CLIENT *websocket_client_ptr, VOID *context, UINT status)
{
    NX_PARAMETER_NOT_USED(websocket_client_ptr);
    NX_PARAMETER_NOT_USED(context);

    if (status == NX_WEBSOCKET_DISCONNECTED)
    {
        disconnect_callback_called = NX_TRUE;
    }
}


#ifdef CTEST
VOID test_application_define(void *first_unused_memory)
#else
void    netx_websocket_empty_control_frame_test_application_define(void *first_unused_memory)
#endif
{
CHAR    *pointer;
UINT    status;


    error_counter = 0;

    /* Setup the working pointer.  */
    pointer =  (CHAR *) first_unused_memory;

    /* Create a helper thread for the server. */
    tx_thread_create(&server_thread, "Test Server thread", thread_server_entry, 0,
                     pointer, DEMO_STACK_SIZE,
                     4, 4, TX_NO_TIME_SLICE, TX_AUTO_START);

    pointer =  pointer + DEMO_STACK_SIZE;

    /* Initialize the NetX system.  */
    nx_system_initialize();

    /* Create the server packet pool.  */
    status =  nx_packet_pool_create(&server_pool, "Test Server Packet Pool", PACKET_SIZE,
                                    pointer, PACKET_SIZE * 8);
    pointer = pointer + PACKET_SIZE * 8;
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    /* Create an IP instance.  */
    status = nx_ip_create(&server_ip, "Test Server IP", TEST_SERVER_ADDRESS,
                          0xFFFFFF00UL, &server_pool, _nx_ram_network_driver_1024,
                          pointer, 2048, 1);
    pointer =  pointer + 2048;
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    /* Enable ARP and supply ARP cache memory for the server IP instance.  */
    status = nx_arp_enable(&server_ip, (void *) pointer, 1024);
    pointer = pointer + 1024;
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);


     /* Enable TCP traffic.  */
    status = nx_tcp_enable(&server_ip);
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    /* Create the Test Client thread. */
    status = tx_thread_create(&client_thread, "Test Client", thread_client_entry, 0,
                              pointer, DEMO_STACK_SIZE,
                              6, 6, TX_NO_TIME_SLICE, TX_AUTO_START);
    pointer =  pointer + DEMO_STACK_SIZE;
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    /* Create the Client packet pool.  */
    status =  nx_packet_pool_create(&client_pool, "Test Client Packet Pool", PACKET_SIZE,
                                    pointer, PACKET_SIZE * 8);
    pointer = pointer + PACKET_SIZE * 8;
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    /* Create an IP instance.  */
    status = nx_ip_create(&client_ip, "Test Client IP", TEST_CLIENT_ADDRESS,
                          0xFFFFFF00UL, &client_pool, _nx_ram_network_driver_1024,
                          pointer, 2048, 1);
    pointer =  pointer + 2048;
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    status  = nx_arp_enable(&client_ip, (void *) pointer, 1024);
    pointer =  pointer + 1024;
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

     /* Enable TCP traffic.  */
    status = nx_tcp_enable(&client_ip);
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);
}


void thread_client_entry(ULONG thread_input)
{
UINT            i, status;
NX_PACKET      *packet_ptr;
NXD_ADDRESS     server_ip_address;
UINT            code;

    NX_PARAMETER_NOT_USED(thread_input);

    /* Create client socket.  */
    status = nx_tcp_socket_create(&client_ip, &test_client, "Client Socket", NX_IP_NORMAL, NX_FRAGMENT_OKAY,
                                  NX_IP_TIME_TO_LIVE, 1000, NX_NULL, NX_NULL);
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    /* Create WebSocket.  */
    status = nx_websocket_client_create(&client_websocket, (UCHAR *)" ", &client_ip, &client_pool);
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    /* Register the connection status callback so the CLOSE notification can be observed.  */
    status = nx_websocket_client_connection_status_callback_set(&client_websocket, NX_NULL, connection_status_callback);
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    /* Give IP task and driver a chance to initialize the system.  */
    tx_thread_sleep(NX_IP_PERIODIC_RATE);

    status = nx_tcp_client_socket_bind(&test_client, TEST_SERVER_PORT, NX_IP_PERIODIC_RATE);
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    while (!test_server_start)
    {
        tx_thread_sleep(NX_IP_PERIODIC_RATE);
    }

    server_ip_address.nxd_ip_address.v4 = TEST_SERVER_ADDRESS;
    server_ip_address.nxd_ip_version = NX_IP_VERSION_V4;

    status = nxd_tcp_client_socket_connect(&test_client, &server_ip_address, TEST_SERVER_PORT, NX_WAIT_FOREVER);
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    /* Upgrade to websocket */
    status = nx_websocket_client_connect(&client_websocket, &test_client,
                                         TEST_HOST_NAME, sizeof(TEST_HOST_NAME) - 1,
                                         (UCHAR *)TEST_URI_PATH, sizeof(TEST_URI_PATH) - 1,
                                         (UCHAR *)TEST_PROTOCOL, sizeof(TEST_PROTOCOL) - 1,
                                         (UCHAR *)TEST_BEARER, sizeof(TEST_BEARER) - 1,
                                         NX_WAIT_FOREVER);
    if (status)
    {
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);
        test_client_stop = 1;
        return;
    }

    /* Drain the connection.  A single receive call may consume several frames, so the
       frames are not matched one-to-one with calls: what matters is that no empty frame is
       ever handed to the application as data, that the mutex is released on every path, and
       that the peer's CLOSE is eventually reported.  */
    for (i = 0; i < 12; i++)
    {
        status = nx_websocket_client_receive(&client_websocket, &packet_ptr, &code, 2 * NX_IP_PERIODIC_RATE);

        /* Whatever happened, the mutex must not be left held.  */
        if (client_websocket.nx_websocket_client_mutex.tx_mutex_ownership_count != 0)
            SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

        if (status == NX_WEBSOCKET_DISCONNECTED)
        {

            /* The empty CLOSE was reported.  */
            close_reported = NX_TRUE;
            break;
        }
        else if (status == NX_SUCCESS)
        {

            /* None of the frames in this test carries a payload, so nothing should ever be
               handed over as application data.  */
            SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);
            nx_packet_release(packet_ptr);
        }
        else if (status != NX_NO_PACKET)
        {

            /* NX_NO_PACKET simply means nothing was ready yet; anything else is a failure.  */
            SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);
        }
    }

    if (close_reported != NX_TRUE)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    if (disconnect_callback_called != NX_TRUE)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    /* No packet may have been released twice or leaked along the way.  */
    if (client_pool.nx_packet_pool_invalid_releases)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    test_client_stop = 1;
}


/* Sends one frame in its own TCP segment.  */
static void send_frame(UCHAR *frame, ULONG frame_size)
{
UINT        status;
NX_PACKET  *packet_ptr;

    status = nx_packet_allocate(&server_pool, &packet_ptr, NX_TCP_PACKET, NX_IP_PERIODIC_RATE);
    if (status)
    {
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);
        return;
    }

    status = nx_packet_data_append(packet_ptr, frame, frame_size, &server_pool, NX_IP_PERIODIC_RATE);
    if (status)
    {
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);
        nx_packet_release(packet_ptr);
        return;
    }

    status = nx_tcp_socket_send(&test_server, packet_ptr, NX_IP_PERIODIC_RATE);
    if (status)
    {
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);
        nx_packet_release(packet_ptr);
    }
}

void    thread_server_entry(ULONG thread_input)
{
UINT            status;
NX_PACKET      *packet_ptr;
UCHAR           opcode;

    NX_PARAMETER_NOT_USED(thread_input);

    printf("NetX Test:   Websocket Empty Control Frame Test........................");

    if (error_counter)
    {
        printf("ERROR!\n");
        test_control_return(1);
    }

    tx_thread_sleep(NX_IP_PERIODIC_RATE);

    status = nx_tcp_socket_create(&server_ip, &test_server, "Test Server Socket",
                                  NX_IP_NORMAL, NX_FRAGMENT_OKAY, NX_IP_TIME_TO_LIVE, 1000,
                                  NX_NULL, NX_NULL);
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    status = nx_tcp_server_socket_listen(&server_ip, TEST_SERVER_PORT, &test_server, 5, NX_NULL);
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    test_server_start = 1;

    status = nx_tcp_server_socket_accept(&test_server, 5 * NX_IP_PERIODIC_RATE);
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    /* Complete the WebSocket handshake.  */
    status = nx_tcp_socket_receive(&test_server, &packet_ptr, 5 * NX_IP_PERIODIC_RATE);
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);
    else
    {
        _server_connect_response_process(packet_ptr);
        memcpy(&server_switch_101[127], connect_key, 28); /* Use case of memcpy is verified. */

        packet_ptr -> nx_packet_append_ptr = packet_ptr -> nx_packet_prepend_ptr;
        packet_ptr -> nx_packet_length = 0;
        nx_packet_data_append(packet_ptr, server_switch_101, sizeof(server_switch_101), &server_pool, NX_IP_PERIODIC_RATE);
        status = nx_tcp_socket_send(&test_server, packet_ptr, NX_IP_PERIODIC_RATE);
        if (status)
        {
            SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);
            nx_packet_release(packet_ptr);
        }
    }

    /* 1. An empty PING.  The client must answer with an empty PONG.  */
    send_frame(server_empty_ping, sizeof(server_empty_ping));

    status = nx_tcp_socket_receive(&test_server, &packet_ptr, 5 * NX_IP_PERIODIC_RATE);
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);
    else
    {

        /* A client frame is masked, so only the low nibble of the first byte is the opcode.  */
        opcode = (UCHAR)(*(packet_ptr -> nx_packet_prepend_ptr) & 0x0F);
        if (opcode == NX_WEBSOCKET_OPCODE_PONG)
        {
            pong_seen = NX_TRUE;
        }
        else
        {
            SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);
        }

        /* The echoed payload must be empty, so the frame is header plus mask only.  */
        if (packet_ptr -> nx_packet_length != 6)
            SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

        nx_packet_release(packet_ptr);
    }

    /* 2, 3 and 4: an empty PONG, an empty data frame and an empty CLOSE, each alone.  */
    tx_thread_sleep(NX_IP_PERIODIC_RATE);
    send_frame(server_empty_pong, sizeof(server_empty_pong));

    tx_thread_sleep(NX_IP_PERIODIC_RATE);
    send_frame(server_empty_text, sizeof(server_empty_text));

    tx_thread_sleep(NX_IP_PERIODIC_RATE);
    send_frame(server_empty_close, sizeof(server_empty_close));

    /* Wait for the client to finish its checks.  */
    while (!test_client_stop)
    {
        tx_thread_sleep(NX_IP_PERIODIC_RATE);
    }

    if (pong_seen != NX_TRUE)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    if (error_counter)
    {
        printf("ERROR!\n");
        test_control_return(1);
    }
    else
    {
        printf("SUCCESS!\n");
        test_control_return(0);
    }
}

#else

#ifdef CTEST
VOID test_application_define(void *first_unused_memory)
#else
void    netx_websocket_empty_control_frame_test_application_define(void *first_unused_memory)
#endif
{

    /* Print out test information banner.  */
    printf("NetX Test:   Websocket Empty Control Frame Test........................N/A\n");

    test_control_return(3);
}
#endif

