/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* This case covers the frame boundaries RFC 6455 puts on control frames and on
   the payload length encoding.

     - A control frame may not be fragmented (Section 5.5), so a PING with the
       FIN bit clear must be rejected rather than parsed as the termination of
       a fragmented message.
     - A control frame payload may not exceed 125 bytes (Section 5.5), so a PING
       declaring 126 through the 16-bit extended length must be rejected.
     - A payload of exactly 125 bytes is the largest that the 7-bit length field
       can carry, so an outgoing frame of that size must use the two-byte header
       (Section 5.2).  126 is the first length that needs the extended form.

   The two rejected frames are sent on a live session and the session is then
   used again, because the parser is expected to recover: rejecting a malformed
   control frame drops the parse state, it does not close the connection.  */

#include    "tx_api.h"
#include    "nx_api.h"

extern void test_control_return(UINT);

#if !defined(NX_DISABLE_IPV4) && defined(__PRODUCT_NETXDUO__) && !defined(NX_DISABLE_PACKET_CHAIN)
#include    "nx_websocket_client.h"
#include    "netx_websocket_common_process.c"

#define     DEMO_STACK_SIZE         4096
#define     PACKET_SIZE             1536
#define     TOTAL_SIZE              DEMO_STACK_SIZE + (PACKET_SIZE * 8) + 2048 + 1024

#define TEST_HOST_NAME       "1.2.3.4"
#define TEST_URI_PATH        "/test"
#define TEST_PROTOCOL        "test"
#define TEST_BEARER          ""

/* The largest payload the 7-bit length field can carry, and the frame that
   carries it: two header bytes, a four byte masking key, then the payload.  */
#define BOUNDARY_PAYLOAD_SIZE   125
#define BOUNDARY_FRAME_SIZE     (2 + 4 + BOUNDARY_PAYLOAD_SIZE)

/* Define device drivers.  */
extern void _nx_ram_network_driver_1024(NX_IP_DRIVER *driver_req_ptr);

static TX_THREAD           client_thread;
static NX_PACKET_POOL      client_pool;
static NX_TCP_SOCKET       test_client;
static NX_IP               client_ip;

static NX_TCP_SOCKET       test_server;
static NX_PACKET_POOL      server_pool;
static TX_THREAD           server_thread;
static NX_IP               server_ip;
static UINT                test_server_start = 0;
static UINT                test_client_stop = 0;

/* Set up the websocket global variables */
static NX_WEBSOCKET_CLIENT client_websocket;
static UCHAR               *client_websocket_host;
static UINT                client_websocket_host_length;
static UCHAR               *client_websocket_uri_path;
static UINT                client_websocket_uri_path_length;


static void thread_client_entry(ULONG thread_input);
static void thread_server_entry(ULONG thread_input);
static void client_send_boundary_frame(void);

#define TEST_SERVER_ADDRESS  IP_ADDRESS(1,2,3,4)
#define TEST_CLIENT_ADDRESS  IP_ADDRESS(1,2,3,5)
#define TEST_SERVER_PORT     80

static UCHAR server_switch_101[] =
{
0x48, 0x54, 0x54, 0x50, 0x2f, 0x31, 0x2e, 0x31, 0x20,                                      // HTTP1.1/
0x31, 0x30, 0x31, 0x20, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x20,        // 101 Switching
0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x0d, 0x0a,                          // Protocols\r\n
0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x3a, 0x20,                                      // Upgrade:
0x57, 0x65, 0x62, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x0d, 0x0a,                          // WebSocket\r\n
0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x3a, 0x20,                    // Connection:
0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x0d, 0x0a,                                      // Upgrade\r\n
0x53, 0x65, 0x63, 0x2d, 0x57, 0x65, 0x62, 0x53, 0x6f, 0x63, 0x6b, 0x65,                    // Sec-WebSocket-Protocol:
0x74, 0x2d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x3a, 0x20,
0x74, 0x65, 0x73, 0x74, 0x0d, 0x0a,                                                        // test
0x53, 0x65, 0x63, 0x2d, 0x57, 0x65, 0x62, 0x53, 0x6f, 0x63, 0x6b,                          // Sec-WebSocket-Accept:
0x65, 0x74, 0x2d, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x3a, 0x20,
0x35, 0x75, 0x31, 0x6c, 0x55, 0x72, 0x32, 0x57, 0x68, 0x70, 0x34, 0x64, 0x44, 0x57, 0x6e,  // 5u1lUr2Whp4dDWnskk9JcJZobO0=
0x73, 0x6b, 0x6b, 0x39, 0x4a, 0x63, 0x4a, 0x5a, 0x6f, 0x62, 0x4f, 0x30, 0x3d, 0x0d, 0x0a,
0x0d, 0x0a,
};

/* A PING with the FIN bit clear.  A control frame may not be fragmented.  */
static UCHAR server_fragmented_ping[] = { 0x09, 0x02, 0xAA, 0xBB };

/* A PING declaring 126 bytes through the 16-bit extended length, one past the
   125 a control frame is allowed.  The payload is present so that the frame is
   complete on the wire and the length is what it is rejected for.  */
static UCHAR server_oversized_ping[4 + 126] = { 0x89, 0x7E, 0x00, 0x7E };

/* A well formed PING, to show the session survives the two rejections.  */
static UCHAR server_valid_ping[] = { 0x89, 0x02, 0xAA, 0xBB };

/* An empty CLOSE, to end the session.  */
static UCHAR server_close[] = { 0x88, 0x00 };

static UCHAR client_boundary_payload[BOUNDARY_PAYLOAD_SIZE];

static ULONG                   error_counter;
static UINT                    invalid_count = 0;
static UINT                    pong_seen = NX_FALSE;
static UINT                    close_reported = NX_FALSE;
static UINT                    boundary_frame_checked = NX_FALSE;

extern void SET_ERROR_COUNTER(ULONG *error_counter, CHAR *filename, int line_number);


#ifdef CTEST
VOID test_application_define(void *first_unused_memory)
#else
void    netx_websocket_frame_boundary_test_application_define(void *first_unused_memory)
#endif
{
CHAR    *pointer;
UINT    status;
UINT    i;


    error_counter = 0;

    /* Fill the payloads with a recognisable pattern.  */
    for (i = 0; i < BOUNDARY_PAYLOAD_SIZE; i++)
    {
        client_boundary_payload[i] = (UCHAR)(i % 32);
    }
    for (i = 0; i < 126; i++)
    {
        server_oversized_ping[4 + i] = (UCHAR)(i % 32);
    }

    /* Setup the working pointer.  */
    pointer =  (CHAR *) first_unused_memory;

    /* Create a helper thread for the server. */
    tx_thread_create(&server_thread, "Test Server thread", thread_server_entry, 0,
                     pointer, DEMO_STACK_SIZE,
                     4, 4, TX_NO_TIME_SLICE, TX_AUTO_START);

    pointer =  pointer + DEMO_STACK_SIZE;

    /* Initialize the NetX system.  */
    nx_system_initialize();

    /* Create the server packet pool.  */
    status =  nx_packet_pool_create(&server_pool, "Test Server Packet Pool", PACKET_SIZE,
                                    pointer, PACKET_SIZE * 8);
    pointer = pointer + PACKET_SIZE * 8;
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    /* Create an IP instance.  */
    status = nx_ip_create(&server_ip, "Test Server IP", TEST_SERVER_ADDRESS,
                          0xFFFFFF00UL, &server_pool, _nx_ram_network_driver_1024,
                          pointer, 2048, 1);
    pointer =  pointer + 2048;
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    /* Enable ARP and supply ARP cache memory for the server IP instance.  */
    status = nx_arp_enable(&server_ip, (void *) pointer, 1024);
    pointer = pointer + 1024;
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

     /* Enable TCP traffic.  */
    status = nx_tcp_enable(&server_ip);
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    /* Create the Test Client thread. */
    status = tx_thread_create(&client_thread, "Test Client", thread_client_entry, 0,
                              pointer, DEMO_STACK_SIZE,
                              6, 6, TX_NO_TIME_SLICE, TX_AUTO_START);
    pointer =  pointer + DEMO_STACK_SIZE;
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    /* Create the Client packet pool.  */
    status =  nx_packet_pool_create(&client_pool, "Test Client Packet Pool", PACKET_SIZE,
                                    pointer, PACKET_SIZE * 8);
    pointer = pointer + PACKET_SIZE * 8;
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    /* Create an IP instance.  */
    status = nx_ip_create(&client_ip, "Test Client IP", TEST_CLIENT_ADDRESS,
                          0xFFFFFF00UL, &client_pool, _nx_ram_network_driver_1024,
                          pointer, 2048, 1);
    pointer =  pointer + 2048;
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    status  = nx_arp_enable(&client_ip, (void *) pointer, 1024);
    pointer =  pointer + 1024;
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

     /* Enable TCP traffic.  */
    status = nx_tcp_enable(&client_ip);
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);
}


/* Sends a frame whose payload is exactly the 125 bytes the 7-bit length field
   can still carry.  The server checks how the header was encoded.  */
static void client_send_boundary_frame(void)
{
UINT        status;
NX_PACKET  *packet_ptr;

    status = nx_packet_allocate(&client_pool, &packet_ptr, NX_TCP_PACKET, NX_IP_PERIODIC_RATE);
    if (status)
    {
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);
        return;
    }

    packet_ptr -> nx_packet_append_ptr = packet_ptr -> nx_packet_prepend_ptr;
    packet_ptr -> nx_packet_length = 0;

    status = nx_packet_data_append(packet_ptr, client_boundary_payload, BOUNDARY_PAYLOAD_SIZE,
                                   &client_pool, NX_IP_PERIODIC_RATE);
    if (status)
    {
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);
        nx_packet_release(packet_ptr);
        return;
    }

    status = nx_websocket_client_send(&client_websocket, packet_ptr,
                                      NX_WEBSOCKET_OPCODE_BINARY_FRAME, NX_TRUE, NX_WAIT_FOREVER);
    if (status)
    {
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);
        nx_packet_release(packet_ptr);
    }
}


void thread_client_entry(ULONG thread_input)
{
UINT            i, status;
NX_PACKET      *packet_ptr;
NXD_ADDRESS     server_ip_address;
UINT            code;

    NX_PARAMETER_NOT_USED(thread_input);

    /* Create client socket.  */
    status = nx_tcp_socket_create(&client_ip, &test_client, "Client Socket", NX_IP_NORMAL, NX_FRAGMENT_OKAY,
                                  NX_IP_TIME_TO_LIVE, 1000, NX_NULL, NX_NULL);
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    /* Create WebSocket.  */
    status = nx_websocket_client_create(&client_websocket, (UCHAR *)" ", &client_ip, &client_pool);
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    /* Give IP task and driver a chance to initialize the system.  */
    tx_thread_sleep(NX_IP_PERIODIC_RATE);

    status = nx_tcp_client_socket_bind(&test_client, TEST_SERVER_PORT, NX_IP_PERIODIC_RATE);
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    while (!test_server_start)
    {
        tx_thread_sleep(NX_IP_PERIODIC_RATE);
    }

    server_ip_address.nxd_ip_address.v4 = TEST_SERVER_ADDRESS;
    server_ip_address.nxd_ip_version = NX_IP_VERSION_V4;

    status = nxd_tcp_client_socket_connect(&test_client, &server_ip_address, TEST_SERVER_PORT, NX_WAIT_FOREVER);
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    /* Upgrade to websocket */
    status = nx_websocket_client_connect(&client_websocket, &test_client,
                                         TEST_HOST_NAME, sizeof(TEST_HOST_NAME) - 1,
                                         (UCHAR *)TEST_URI_PATH, sizeof(TEST_URI_PATH) - 1,
                                         (UCHAR *)TEST_PROTOCOL, sizeof(TEST_PROTOCOL) - 1,
                                         (UCHAR *)TEST_BEARER, sizeof(TEST_BEARER) - 1,
                                         NX_WAIT_FOREVER);
    if (status)
    {
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);
        test_client_stop = 1;
        return;
    }

    /* Drain the connection.  A receive call may consume more than one frame, so the frames
       are not matched one-to-one with calls.  What matters is that both malformed control
       frames are reported as NX_INVALID_PACKET, that nothing is ever handed over as
       application data, and that the peer's CLOSE is eventually reported.  */
    for (i = 0; i < 16; i++)
    {
        status = nx_websocket_client_receive(&client_websocket, &packet_ptr, &code, 2 * NX_IP_PERIODIC_RATE);

        /* Whatever happened, the mutex must not be left held.  */
        if (client_websocket.nx_websocket_client_mutex.tx_mutex_ownership_count != 0)
            SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

        if (status == NX_INVALID_PACKET)
        {
            invalid_count++;

            /* Both malformed frames have been rejected.  The connection is still up and the
               parse state has been dropped rather than poisoned, so the session must still
               carry traffic.  */
            if (invalid_count == 2)
            {
                client_send_boundary_frame();
            }
        }
        else if (status == NX_WEBSOCKET_DISCONNECTED)
        {
            close_reported = NX_TRUE;
            break;
        }
        else if (status == NX_SUCCESS)
        {

            /* No frame in this test carries application data.  */
            SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);
            nx_packet_release(packet_ptr);
        }
        else if (status != NX_NO_PACKET)
        {

            /* NX_NO_PACKET simply means nothing was ready yet; anything else is a failure.  */
            SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);
        }
    }

    /* Exactly the two malformed control frames, no more and no fewer.  */
    if (invalid_count != 2)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    if (close_reported != NX_TRUE)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    /* No packet may have been released twice or leaked along the way.  */
    if (client_pool.nx_packet_pool_invalid_releases)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    test_client_stop = 1;
}


/* Sends one frame in its own TCP segment.  */
static void send_frame(UCHAR *frame, ULONG frame_size)
{
UINT        status;
NX_PACKET  *packet_ptr;

    status = nx_packet_allocate(&server_pool, &packet_ptr, NX_TCP_PACKET, NX_IP_PERIODIC_RATE);
    if (status)
    {
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);
        return;
    }

    status = nx_packet_data_append(packet_ptr, frame, frame_size, &server_pool, NX_IP_PERIODIC_RATE);
    if (status)
    {
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);
        nx_packet_release(packet_ptr);
        return;
    }

    status = nx_tcp_socket_send(&test_server, packet_ptr, NX_IP_PERIODIC_RATE);
    if (status)
    {
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);
        nx_packet_release(packet_ptr);
    }
}


void    thread_server_entry(ULONG thread_input)
{
UINT            status;
NX_PACKET      *packet_ptr;
UCHAR           header[2];
ULONG           bytes_copied;

    NX_PARAMETER_NOT_USED(thread_input);

    printf("NetX Test:   Websocket Frame Boundary Test.............................");

    if (error_counter)
    {
        printf("ERROR!\n");
        test_control_return(1);
    }

    tx_thread_sleep(NX_IP_PERIODIC_RATE);

    status = nx_tcp_socket_create(&server_ip, &test_server, "Test Server Socket",
                                  NX_IP_NORMAL, NX_FRAGMENT_OKAY, NX_IP_TIME_TO_LIVE, 1000,
                                  NX_NULL, NX_NULL);
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    status = nx_tcp_server_socket_listen(&server_ip, TEST_SERVER_PORT, &test_server, 5, NX_NULL);
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    test_server_start = 1;

    status = nx_tcp_server_socket_accept(&test_server, 5 * NX_IP_PERIODIC_RATE);
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    /* Complete the WebSocket handshake.  */
    status = nx_tcp_socket_receive(&test_server, &packet_ptr, 5 * NX_IP_PERIODIC_RATE);
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);
    else
    {
        _server_connect_response_process(packet_ptr);
        memcpy(&server_switch_101[127], connect_key, 28); /* Use case of memcpy is verified. */

        packet_ptr -> nx_packet_append_ptr = packet_ptr -> nx_packet_prepend_ptr;
        packet_ptr -> nx_packet_length = 0;
        nx_packet_data_append(packet_ptr, server_switch_101, sizeof(server_switch_101), &server_pool, NX_IP_PERIODIC_RATE);
        status = nx_tcp_socket_send(&test_server, packet_ptr, NX_IP_PERIODIC_RATE);
        if (status)
        {
            SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);
            nx_packet_release(packet_ptr);
        }
    }

    /* 1. A fragmented control frame, then 2. an oversized one.  Each is sent alone so that
       it is rejected on its own rather than as part of a larger parse.  */
    send_frame(server_fragmented_ping, sizeof(server_fragmented_ping));

    tx_thread_sleep(NX_IP_PERIODIC_RATE);
    send_frame(server_oversized_ping, sizeof(server_oversized_ping));

    /* 3. The client answers the second rejection by sending its 125 byte frame.  */
    status = nx_tcp_socket_receive(&test_server, &packet_ptr, 5 * NX_IP_PERIODIC_RATE);
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);
    else
    {
        nx_packet_data_extract_offset(packet_ptr, 0, header, sizeof(header), &bytes_copied);
        if (bytes_copied != sizeof(header))
            SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);
        else
        {

            /* 125 is the largest the 7-bit field carries, so the length must be in the
               second header byte and the frame must be two bytes of header, the masking key
               and the payload.  Encoding it as an extended length would also overrun the
               six bytes reserved in front of the payload.  */
            if ((header[0] != (NX_WEBSOCKET_FIN | NX_WEBSOCKET_OPCODE_BINARY_FRAME)) ||
                (header[1] != (NX_WEBSOCKET_MASK | BOUNDARY_PAYLOAD_SIZE)) ||
                (packet_ptr -> nx_packet_length != BOUNDARY_FRAME_SIZE))
            {
                SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);
            }
            else
            {
                boundary_frame_checked = NX_TRUE;
            }
        }

        nx_packet_release(packet_ptr);
    }

    /* 4. A well formed PING, which must still be answered.  */
    send_frame(server_valid_ping, sizeof(server_valid_ping));

    status = nx_tcp_socket_receive(&test_server, &packet_ptr, 5 * NX_IP_PERIODIC_RATE);
    if (status)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);
    else
    {

        /* A client frame is masked, so only the low nibble of the first byte is the opcode.  */
        if ((UCHAR)(*(packet_ptr -> nx_packet_prepend_ptr) & 0x0F) == NX_WEBSOCKET_OPCODE_PONG)
        {
            pong_seen = NX_TRUE;
        }
        else
        {
            SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);
        }

        nx_packet_release(packet_ptr);
    }

    /* 5. Close the session.  */
    tx_thread_sleep(NX_IP_PERIODIC_RATE);
    send_frame(server_close, sizeof(server_close));

    /* Wait for the client to finish its checks.  */
    while (!test_client_stop)
    {
        tx_thread_sleep(NX_IP_PERIODIC_RATE);
    }

    if (boundary_frame_checked != NX_TRUE)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    if (pong_seen != NX_TRUE)
        SET_ERROR_COUNTER(&error_counter, __FILE__, __LINE__);

    if (error_counter)
    {
        printf("ERROR!\n");
        test_control_return(1);
    }
    else
    {
        printf("SUCCESS!\n");
        test_control_return(0);
    }
}

#else

#ifdef CTEST
VOID test_application_define(void *first_unused_memory)
#else
void    netx_websocket_frame_boundary_test_application_define(void *first_unused_memory)
#endif
{

    /* Print out test information banner.  */
    printf("NetX Test:   Websocket Frame Boundary Test.............................N/A\n");

    test_control_return(3);
}
#endif
