#!/bin/bash
##############################################################################
# Copyright (c) 2026 Eclipse ThreadX contributors
#
# This program and the accompanying materials are made available under the
# terms of the MIT License which is available at
# https://opensource.org/licenses/MIT.
#
# AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
# The AI-generated portions may be considered public domain (CC0-1.0)
# and not subject to the project's licence. The human contributor has
# reviewed and verified that the code is correct.
#
# SPDX-License-Identifier: MIT and CC0-1.0
##############################################################################

# Compiles the library with NX_LITTLE_ENDIAN suppressed, so that code which
# only builds on a little-endian port is caught on an ordinary x86 machine.
#
#     scripts/check_endian.sh
#     scripts/check_endian.sh --quiet
#     scripts/check_endian.sh --file addons/mdns/nxd_mdns.c
#     scripts/check_endian.sh --threadx ../threadx --filex ../filex
#
# Options:
#     --file <path>     Check one source file instead of the whole tree.
#     --threadx <path>  ThreadX checkout, for tx_api.h and tx_port.h.
#     --filex <path>    FileX checkout, for the add-ons that need fx_api.h.
#     --cc <path>       Compiler to use; defaults to $CC then to gcc.
#     --quiet           Print only failures and the summary.
#
# Exit status is 0 when everything compiles and 1 otherwise.
#
# Why this exists: the endian macros are not interchangeable between the two
# branches of the port header. On a little-endian port,
#
#     #define NX_CHANGE_ULONG_ENDIAN(a)   a = (...)
#
# expands to an assignment, which parses in expression position; on a
# big-endian port the same macro is empty and does not. Code written as
# "x |= NX_CHANGE_USHORT_ENDIAN(y)" therefore compiles for the author and fails
# for everyone building big-endian. One such line reached the repository and
# survived for years, because nothing in CI compiles the tree big-endian and
# almost nobody develops on a big-endian host.
#
# NX_CRYPTO_LITTLE_ENDIAN needs no separate handling: nx_crypto.h derives it
# from NX_LITTLE_ENDIAN, so suppressing the one covers the crypto sources too.
#
# This is a compilation check only. It proves the big-endian branches parse and
# type-check; it does not prove they compute the right answer, which needs a
# big-endian target.

set -u

cd "$(dirname "$(realpath "$0")")/.."

CC_BIN="${CC:-gcc}"
one_file=""
quiet=0
threadx_dir="${THREADX_DIR:-}"
filex_dir="${FILEX_DIR:-}"

while [ "$#" -gt 0 ]; do
    case "$1" in
        --file)    [ "$#" -ge 2 ] || { echo "Error: --file needs a path" >&2; exit 2; }; one_file="$2"; shift 2 ;;
        --threadx) [ "$#" -ge 2 ] || { echo "Error: --threadx needs a path" >&2; exit 2; }; threadx_dir="$2"; shift 2 ;;
        --filex)   [ "$#" -ge 2 ] || { echo "Error: --filex needs a path" >&2; exit 2; }; filex_dir="$2"; shift 2 ;;
        --cc)      [ "$#" -ge 2 ] || { echo "Error: --cc needs a path" >&2; exit 2; }; CC_BIN="$2"; shift 2 ;;
        --quiet)   quiet=1; shift ;;
        -h|--help) sed -n '17,34p' "$0"; exit 0 ;;
        *) echo "Error: unknown option '$1'" >&2; exit 2 ;;
    esac
done

# NetX Duo does not compile without the ThreadX headers. Look where they
# usually are: the submodule this repository already carries, then a sibling
# checkout.
find_dep() {
    name="$1"
    header="$2"
    supplied="$3"
    if [ -n "$supplied" ]; then
        if [ -f "$supplied/common/inc/$header" ]; then echo "$supplied"; return 0; fi
        echo "Error: $supplied does not look like a $name checkout ($header not found)." >&2
        return 1
    fi
    for candidate in "test/cmake/$name" "../$name"; do
        if [ -f "$candidate/common/inc/$header" ]; then echo "$candidate"; return 0; fi
    done
    return 1
}

say() { [ "$quiet" -eq 1 ] || echo "$@"; }

if ! command -v "$CC_BIN" >/dev/null 2>&1; then
    echo "Error: compiler '$CC_BIN' not found. Pass --cc <path> or set CC." >&2
    exit 1
fi

port_header="ports/linux/gnu/inc/nx_port.h"
if [ ! -f "$port_header" ]; then
    echo "Error: $port_header not found; run this from a NetX Duo checkout." >&2
    exit 1
fi

# A doctored copy of the port header, with the endian define removed, placed
# ahead of the real one on the include path. The tree is never modified.
shim="$(mktemp -d)"
trap 'rm -rf "$shim"' EXIT
sed 's|^#define NX_LITTLE_ENDIAN.*|/* NX_LITTLE_ENDIAN suppressed by scripts/check_endian.sh */|' \
    "$port_header" > "$shim/nx_port.h"

if grep -q "NX_LITTLE_ENDIAN suppressed" "$shim/nx_port.h"; then
    :
else
    echo "Error: could not suppress NX_LITTLE_ENDIAN in $port_header." >&2
    echo "The define may have been reworded; check it by hand." >&2
    exit 1
fi

if ! tx="$(find_dep threadx tx_api.h "$threadx_dir")"; then
    echo "Error: ThreadX headers not found. NetX Duo cannot compile without them." >&2
    echo "Pass --threadx <path>, set THREADX_DIR, or populate the submodule:" >&2
    echo "  git submodule update --init test/cmake/threadx" >&2
    exit 1
fi
fx="$(find_dep filex fx_api.h "$filex_dir" || true)"

common_includes="-Icommon/inc -Iports/linux/gnu/inc -Inx_secure/inc -Inx_secure/ports"
common_includes="$common_includes -Icrypto_libraries/inc"
common_includes="$common_includes -I$tx/common/inc -I$tx/ports/linux/gnu/inc"
[ -n "$fx" ] && common_includes="$common_includes -I$fx/common/inc -I$fx/ports/linux/gnu/inc"
for d in addons/*/; do
    common_includes="$common_includes -I${d%/}"
done
[ -d tsn/inc ] && common_includes="$common_includes -Itsn/inc"

# The shim goes first only for the big-endian pass.
be_includes="-I$shim $common_includes"
le_includes="$common_includes"

# The Azure IoT add-on carries its own vendored SDK and is excluded: it is not
# part of the core library and pulls in an external include tree.
sources() {
    if [ -n "$one_file" ]; then
        echo "$one_file"
        return
    fi
    find common/src nx_secure/src crypto_libraries/src addons utility \
        -name '*.c' 2>/dev/null | grep -v '/azure_iot/' | sort
}

say ""
say "Using: $CC_BIN ($("$CC_BIN" --version | head -1))"
say "       NX_LITTLE_ENDIAN suppressed via $shim/nx_port.h"
say ""

total=0
failed=0
failed_list=""
both=0

# Each source is compiled twice: once as the port ships, once with the endian
# define suppressed. Only a file that compiles one way and not the other is an
# endian defect. Anything failing both ways is a pre-existing problem on this
# host -- the BSD add-on clashes with the glibc definition of struct timeval,
# for one -- and reporting those would bury the finding this check exists for.
# Comparing rather than excluding also means there is no skip list to rot.
for src in $(sources); do
    [ -f "$src" ] || { echo "  FAIL: $src does not exist"; failed=$((failed + 1)); continue; }
    total=$((total + 1))
    # -w because the goal is to find what does not compile big-endian, not to
    # relitigate every warning the tree already carries on the little-endian
    # path. Errors are still reported.
    if ! be_out="$("$CC_BIN" $be_includes -w -c "$src" -o /dev/null 2>&1)"; then
        if "$CC_BIN" $le_includes -w -c "$src" -o /dev/null >/dev/null 2>&1; then
            echo "  FAIL: $src"
            echo "$be_out" | grep -E "error:" | head -3 | sed 's/^/        /'
            failed=$((failed + 1))
            failed_list="$failed_list $src"
        else
            both=$((both + 1))
        fi
    fi
done

say ""
say "  $((total - failed - both)) of $total sources compile both ways."
if [ "$both" -gt 0 ]; then
    say "  $both do not compile either way, so they are not endian defects."
fi

if [ "$failed" -eq 0 ]; then
    say ""
    say "Big-endian compilation check passed."
    exit 0
fi

echo ""
echo "  $failed source(s) compile little-endian but not big-endian:$failed_list"
echo ""
echo "$failed source(s) do not compile big-endian."
exit 1
