# Copyright (c) 2026 Eclipse ThreadX contributors
#
# SPDX-License-Identifier: MIT
# Some portions generated by Codex (gpt-5.6-sol).
#
# Runs the existing Linux interoperability suites from a Windows host through
# WSL2 and a Linux-native repository checkout without modifying Windows
# network adapters or firewall configuration.

[CmdletBinding()]
param(
    [ValidateSet('mqtt', 'secure', 'all')]
    [string]$Suite = 'all',

    [ValidateSet('build', 'test')]
    [string]$Operation = 'test',

    [string[]]$Configuration = @('all'),

    [string]$Distribution,

    [string]$WindowsRepositoryRoot = (Split-Path -Parent $PSScriptRoot),

    [string]$LinuxRepositoryRoot,

    [ValidateRange(0, [int]::MaxValue)]
    [int]$TimeoutSeconds = 0,

    [switch]$CheckOnly,

    [switch]$DryRun
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function ConvertTo-ProcessArgument {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Argument
    )

    if ($Argument -notmatch '\s|"') {
        return $Argument
    }

    return '"' + ($Argument -replace '"', '\"') + '"'
}

function Get-WslBaseArguments {
    if ([string]::IsNullOrWhiteSpace($Distribution)) {
        return @()
    }

    if ($Distribution -notmatch '^[A-Za-z0-9._-]+$') {
        throw "Invalid WSL distribution name: $Distribution"
    }

    return @('--distribution', $Distribution)
}

function Invoke-WslCommand {
    param(
        [Parameter(Mandatory = $true)]
        [string[]]$Arguments
    )

    & $script:WslExecutable @script:WslBaseArguments @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "WSL command failed with exit code ${LASTEXITCODE}: $($Arguments -join ' ')"
    }
}

function ConvertTo-LinuxPath {
    param(
        [Parameter(Mandatory = $true)]
        [string]$WindowsPath
    )

    $convertedPath = & $script:WslExecutable @script:WslBaseArguments --exec wslpath -a -u $WindowsPath
    if (($LASTEXITCODE -ne 0) -or [string]::IsNullOrWhiteSpace($convertedPath)) {
        throw "Unable to translate Windows path for WSL: $WindowsPath"
    }

    return $convertedPath.Trim()
}

function Stop-WslProcessGroup {
    param(
        [Parameter(Mandatory = $true)]
        [string]$SupervisorPath,

        [Parameter(Mandatory = $true)]
        [string]$PidFile
    )

    try {
        & $script:WslExecutable @script:WslBaseArguments --exec bash $SupervisorPath --cleanup $PidFile
    }
    catch {
        Write-Warning "WSL cleanup failed: $($_.Exception.Message)"
    }
}

if (($Configuration.Count -eq 0) -or ($Configuration -contains '')) {
    throw 'At least one non-empty configuration is required.'
}

if ($Distribution -and ($Distribution -notmatch '^[A-Za-z0-9._-]+$')) {
    throw "Invalid WSL distribution name: $Distribution"
}

if ($LinuxRepositoryRoot -and (-not $LinuxRepositoryRoot.StartsWith('/'))) {
    throw 'LinuxRepositoryRoot must be an absolute Linux path.'
}

foreach ($configurationName in $Configuration) {
    if ($configurationName -notmatch '^[A-Za-z0-9_]+$') {
        throw "Invalid configuration name: $configurationName"
    }
}

if (($Configuration -contains 'all') -and ($Configuration.Count -ne 1)) {
    throw 'The all configuration cannot be combined with named configurations.'
}

$selectedSuites = switch ($Suite) {
    'mqtt'   { @('mqtt_interoperability') }
    'secure' { @('nx_secure_interoperability') }
    'all'    { @('mqtt_interoperability', 'nx_secure_interoperability') }
}

if ($DryRun) {
    $plannedRepositoryRoot = if ($LinuxRepositoryRoot) { $LinuxRepositoryRoot } else { '<translated-windows-repository>' }
    $plannedDistribution = if ($Distribution) { $Distribution } else { '<default>' }
    Write-Output "WSL_DISTRIBUTION=$plannedDistribution"
    Write-Output "LINUX_REPOSITORY_ROOT=$plannedRepositoryRoot"
    if ($CheckOnly) {
        Write-Output 'CHECK_ONLY=true'
        return
    }
    foreach ($selectedSuite in $selectedSuites) {
        Write-Output "RUN=$selectedSuite $Operation $($Configuration -join ' ')"
    }
    return
}

$wslCommand = Get-Command wsl.exe -ErrorAction SilentlyContinue
if ($null -eq $wslCommand) {
    throw 'wsl.exe was not found. Install and enable WSL2 before using this wrapper.'
}

$script:WslExecutable = $wslCommand.Source
$script:WslBaseArguments = @(Get-WslBaseArguments)

$supervisorWindowsPath = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot 'run_interoperability_wsl.sh'))
$supervisorLinuxPath = ConvertTo-LinuxPath -WindowsPath $supervisorWindowsPath

if ([string]::IsNullOrWhiteSpace($LinuxRepositoryRoot)) {
    $repositoryWindowsPath = [System.IO.Path]::GetFullPath($WindowsRepositoryRoot)
    $LinuxRepositoryRoot = ConvertTo-LinuxPath -WindowsPath $repositoryWindowsPath
}
Invoke-WslCommand -Arguments (@(
    '--exec', 'bash', $supervisorLinuxPath,
    '--check', $LinuxRepositoryRoot
) + $selectedSuites)

if ($CheckOnly) {
    Write-Output 'WSL interoperability preflight passed.'
    return
}

if ($Operation -eq 'test') {
    Write-Host 'Validating cached sudo credentials for Linux network setup.'
    Invoke-WslCommand -Arguments @('--exec', 'sudo', '-v')
}

foreach ($selectedSuite in $selectedSuites) {
    $runId = [Guid]::NewGuid().ToString('N')
    $pidFile = "/tmp/threadx-wsl-interop-$runId.pid"
    $wslArguments = @($script:WslBaseArguments) + @(
        '--exec', 'bash', $supervisorLinuxPath,
        $pidFile, $LinuxRepositoryRoot, $selectedSuite, $Operation
    ) + $Configuration
    $processArguments = @($wslArguments | ForEach-Object { ConvertTo-ProcessArgument -Argument $_ })

    Write-Host "Running $selectedSuite / $Operation in WSL."
    $process = Start-Process -FilePath $script:WslExecutable -ArgumentList $processArguments `
        -NoNewWindow -PassThru
    $timedOut = $false

    try {
        if ($TimeoutSeconds -le 0) {
            $process | Wait-Process
        }
        else {
            try {
                $process | Wait-Process -Timeout $TimeoutSeconds -ErrorAction Stop
            }
            catch {
                if ($process.HasExited) {
                    throw
                }
                $timedOut = $true
            }
        }
    }
    finally {
        if (-not $process.HasExited) {
            $null = Start-Process -FilePath 'taskkill.exe' `
                -ArgumentList @('/PID', $process.Id.ToString(), '/T', '/F') `
                -WindowStyle Hidden -Wait -PassThru
        }
        Stop-WslProcessGroup -SupervisorPath $supervisorLinuxPath -PidFile $pidFile
    }

    if ($timedOut) {
        throw "$selectedSuite timed out after $TimeoutSeconds seconds."
    }

    $process.Refresh()
    if ($process.ExitCode -ne 0) {
        throw "$selectedSuite failed with exit code $($process.ExitCode)."
    }
}
