#!/bin/bash
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Eclipse ThreadX Contributors
# Some portions generated by Copilot (claude-sonnet-4.6).
#
# Update test submodules to the latest commit on their release branch (master).
# Run this on release day after dev has been merged to master.

set -euo pipefail

REPO_ROOT="$(dirname "$(realpath "$0")")/.."
SUBMODULES=(
    "test/cmake/filex"
    "test/cmake/threadx"
)
RELEASE_BRANCH="master"

cd "$REPO_ROOT"

for sub in "${SUBMODULES[@]}"; do
    echo "Updating $sub to origin/$RELEASE_BRANCH..."
    git -C "$sub" fetch origin "$RELEASE_BRANCH"
    git -C "$sub" checkout "origin/$RELEASE_BRANCH"
done

git add "${SUBMODULES[@]}"
echo ""
echo "Submodules updated. Review with 'git diff --cached', then commit:"
echo "  git commit -m \"chore: update submodules to latest release commits\""
