#!/bin/bash
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Eclipse ThreadX Contributors
# Some portions generated by Copilot (claude-sonnet-4.6).
#
# Update test submodules to the latest commit on their dev branch.
# Run this script from the repository root.

set -euo pipefail

REPO_ROOT="$(dirname "$(realpath "$0")")/.."
SUBMODULES=(
    "test/cmake/filex"
    "test/cmake/threadx"
)

cd "$REPO_ROOT"

for sub in "${SUBMODULES[@]}"; do
    echo "Updating $sub to origin/dev..."
    git -C "$sub" fetch origin dev
    git -C "$sub" checkout origin/dev
done

git add "${SUBMODULES[@]}"
echo ""
echo "Submodules updated. Review with 'git diff --cached', then commit:"
echo "  git commit -m \"chore: update submodules to latest dev commits\""
