/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Codex (GPT-6-Sol).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

#include "tx_api.h"
#include "nx_api.h"
#include "nx_ppp.h"

extern void test_control_return(UINT status);

#ifndef NX_DISABLE_IPV4

#define TEST_STACK_SIZE 2048
#define TEST_FRAME_COUNT 18

static TX_THREAD test_thread;
static NX_PACKET_POOL test_pool;
static NX_PPP test_ppp;
static NX_IP test_ip;
static CHAR *test_memory;

/* A valid short PPP frame with a protocol field; packet processing discards it.  */
static const UCHAR test_frame[] = {0x7e, 0xff, 0x03, 0xc0, 0x21, 0x49, 0x2c, 0x7e};

static void test_thread_entry(ULONG input);
static void test_byte_send(UCHAR byte);

/* Create the objects before the test thread queues the receive burst.  */
#ifdef CTEST
VOID test_application_define(void *first_unused_memory)
#else
void netx_ppp_receive_burst_test_application_define(void *first_unused_memory)
#endif
{
CHAR *pointer = (CHAR *)first_unused_memory;

    nx_system_initialize();
    test_memory = pointer + TEST_STACK_SIZE;
    tx_thread_create(&test_thread, "PPP burst test", test_thread_entry, 0,
                     pointer, TEST_STACK_SIZE, 5, 5, TX_NO_TIME_SLICE, TX_AUTO_START);
}

/* Ignore output; the test only supplies short receive frames.  */
static void test_byte_send(UCHAR byte)
{
    (void)byte;
}

/* Verify one coalesced event consumes valid frames on both sides of a bad one.  */
static void test_thread_entry(ULONG input)
{
CHAR *pointer;
UINT status;
UINT frame_index;
UINT byte_index;
UCHAR byte;

    (void)input;
    printf("NetX Test:   PPP Receive Burst Test...................................");

    pointer = test_memory;
    status = nx_packet_pool_create(&test_pool, "PPP packets", NX_PPP_MIN_PACKET_PAYLOAD,
                                   pointer, 8192);
    pointer += 8192;
    if (status != NX_SUCCESS)
    {
        printf("ERROR!\n");
        test_control_return(1);
        return;
    }

    status = nx_ppp_create(&test_ppp, "PPP burst", &test_ip, pointer,
                           TEST_STACK_SIZE, 4, &test_pool, NX_NULL, test_byte_send);
    if (status != NX_SUCCESS)
    {
        printf("ERROR!\n");
        test_control_return(1);
        return;
    }

    /* Keep the PPP thread stopped while the receive event coalesces.  */
    test_ppp.nx_ppp_state = NX_PPP_STARTED;
    for (frame_index = 0; frame_index < TEST_FRAME_COUNT + 1; frame_index++)
    {
        for (byte_index = 0; byte_index < sizeof(test_frame); byte_index++)
        {
            byte = test_frame[byte_index];
            if ((frame_index == 1) && (byte_index == 5))
            {
                byte ^= 1;
            }
            status = nx_ppp_byte_receive(&test_ppp, byte);
            if (status != NX_SUCCESS)
            {
                printf("ERROR!\n");
                test_control_return(1);
                return;
            }
        }
    }

    /* An incomplete escape must remain buffered until its next byte arrives.  */
    status = nx_ppp_byte_receive(&test_ppp, 0x7d);
    if (status != NX_SUCCESS)
    {
        printf("ERROR!\n");
        test_control_return(1);
        return;
    }

    tx_thread_resume(&test_ppp.nx_ppp_thread);
    tx_thread_sleep(2);

    if ((test_ppp.nx_ppp_total_frames_received != TEST_FRAME_COUNT) ||
        (test_ppp.nx_ppp_frame_crc_errors != 1) ||
        (test_ppp.nx_ppp_serial_buffer_byte_count != 1))
    {
        printf("ERROR!\n");
        test_control_return(1);
        return;
    }

    status = nx_ppp_byte_receive(&test_ppp, 0x20);
    tx_thread_sleep(2);
    if ((status != NX_SUCCESS) ||
        (test_ppp.nx_ppp_serial_buffer_byte_count != 0))
    {
        printf("ERROR!\n");
        test_control_return(1);
        return;
    }

    printf("SUCCESS!\n");
    test_control_return(0);
}

#else

/* PPP serial receive support requires IPv4.  */
#ifdef CTEST
VOID test_application_define(void *first_unused_memory)
#else
void netx_ppp_receive_burst_test_application_define(void *first_unused_memory)
#endif
{
    (void)first_unused_memory;
    test_control_return(3);
}

#endif
