set(ASC_SECURITY_MODULE_ID "defender-iot-micro-agent")

set(ASC_COLLECTOR_HEARTBEAT_ENABLED ON)
set(ASC_COLLECTOR_BASELINE_ENABLED OFF)
set(ASC_COLLECTOR_NETWORK_ACTIVITY_ENABLED OFF)
set(ASC_COLLECTOR_PROCESS_ENABLED OFF)
set(ASC_COLLECTOR_SYSTEM_INFORMATION_ENABLED OFF)
set(ASC_COLLECTOR_LISTENING_PORTS_ENABLED OFF)

set(ASC_COMPONENT_COMMAND_EXECUTOR OFF)
set(ASC_COMPONENT_CONFIGURATION OFF)
set(ASC_COMPONENT_SECURITY_MODULE OFF)

set(ASC_DYNAMIC_MEMORY_ENABLED OFF)

set(ASC_BEST_EFFORT_EVENT_LOOP OFF)

set(run_core_unittests OFF)
set(run_core_coverage OFF)
set(build_json_printer OFF)
