/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Codex (GPT-6).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

#include "tx_api.h"
#include "nx_api.h"
#include "fx_api.h"
#include "nx_web_http_server.h"
#include <string.h>
#include <stdio.h>

extern VOID _nx_ram_network_driver_1024(NX_IP_DRIVER *driver_req_ptr);
extern VOID test_control_return(UINT status);

#if !defined(NX_DISABLE_IPV4) && !defined(NX_WEB_HTTP_KEEPALIVE_DISABLE)

#define SERVER_ADDRESS IP_ADDRESS(1, 2, 3, 4)
#define CLIENT_ADDRESS IP_ADDRESS(1, 2, 3, 5)
#define PACKET_SIZE (NX_WEB_HTTP_SERVER_MIN_PACKET_SIZE * 2)

static NX_IP server_ip;
static NX_IP client_ip;
static NX_PACKET_POOL server_pool;
static NX_PACKET_POOL client_pool;
static NX_WEB_HTTP_SERVER server;
static NX_TCP_SOCKET client_socket;
static TX_THREAD server_thread;
static TX_THREAD client_thread;
static UCHAR server_stack[16384];
static UCHAR server_pool_memory[PACKET_SIZE * 16];
static UCHAR client_pool_memory[PACKET_SIZE * 16];
static UCHAR server_ip_stack[4096];
static UCHAR client_ip_stack[4096];
static UCHAR server_arp[1024];
static UCHAR client_arp[1024];
static UCHAR client_thread_stack[4096];
static UCHAR worker_stack[4096];
static NX_TCP_SESSION *stream_session;
static UINT error_count;
static UINT server_ready;

/* Start one event stream from the GET callback. */
static UINT request_notify(NX_WEB_HTTP_SERVER *server_ptr, UINT request_type,
                           CHAR *resource, NX_PACKET *request_ptr)
{
UINT status;

    NX_PARAMETER_NOT_USED(resource);
    NX_PARAMETER_NOT_USED(request_ptr);
    if(request_type != NX_WEB_HTTP_SERVER_GET_REQUEST)
    {
        error_count++;
        return(NX_WEB_HTTP_CALLBACK_COMPLETED);
    }

    status = nx_web_http_server_event_stream_start(server_ptr, &stream_session);
    if(status != NX_SUCCESS)
    {
        error_count++;
    }
    return(NX_WEB_HTTP_CALLBACK_COMPLETED);
}

/* Initialize the two local IP instances and start the HTTP server. */
static VOID worker_entry(ULONG input)
{
UINT status;

    NX_PARAMETER_NOT_USED(input);
    status = nx_web_http_server_create(&server, "event server", &server_ip,
                                       NX_WEB_HTTP_SERVER_PORT, NX_NULL,
                                       server_stack, sizeof(server_stack), &server_pool,
                                       NX_NULL, request_notify);
    if(status == NX_SUCCESS)
    {
        status = nx_web_http_server_start(&server);
    }
    if(status != NX_SUCCESS)
    {
        error_count++;
    }
    server_ready = NX_TRUE;

    while(stream_session == NX_NULL)
    {
        tx_thread_sleep(1);
    }

    /* Events can be sent after the ordinary idle timeout has passed. */
    tx_thread_sleep(12 * NX_IP_PERIODIC_RATE);
    status = nx_web_http_server_event_stream_send(&server, stream_session,
                                                   "data: ready\n\n", 13);
    if(status != NX_SUCCESS)
    {
        error_count++;
    }
}

/* Check the response header and an event sent after a long idle interval. */
static VOID client_entry(ULONG input)
{
CHAR request[] = "GET /events HTTP/1.1\r\nHost: test\r\nConnection: keep-alive\r\n\r\n";
CHAR response[256];
NX_PACKET *packet_ptr;
NX_TCP_SESSION foreign_session;
NX_TCP_SESSION *other_session;
ULONG copied;
UINT status;

    NX_PARAMETER_NOT_USED(input);
    while(server_ready != NX_TRUE)
    {
        tx_thread_sleep(1);
    }

    status = nx_tcp_socket_create(&client_ip, &client_socket, "event client",
                                  NX_IP_NORMAL, NX_FRAGMENT_OKAY, NX_IP_TIME_TO_LIVE,
                                  2048, NX_NULL, NX_NULL);
    status += nx_tcp_client_socket_bind(&client_socket, NX_ANY_PORT, NX_IP_PERIODIC_RATE);
    status += nx_tcp_client_socket_connect(&client_socket, SERVER_ADDRESS,
                                           NX_WEB_HTTP_SERVER_PORT, 5 * NX_IP_PERIODIC_RATE);
    if(status != NX_SUCCESS)
    {
        error_count++;
        test_control_return(1);
        return;
    }

    status = nx_packet_allocate(&client_pool, &packet_ptr, NX_TCP_PACKET, NX_WAIT_FOREVER);
    if(status == NX_SUCCESS)
    {
        status = nx_packet_data_append(packet_ptr, request, sizeof(request) - 1,
                                       &client_pool, NX_WAIT_FOREVER);
    }
    if(status == NX_SUCCESS)
    {
        status = nx_tcp_socket_send(&client_socket, packet_ptr, NX_WAIT_FOREVER);
    }
    if(status != NX_SUCCESS)
    {
        error_count++;
        test_control_return(1);
        return;
    }

    status = nx_tcp_socket_receive(&client_socket, &packet_ptr, 5 * NX_IP_PERIODIC_RATE);
    if(status == NX_SUCCESS)
    {
        copied = sizeof(response) - 1;
        status = nx_packet_data_retrieve(packet_ptr, response, &copied);
        nx_packet_release(packet_ptr);
        response[copied] = 0;
        if((status != NX_SUCCESS) ||
           (strstr(response, "Content-Type: text/event-stream\r\n") == NX_NULL) ||
           (strstr(response, "Connection: keep-alive\r\n") == NX_NULL) ||
           (strstr(response, "Content-Length:") != NX_NULL))
        {
            error_count++;
        }
    }
    else
    {
        error_count++;
    }

    /* Only the callback can start a stream, and only its session can send. */
    if((nx_web_http_server_event_stream_start(&server, &other_session) != NX_WEB_HTTP_ERROR) ||
       (nx_web_http_server_event_stream_send(&server, &foreign_session,
                                             request, sizeof(request) - 1) != NX_PTR_ERROR) ||
       (nx_web_http_server_event_stream_send(&server, stream_session,
                                             request, 0) != NX_WEB_HTTP_ERROR))
    {
        error_count++;
    }

    status = nx_tcp_socket_receive(&client_socket, &packet_ptr, 16 * NX_IP_PERIODIC_RATE);
    if(status == NX_SUCCESS)
    {
        copied = sizeof(response) - 1;
        status = nx_packet_data_retrieve(packet_ptr, response, &copied);
        nx_packet_release(packet_ptr);
        if((status != NX_SUCCESS) || (copied != 13) ||
           (memcmp(response, "data: ready\n\n", 13) != 0))
        {
            error_count++;
        }
    }
    else
    {
        error_count++;
    }

    nx_tcp_socket_disconnect(&client_socket, NX_IP_PERIODIC_RATE);
    nx_tcp_client_socket_unbind(&client_socket);
    nx_tcp_socket_delete(&client_socket);
    nx_web_http_server_delete(&server);
    if(error_count == 0)
    {
        printf("NetX Test: Web Event Stream Test........................SUCCESS!\n");
        test_control_return(0);
    }
    else
    {
        printf("NetX Test: Web Event Stream Test........................ERROR!\n");
        test_control_return(1);
    }
}

#ifdef CTEST
VOID test_application_define(VOID *first_unused_memory)
#else
VOID netx_web_event_stream_test_application_define(VOID *first_unused_memory)
#endif
{
UINT status;

    NX_PARAMETER_NOT_USED(first_unused_memory);
    nx_system_initialize();
    status = nx_packet_pool_create(&server_pool, "server pool", PACKET_SIZE,
                                   server_pool_memory, sizeof(server_pool_memory));
    status += nx_packet_pool_create(&client_pool, "client pool", PACKET_SIZE,
                                    client_pool_memory, sizeof(client_pool_memory));
    status += nx_ip_create(&server_ip, "server ip", SERVER_ADDRESS, 0xFFFFFF00UL,
                           &server_pool, _nx_ram_network_driver_1024,
                           server_ip_stack, sizeof(server_ip_stack), 1);
    status += nx_ip_create(&client_ip, "client ip", CLIENT_ADDRESS, 0xFFFFFF00UL,
                           &client_pool, _nx_ram_network_driver_1024,
                           client_ip_stack, sizeof(client_ip_stack), 1);
    status += nx_arp_enable(&server_ip, server_arp, sizeof(server_arp));
    status += nx_arp_enable(&client_ip, client_arp, sizeof(client_arp));
    status += nx_tcp_enable(&server_ip);
    status += nx_tcp_enable(&client_ip);
    status += tx_thread_create(&server_thread, "server worker", worker_entry, 0,
                               worker_stack, sizeof(worker_stack), 4, 4,
                               TX_NO_TIME_SLICE, TX_AUTO_START);
    status += tx_thread_create(&client_thread, "client worker", client_entry, 0,
                               client_thread_stack, sizeof(client_thread_stack), 5, 5,
                               TX_NO_TIME_SLICE, TX_AUTO_START);
    if(status != NX_SUCCESS)
    {
        error_count++;
    }
}

#else

#ifdef CTEST
VOID test_application_define(VOID *first_unused_memory)
#else
VOID netx_web_event_stream_test_application_define(VOID *first_unused_memory)
#endif
{
    NX_PARAMETER_NOT_USED(first_unused_memory);
    test_control_return(3);
}
#endif
