/***************************************************************************
 * Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* This case tests the Content-Length underflow detection in the PUT request
   processing of the Web server add-on.

   A raw TCP client sends a PUT request whose Content-Length header is smaller
   than the number of body bytes actually present in the first packet.  That
   makes the (length - consumed_length) subtraction in
   _nx_web_http_server_put_process() wrap around, which must be detected and
   answered with a 400 response.

   The test verifies two things:

     1. The server answers 400 rather than accepting the request.

     2. The server packet pool is fully restored afterwards, so the path
        neither leaks a packet nor hands one back twice.

   Note that this test does not, on its own, distinguish the earlier defect on
   this path, where the underflow branch released a packet pointer that had not
   been assigned yet.  The consequence of that release depends on whatever the
   uninitialized stack slot happened to hold, so it is not reproducible from a
   test.  What the test does guarantee is that the branch is exercised at all
   and that its packet accounting is correct.  */

#include    "tx_api.h"
#include    "nx_api.h"
#include    "fx_api.h"
#include    "nx_web_http_client.h"
#include    "nx_web_http_server.h"

extern void test_control_return(UINT);

#if !defined(NX_DISABLE_IPV4)

#define     DEMO_STACK_SIZE         4096

/* Set up FileX and file memory resources.  */
static CHAR             ram_disk_memory[4096];
static FX_MEDIA         ram_disk;
static UCHAR            media_memory[4096];

static UCHAR            server_stack[16000];

/* Define device drivers.  */
extern void _fx_ram_driver(FX_MEDIA *media_ptr);
extern void _nx_ram_network_driver_1024(NX_IP_DRIVER *driver_req_ptr);

/* Set up the client global variables.  */

#define         CLIENT_PACKET_SIZE  (NX_WEB_HTTP_CLIENT_MIN_PACKET_SIZE * 2)

static TX_THREAD           client_thread;
static NX_PACKET_POOL      client_pool;
static NX_IP               client_ip;
static NX_TCP_SOCKET       client_socket;
static UINT                error_counter;

/* Set up the HTTP server global variables.  */

#define         SERVER_PACKET_SIZE  (NX_WEB_HTTP_SERVER_MIN_PACKET_SIZE * 2)

static NX_WEB_HTTP_SERVER  my_server;
static NX_PACKET_POOL      server_pool;
static TX_THREAD           server_thread;
static NX_IP               server_ip;
static NXD_ADDRESS         server_ip_address;

/* Packet pool availability recorded once the server is idle and ready.  */
static ULONG               server_pool_available;

static void thread_client_entry(ULONG thread_input);
static void thread_server_entry(ULONG thread_input);

#define HTTP_SERVER_ADDRESS  IP_ADDRESS(1,2,3,4)
#define HTTP_CLIENT_ADDRESS  IP_ADDRESS(1,2,3,5)

static TX_SEMAPHORE server_start;

/* A PUT request announcing five content bytes but carrying ten.  The whole
   request, headers and body, is delivered in a single packet so that the
   surplus is found in the first packet examined by the server.  */
static CHAR malformed_put_request[] =
    "PUT /underflow.htm HTTP/1.1\r\n"
    "Host: 1.2.3.4\r\n"
    "Content-Length: 5\r\n"
    "\r\n"
    "0123456789";

#ifdef CTEST
VOID test_application_define(void *first_unused_memory)
#else
void    netx_web_put_content_length_underflow_test_application_define(void *first_unused_memory)
#endif
{
CHAR    *pointer;
UINT    status;


    error_counter = 0;

    /* Setup the working pointer.  */
    pointer =  (CHAR *) first_unused_memory;

    /* Create a helper thread for the server.  */
    tx_thread_create(&server_thread, "HTTP Server thread", thread_server_entry, 0,
                     pointer, DEMO_STACK_SIZE,
                     NX_WEB_HTTP_SERVER_PRIORITY, NX_WEB_HTTP_SERVER_PRIORITY, TX_NO_TIME_SLICE, TX_AUTO_START);

    pointer =  pointer + DEMO_STACK_SIZE;

    /* Initialize the NetX system.  */
    nx_system_initialize();

    /* Create the server packet pool.  */
    status =  nx_packet_pool_create(&server_pool, "HTTP Server Packet Pool", SERVER_PACKET_SIZE,
                                    pointer, SERVER_PACKET_SIZE * 8);
    pointer = pointer + SERVER_PACKET_SIZE * 8;
    if (status)
        error_counter++;

    /* Create an IP instance.  */
    status = nx_ip_create(&server_ip, "HTTP Server IP", HTTP_SERVER_ADDRESS,
                          0xFFFFFF00UL, &server_pool, _nx_ram_network_driver_1024,
                          pointer, 4096, 1);
    pointer =  pointer + 4096;
    if (status)
        error_counter++;

    /* Enable ARP and supply ARP cache memory for the server IP instance.  */
    status = nx_arp_enable(&server_ip, (void *) pointer, 1024);
    pointer = pointer + 1024;
    if (status)
        error_counter++;

    /* Enable TCP traffic.  */
    status = nx_tcp_enable(&server_ip);
    if (status)
        error_counter++;

    /* Create the client thread.  */
    status = tx_thread_create(&client_thread, "HTTP Client", thread_client_entry, 0,
                              pointer, DEMO_STACK_SIZE,
                              NX_WEB_HTTP_SERVER_PRIORITY + 2, NX_WEB_HTTP_SERVER_PRIORITY + 2, TX_NO_TIME_SLICE, TX_AUTO_START);
    pointer =  pointer + DEMO_STACK_SIZE;
    if (status)
        error_counter++;

    /* Create the client packet pool.  */
    status =  nx_packet_pool_create(&client_pool, "HTTP Client Packet Pool", CLIENT_PACKET_SIZE,
                                    pointer, CLIENT_PACKET_SIZE * 8);
    pointer = pointer + CLIENT_PACKET_SIZE * 8;
    if (status)
        error_counter++;

    /* Create an IP instance.  */
    status = nx_ip_create(&client_ip, "HTTP Client IP", HTTP_CLIENT_ADDRESS,
                          0xFFFFFF00UL, &client_pool, _nx_ram_network_driver_1024,
                          pointer, 2048, 1);
    pointer =  pointer + 2048;
    if (status)
        error_counter++;

    status = nx_arp_enable(&client_ip, (void *) pointer, 1024);
    pointer =  pointer + 2048;
    if (status)
        error_counter++;

    /* Enable TCP traffic.  */
    status = nx_tcp_enable(&client_ip);
    if (status)
        error_counter++;

    tx_semaphore_create(&server_start, "server start", 0);
}

void thread_client_entry(ULONG thread_input)
{
UINT            status;
NX_PACKET      *send_packet;
NX_PACKET      *recv_packet;
CHAR           *buffer_ptr;
ULONG           available_after;

    NX_PARAMETER_NOT_USED(thread_input);

    /* Give the IP task and the driver a chance to initialize the system.  */
    tx_thread_sleep(NX_IP_PERIODIC_RATE);

    /* Set the server IP address.  */
    server_ip_address.nxd_ip_address.v4 = HTTP_SERVER_ADDRESS;
    server_ip_address.nxd_ip_version = NX_IP_VERSION_V4;

    /* Create the raw client socket.  The request has to be crafted by hand,
       since the HTTP client API would never emit a Content-Length that
       disagrees with the body it sends.  */
    status =  nx_tcp_socket_create(&client_ip, &client_socket, "Client Socket",
                                   NX_IP_NORMAL, NX_FRAGMENT_OKAY, NX_IP_TIME_TO_LIVE, 200,
                                   NX_NULL, NX_NULL);
    if (status)
        error_counter++;

    /* Wait for the server to be ready.  */
    tx_semaphore_get(&server_start, NX_WAIT_FOREVER);

    /* Bind the client socket.  */
    status = nx_tcp_client_socket_bind(&client_socket, NX_ANY_PORT, NX_WAIT_FOREVER);
    if (status)
        error_counter++;

    /* Connect to the HTTP server.  */
    status = nxd_tcp_client_socket_connect(&client_socket, &server_ip_address,
                                           NX_WEB_HTTP_SERVER_PORT, NX_WAIT_FOREVER);
    if (status)
        error_counter++;

    /* Allocate a packet.  */
    status = nx_packet_allocate(&client_pool, &send_packet, NX_TCP_PACKET, NX_WAIT_FOREVER);
    if (status)
        error_counter++;

    /* Build the malformed request.  The terminating null is not sent.  */
    status = nx_packet_data_append(send_packet, malformed_put_request,
                                   sizeof(malformed_put_request) - 1,
                                   &client_pool, NX_WAIT_FOREVER);
    if (status)
        error_counter++;

    /* Send the request.  */
    status = nx_tcp_socket_send(&client_socket, send_packet, NX_WAIT_FOREVER);
    if (status)
    {
        error_counter++;
        nx_packet_release(send_packet);
    }

    /* Pick up the response from the server.  */
    status = nx_tcp_socket_receive(&client_socket, &recv_packet, 5 * NX_IP_PERIODIC_RATE);
    if (status)
    {
        error_counter++;
    }
    else
    {

        /* The underflow must be reported as a bad request.  */
        buffer_ptr = (CHAR *)recv_packet -> nx_packet_prepend_ptr;

        if (recv_packet -> nx_packet_length < 12)
            error_counter++;
        else if ((buffer_ptr[9] != '4') || (buffer_ptr[10] != '0') || (buffer_ptr[11] != '0'))
            error_counter++;

        nx_packet_release(recv_packet);
    }

    /* Disconnect and unbind the socket.  */
    nx_tcp_socket_disconnect(&client_socket, NX_IP_PERIODIC_RATE);
    nx_tcp_client_socket_unbind(&client_socket);

    status = nx_tcp_socket_delete(&client_socket);
    if (status)
        error_counter++;

    /* Let the server finish tearing the session down.  */
    tx_thread_sleep(2 * NX_IP_PERIODIC_RATE);

    /* Every packet the server took must have been given back.  A packet
       released through an unassigned pointer, or a packet never released at
       all, changes this count.  */
    available_after = server_pool.nx_packet_pool_available;

    if (available_after != server_pool_available)
        error_counter++;

    if (error_counter)
    {
        printf("ERROR!\n");
        test_control_return(1);
    }
    else
    {
        printf("SUCCESS!\n");
        test_control_return(0);
    }
}

/* Define the helper HTTP server thread.  */
void    thread_server_entry(ULONG thread_input)
{
UINT            status;

    NX_PARAMETER_NOT_USED(thread_input);

    /* Print out test information banner.  */
    printf("NetX Test:   Web PUT Content Length Underflow Test.....................");

    /* Check for earlier error.  */
    if (error_counter)
    {
        printf("ERROR!\n");
        test_control_return(1);
    }

    fx_media_format(&ram_disk,
                    _fx_ram_driver,               // Driver entry
                    ram_disk_memory,              // RAM disk memory pointer
                    media_memory,                 // Media buffer pointer
                    sizeof(media_memory),         // Media buffer size
                    "MY_RAM_DISK",                // Volume Name
                    1,                            // Number of FATs
                    32,                           // Directory Entries
                    0,                            // Hidden sectors
                    256,                          // Total sectors
                    512,                          // Sector size
                    8,                            // Sectors per cluster
                    1,                            // Heads
                    1);                           // Sectors per track

    /* Open the RAM disk.  */
    status = fx_media_open(&ram_disk, "RAM DISK", _fx_ram_driver, ram_disk_memory, media_memory, sizeof(media_memory));
    if (status)
        error_counter++;

    /* Give NetX a chance to initialize the system.  */
    tx_thread_sleep(NX_IP_PERIODIC_RATE);

    /* Create the HTTP server.  No authentication, so the request reaches the
       PUT processing directly.  */
    status = nx_web_http_server_create(&my_server, "My HTTP Server", &server_ip, NX_WEB_HTTP_SERVER_PORT, &ram_disk,
                                       &server_stack, sizeof(server_stack), &server_pool,
                                       NX_NULL, NX_NULL);
    if (status)
        error_counter++;

    /* OK to start the HTTP server.  */
    status = nx_web_http_server_start(&my_server);
    if (status)
        error_counter++;

    /* Record the pool availability now that the server is idle and listening.  */
    server_pool_available = server_pool.nx_packet_pool_available;

    tx_semaphore_put(&server_start);
}

#else

#ifdef CTEST
VOID test_application_define(void *first_unused_memory)
#else
void    netx_web_put_content_length_underflow_test_application_define(void *first_unused_memory)
#endif
{

    /* Print out test information banner.  */
    printf("NetX Test:   Web PUT Content Length Underflow Test.....................N/A\n");

    test_control_return(3);
}
#endif
