/***************************************************************************
 * Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* This test covers the header/body boundary in
   _nx_web_http_server_field_value_get() (issue #397).

   HTTP header parsing must stop at the first CRLFCRLF.  The message body is
   opaque and must never be interpreted as header fields, otherwise a request
   body can inject headers -- the reported case being a Content-Length request
   whose body contains "Transfer-Encoding: chunked", which made
   _nx_web_http_server_chunked_check() see chunked encoding.

   The cases below are unit-level: each builds a request in a packet and calls
   the parser directly, which lets the boundary conditions be pinned down
   exactly.  Cases 1, 2, 3 and 6 fail without the fix.  */

#include "tx_api.h"
#include "nx_api.h"
#include "nx_web_http_server.h"

extern void test_control_return(UINT);

#if !defined(NX_DISABLE_IPV4)

#define     DEMO_STACK_SIZE         4096
#define     PACKET_SIZE             1024

extern UINT _nx_web_http_server_field_value_get(NX_PACKET *packet_ptr, UCHAR *field_name,
                                                ULONG name_length, UCHAR *field_value,
                                                ULONG field_value_size);

static TX_THREAD           test_thread;
static NX_PACKET_POOL      pool_0;
static UINT                error_counter;

static void thread_entry(ULONG thread_input);

#ifdef CTEST
VOID test_application_define(void *first_unused_memory)
#else
void netx_web_header_boundary_test_application_define(void *first_unused_memory)
#endif
{
CHAR    *pointer;
UINT     status;


    error_counter = 0;

    pointer = (CHAR *)first_unused_memory;

    /* Create the test thread.  */
    tx_thread_create(&test_thread, "Test thread", thread_entry, 0,
                     pointer, DEMO_STACK_SIZE, 4, 4, TX_NO_TIME_SLICE, TX_AUTO_START);
    pointer = pointer + DEMO_STACK_SIZE;

    /* Initialize the NetX system.  */
    nx_system_initialize();

    /* Create a packet pool.  */
    status = nx_packet_pool_create(&pool_0, "Test Packet Pool", PACKET_SIZE,
                                   pointer, PACKET_SIZE * 8);
    pointer = pointer + PACKET_SIZE * 8;
    if (status)
        error_counter++;
}

/* Build a packet holding the supplied request bytes, then look up field_name in
   it.  Returns the parser status; the extracted value is copied to value_out.  */
static UINT field_lookup(const CHAR *request, UINT request_length,
                         const CHAR *field_name, ULONG name_length,
                         UCHAR *value_out, ULONG value_size)
{
NX_PACKET   *packet_ptr;
UINT         status;


    status = nx_packet_allocate(&pool_0, &packet_ptr, NX_TCP_PACKET, NX_WAIT_FOREVER);
    if (status)
    {
        error_counter++;
        return(NX_NOT_SUCCESSFUL);
    }

    status = nx_packet_data_append(packet_ptr, (VOID *)request, request_length,
                                   &pool_0, NX_WAIT_FOREVER);
    if (status)
    {
        error_counter++;
        nx_packet_release(packet_ptr);
        return(NX_NOT_SUCCESSFUL);
    }

    memset(value_out, 0, value_size);
    status = _nx_web_http_server_field_value_get(packet_ptr, (UCHAR *)field_name,
                                                 name_length, value_out, value_size);

    nx_packet_release(packet_ptr);

    return(status);
}

/* Expect the field to be absent.  */
static void expect_not_found(const CHAR *label, const CHAR *request,
                             const CHAR *field_name, ULONG name_length)
{
UCHAR   value[64];
UINT    status;


    status = field_lookup(request, (UINT)strlen(request), field_name, name_length,
                          value, sizeof(value));

    if (status == NX_SUCCESS)
    {

        /* The parser reported a header that is not in the header section.  */
        printf("\n    [%s] expected NOT_FOUND, got \"%s\"", label, (CHAR *)value);
        error_counter++;
    }
}

/* Expect the field to be present with the supplied value.  */
static void expect_value(const CHAR *label, const CHAR *request,
                         const CHAR *field_name, ULONG name_length,
                         const CHAR *expected)
{
UCHAR   value[64];
UINT    status;


    status = field_lookup(request, (UINT)strlen(request), field_name, name_length,
                          value, sizeof(value));

    if (status != NX_SUCCESS)
    {
        printf("\n    [%s] expected \"%s\", got NOT_FOUND", label, expected);
        error_counter++;
    }
    else if (strcmp((CHAR *)value, expected) != 0)
    {
        printf("\n    [%s] expected \"%s\", got \"%s\"", label, expected, (CHAR *)value);
        error_counter++;
    }
}

static void thread_entry(ULONG thread_input)
{

    NX_PARAMETER_NOT_USED(thread_input);

    printf("NetX Test:   Web Header Boundary Test.................................");

    if (error_counter)
    {
        printf("ERROR!\n");
        test_control_return(1);
    }

    /* 1. The reported case: the field appears only in the body, past the header
          terminator.  It must not be reported as a header.  */
    expect_not_found("body contains field",
                     "POST /f HTTP/1.1\r\nHost: h\r\nContent-Length: 40\r\n\r\n"
                     "junkjunkjunkTransfer-Encoding: chunked\r\n",
                     "Transfer-Encoding", 17);

    /* 2. The body begins with the field name, so a match would start exactly at
          the first body byte.  The whole name must lie inside the header.  */
    expect_not_found("body starts with field",
                     "POST /f HTTP/1.1\r\nHost: h\r\nContent-Length: 30\r\n\r\n"
                     "Transfer-Encoding: chunked\r\npad",
                     "Transfer-Encoding", 17);

    /* 3. The field is absent everywhere.  A body containing a CRLF must not be
          mistaken for a field value.  */
    expect_not_found("field absent, body has CRLF",
                     "POST /f HTTP/1.1\r\nHost: h\r\nContent-Length: 30\r\n\r\n"
                     "AAAAAAAAAAAAAAAAAAAAAAAA\r\nBBBB",
                     "Transfer-Encoding", 17);

    /* 4. No header terminator in the packet, so the packet carries no body and
          all of it is header.  A field in it must still be found.  */
    expect_value("no header terminator",
                 "POST /f HTTP/1.1\r\nHost: h\r\nTransfer-Encoding: chunked\r\n",
                 "Transfer-Encoding", 17, "chunked");

    /* 5. Control: an ordinary request with the field in the header.  */
    expect_value("field in header",
                 "POST /f HTTP/1.1\r\nHost: h\r\nTransfer-Encoding: chunked\r\n\r\nbody",
                 "Transfer-Encoding", 17, "chunked");

    /* 6. A body crafted for the offset the parser used to land on when the scan
          was cut short: no Transfer-Encoding header at all, and "chunked"
          positioned so that a mis-terminated scan would return it.  */
    expect_not_found("body crafted for scan offset",
                     "POST /f HTTP/1.1\r\nHost: h\r\nContent-Length: 26\r\n\r\n"
                     "1234567890123456789chunked\r\n",
                     "Transfer-Encoding", 17);

    /* 7. The header carries the field and the body carries a decoy with a
          different value.  The header must win.  */
    expect_value("header wins over body decoy",
                 "POST /f HTTP/1.1\r\nContent-Type: text/plain\r\nContent-Length: 32\r\n\r\n"
                 "Content-Type: application/evil\r\n",
                 "Content-Type", 12, "text/plain");

    if (error_counter)
    {
        printf("\nERROR!\n");
        test_control_return(1);
    }
    else
    {
        printf("SUCCESS!\n");
        test_control_return(0);
    }
}

#else

extern void test_control_return(UINT status);

#ifdef CTEST
VOID test_application_define(void *first_unused_memory)
#else
void netx_web_header_boundary_test_application_define(void *first_unused_memory)
#endif
{

    printf("NetX Test:   Web Header Boundary Test.................................N/A\n");

    test_control_return(3);
}
#endif
