/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Codex (gpt-5.6-sol).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

// Some portions generated by Codex (gpt-5.6-sol).

#include "tls_test_frame.h"

#define TLS_TEST_EXTERNAL_SERVER_READY_ATTEMPTS           30U
#define TLS_TEST_EXTERNAL_SERVER_READY_OUTPUT_SIZE         1U

/* Stop and reap an external server process.  */
static INT tls_test_external_server_cleanup( TLS_TEST_EXTERNAL_TEST_PROCESS* test_process_ptr)
{
INT exit_status;
INT kill_status;
INT wait_status;

    kill_status = tls_test_kill_external_test_process( test_process_ptr);
    wait_status = tls_test_wait_external_test_process( test_process_ptr, &exit_status);
    if (TLS_TEST_SUCCESS != wait_status)
    {
        return wait_status;
    }
    if ((TLS_TEST_SUCCESS != kill_status) && (0 == exit_status))
    {
        return kill_status;
    }

    return TLS_TEST_SUCCESS;
}

/* Wait until an external server is listening on the requested port.  */
static INT tls_test_external_server_wait_until_ready( CHAR* port, UINT protocol)
{
CHAR* socket_option;
CHAR* external_cmd[] = { "ss", "-H", NULL, "sport", "=", port, (CHAR*)NULL};
CHAR output[TLS_TEST_EXTERNAL_SERVER_READY_OUTPUT_SIZE];
ULONG output_length;
UINT attempt;
INT exit_status;
INT status;

    if (TLS_TEST_EXTERNAL_SERVER_TCP == protocol)
    {
        socket_option = "-ltn";
    }
    else if (TLS_TEST_EXTERNAL_SERVER_UDP == protocol)
    {
        socket_option = "-lun";
    }
    else
    {
        return TLS_TEST_UNKNOWN_TYPE_ERROR;
    }
    external_cmd[2] = socket_option;

    for (attempt = 0U; attempt < TLS_TEST_EXTERNAL_SERVER_READY_ATTEMPTS; attempt++)
    {
        output_length = (ULONG)sizeof( output);
        status = tls_test_get_external_test_process_output( &exit_status, external_cmd, output, &output_length);
        if (TLS_TEST_SUCCESS != status)
        {
            return status;
        }
        if (0 != exit_status)
        {
            return TLS_TEST_INSTANCE_EXTERNAL_PROGRAM_FAILED;
        }
        if (0U < output_length)
        {
            return TLS_TEST_SUCCESS;
        }
        (VOID)tls_test_sleep( 1U);
    }

    return TLS_TEST_INSTANCE_FAILED;
}

/* Launch an external server, notify its client when ready, and wait for it.  */
INT tls_test_launch_external_test_server( INT* exit_status_ptr, CHAR* argv[], TLS_TEST_SEMAPHORE* semaphore_ptr,
                                          CHAR* port, UINT protocol)
{
TLS_TEST_EXTERNAL_TEST_PROCESS external_test_process;
INT cleanup_status;
INT status;

    return_value_if_fail( NULL != exit_status_ptr, TLS_TEST_INVALID_POINTER);
    return_value_if_fail( NULL != argv, TLS_TEST_INVALID_POINTER);
    return_value_if_fail( NULL != semaphore_ptr, TLS_TEST_INVALID_POINTER);
    return_value_if_fail( NULL != port, TLS_TEST_INVALID_POINTER);

    status = tls_test_launch_external_test_process_in_background( &external_test_process, argv);
    return_value_if_fail( TLS_TEST_SUCCESS == status, status);

    status = tls_test_external_server_wait_until_ready( port, protocol);
    if (TLS_TEST_SUCCESS != status)
    {
        cleanup_status = tls_test_external_server_cleanup( &external_test_process);
        return_value_if_fail( TLS_TEST_SUCCESS == cleanup_status, cleanup_status);
        return status;
    }

    status = tls_test_semaphore_post( semaphore_ptr);
    if (TLS_TEST_SUCCESS != status)
    {
        cleanup_status = tls_test_external_server_cleanup( &external_test_process);
        return_value_if_fail( TLS_TEST_SUCCESS == cleanup_status, cleanup_status);
        return status;
    }

    return tls_test_wait_external_test_process( &external_test_process, exit_status_ptr);
}
