/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 * 
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 * 
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 * 
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

#include "tls_test_frame.h"

#include <execinfo.h>
#include <signal.h>

/* A test instance is a forked process, so a fault in it reaches the director
   only as a signal number.  The frames are what says which object the instance
   was in when it died, and they are gone by the time the director reaps it.
   This reports them from inside the faulting process, before the default
   disposition runs, so the answer is in the test log whether or not the
   platform retained a core.  */

/* The instance's own name, kept for the handler, which may not call anything
   that takes a lock.  */
static const CHAR *tls_test_fault_instance_name = "unknown";

/* Frame buffer, filled in the handler.  It is static because the alternate
   stack is small and the handler must not build an array of this size on it.  */
static void *tls_test_fault_frames[64];

/* Alternate stack, so a fault caused by an exhausted thread stack still
   reports.  The size is stated rather than taken from SIGSTKSZ, which is a
   call to sysconf on current glibc and so cannot size a static object.  */
static CHAR tls_test_fault_stack[32768];

/* Write a NUL-terminated string.  Only async-signal-safe calls are used here:
   the handler runs after memory has already been shown to be untrustworthy.  */
static VOID tls_test_fault_write(const CHAR *text)
{
size_t length = 0;

    while (text[length] != '\0')
    {
        length++;
    }
    (VOID)!write(STDOUT_FILENO, text, length);
}

/* Write an unsigned value as hexadecimal, widest digit first.  */
static VOID tls_test_fault_write_hex(unsigned long value)
{
CHAR   digits[] = "0123456789abcdef";
CHAR   text[2 + (sizeof(unsigned long) * 2) + 1];
UINT   index;

    text[0] = '0';
    text[1] = 'x';
    for (index = 0; index < (sizeof(unsigned long) * 2); index++)
    {
        text[2 + index] = digits[(value >> ((((sizeof(unsigned long) * 2) - 1) - index) * 4)) & 0xfU];
    }
    text[2 + (sizeof(unsigned long) * 2)] = '\0';
    tls_test_fault_write(text);
}

static VOID tls_test_fault_handler(INT signal_number, siginfo_t *info, VOID *context)
{
INT frame_count;

    NX_PARAMETER_NOT_USED(context);

    tls_test_fault_write("\nInstance ");
    tls_test_fault_write(tls_test_fault_instance_name);
    tls_test_fault_write(" faulted on signal ");
    tls_test_fault_write_hex((unsigned long)signal_number);
    tls_test_fault_write(" at address ");
    tls_test_fault_write_hex((unsigned long)(info == NULL ? NULL : info -> si_addr));
    tls_test_fault_write("\n");

    frame_count = backtrace(tls_test_fault_frames,
                            (INT)(sizeof(tls_test_fault_frames) / sizeof(tls_test_fault_frames[0])));
    backtrace_symbols_fd(tls_test_fault_frames, frame_count, STDOUT_FILENO);
    tls_test_fault_write("\n");

    /* Restore the default disposition and fault again, so the instance's exit
       status stays the signal the director already reports and counts.  */
    (VOID)signal(signal_number, SIG_DFL);
    (VOID)raise(signal_number);
}

INT tls_test_instance_install_fault_report(const CHAR *instance_name)
{
struct sigaction  fault_action;
stack_t           handler_stack;
INT               status;
UINT              index;
INT               fault_signals[] = {SIGSEGV, SIGBUS, SIGILL, SIGFPE, SIGABRT};

    if (instance_name != NULL)
    {
        tls_test_fault_instance_name = instance_name;
    }

    handler_stack.ss_sp = tls_test_fault_stack;
    handler_stack.ss_size = sizeof(tls_test_fault_stack);
    handler_stack.ss_flags = 0;
    status = sigaltstack(&handler_stack, NULL);
    return_value_if_fail(-1 != status, TLS_TEST_SYSTEM_CALL_FAILED);

    memset(&fault_action, 0, sizeof(fault_action));
    fault_action.sa_sigaction = tls_test_fault_handler;
    fault_action.sa_flags = SA_SIGINFO | SA_ONSTACK | SA_RESETHAND;
    (VOID)sigemptyset(&fault_action.sa_mask);

    for (index = 0; index < (sizeof(fault_signals) / sizeof(fault_signals[0])); index++)
    {
        status = sigaction(fault_signals[index], &fault_action, NULL);
        return_value_if_fail(-1 != status, TLS_TEST_SYSTEM_CALL_FAILED);
    }

    return TLS_TEST_SUCCESS;
}
