# This is a basic workflow that is manually triggered

name: azure_iot_test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Azure_IoT"
  Azure_IoT:

    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Checkout submodules
      run: |
        if (!(Test-Path ./test/cmake/threadx)) {git clone https://github.com/azure-rtos/threadx.git ./test/cmake/threadx --depth 1}

    - name: CMake
      run: |
        mkdir build
        cd build
        cmake ../test/cmake/azure_iot -A Win32

    - name: Build
      run: |
        cd build
        cmake --build .