/***************************************************************************/
/* Copyright (c) 2024 Microsoft Corporation                                */
/* Copyright (c) 2026 Eclipse ThreadX contributors                         */
/*                                                                         */
/* This program and the accompanying materials are made available under    */
/* the terms of the MIT License which is available at                      */
/* https://opensource.org/licenses/MIT.                                    */
/*                                                                         */
/* SPDX-License-Identifier: MIT                                            */
/***************************************************************************/

// Some portions generated by Codex (gpt-5.6-sol).

#include <stdio.h>

#include "nx_secure_tls_api.h"
#include "nx_crypto.h"
#include "tls_test_utility.h"
#include "nx_secure_tls_test_init_functions.h"

extern void    test_control_return(UINT status);

static NX_SECURE_TLS_SESSION   client_tls_session;
static NX_PACKET_POOL          pool_0;
#define NX_PACKET_POOL_BYTES  ((128 + sizeof(NX_PACKET)) * 3)
void NX_Secure_TLS_verify_mac_coverage();

/* Test cases all taken from RFC 4231. Relevant section numbers included in comments. */

#ifdef CTEST
void test_application_define(void *first_unused_memory);
void test_application_define(void *first_unused_memory)
#else
void nx_secure_tls_verify_mac_test_application_define(void *first_unused_memory)
#endif
{

    CHAR* pointer;
    UINT       status;

    pointer = (CHAR*)first_unused_memory;


    status = nx_packet_pool_create(&pool_0, "NetX Main Packet Pool", 128, pointer, NX_PACKET_POOL_BYTES);

    /* Print out test information banner.  */
    printf("NetX Secure Test:   TLS verify mac Test................................");


    NX_Secure_TLS_verify_mac_coverage();

    printf("SUCCESS!\n");
    test_control_return(0);

}
extern NX_CRYPTO_METHOD crypto_method_sha256;
extern NX_SECURE_TLS_CRYPTO nx_crypto_tls_ciphers;
extern NX_SECURE_TLS_CIPHERSUITE_INFO _nx_crypto_ciphersuite_lookup_table[];

#define TEST_HASH_SIZE 4

static UINT test_crypto_operation(UINT op,       /* Encrypt, Decrypt, Authenticate */
                                  VOID *handler, /* Crypto handler */
                                  struct NX_CRYPTO_METHOD_STRUCT *method,
                                  UCHAR *key,
                                  NX_CRYPTO_KEY_SIZE key_size_in_bits,
                                  UCHAR *input,
                                  ULONG input_length_in_byte,
                                  UCHAR *iv_ptr,
                                  UCHAR *output,
                                  ULONG output_length_in_byte,
                                  VOID *crypto_metadata,
                                  ULONG crypto_metadata_size,
                                  VOID *packet_ptr,
                                  VOID (*nx_crypto_hw_process_callback)(VOID *packet_ptr, UINT status))
{
    if (op == NX_CRYPTO_HASH_CALCULATE)
    {
        memset(output, 0xA5, TEST_HASH_SIZE);
    }

    return(NX_CRYPTO_SUCCESS);
}

TEST(NX_Secure_TLS, verify_mac_coverage)
{
UINT status;
UINT length = 0;
NX_PACKET *send_packet;
NX_PACKET *receive_packet;
UCHAR receive_buffer[10];
UCHAR test_hash[TEST_HASH_SIZE];
UCHAR test_secret[TEST_HASH_SIZE] = {0};
NX_CRYPTO_METHOD test_hash_method = {0};
NX_SECURE_TLS_CIPHERSUITE_INFO test_ciphersuite;



    
    nx_packet_allocate(&pool_0, &send_packet, 0, NX_WAIT_FOREVER);

    /* Invalid hash size. */
    length = 0;

    nx_secure_tls_test_init_functions(&client_tls_session);

    /* Test Line 102 */
    client_tls_session.nx_secure_tls_session_ciphersuite = NX_NULL;
    status = _nx_secure_tls_verify_mac(&client_tls_session, receive_buffer, NX_SECURE_TLS_RECORD_HEADER_SIZE,
                                       send_packet, 0, &length);
    EXPECT_EQ(NX_SECURE_TLS_UNKNOWN_CIPHERSUITE, status);

    /* Set up the correct ciphersuite and crypto table. */
#ifdef NX_SECURE_DISABLE_X509
    client_tls_session.nx_secure_tls_session_ciphersuite = &_nx_crypto_ciphersuite_lookup_table[0];
#else
    client_tls_session.nx_secure_tls_session_ciphersuite = &_nx_crypto_ciphersuite_lookup_table[3];
#endif
    client_tls_session.nx_secure_tls_crypto_table = &nx_crypto_tls_ciphers;

    /* Verify that empty application records have an authenticated MAC. */
    memcpy(&test_ciphersuite, client_tls_session.nx_secure_tls_session_ciphersuite,
           sizeof(NX_SECURE_TLS_CIPHERSUITE_INFO));
    test_hash_method.nx_crypto_operation = test_crypto_operation;
    test_ciphersuite.nx_secure_tls_hash = &test_hash_method;
    test_ciphersuite.nx_secure_tls_hash_size = TEST_HASH_SIZE;
    client_tls_session.nx_secure_tls_session_ciphersuite = &test_ciphersuite;
    client_tls_session.nx_secure_tls_key_material.nx_secure_tls_server_write_mac_secret = test_secret;

    memset(test_hash, 0xA5, sizeof(test_hash));
    status = nx_packet_data_append(send_packet, test_hash, sizeof(test_hash), &pool_0, NX_WAIT_FOREVER);
    EXPECT_EQ(NX_SUCCESS, status);

    receive_buffer[0] = NX_SECURE_TLS_APPLICATION_DATA;
    receive_buffer[1] = (UCHAR)(NX_SECURE_TLS_VERSION_TLS_1_0 >> 8);
    receive_buffer[2] = (UCHAR)(NX_SECURE_TLS_VERSION_TLS_1_0);
    receive_buffer[3] = 0;
    receive_buffer[4] = TEST_HASH_SIZE;
    length = TEST_HASH_SIZE;
    status = _nx_secure_tls_verify_mac(&client_tls_session, receive_buffer, NX_SECURE_TLS_RECORD_HEADER_SIZE,
                                       send_packet, 0, &length);
    EXPECT_EQ(NX_SUCCESS, status);
    EXPECT_EQ(0, length);
    EXPECT_EQ(1, client_tls_session.nx_secure_tls_remote_sequence_number[0]);

    /* A modified MAC on an empty application record must be rejected. */
    send_packet -> nx_packet_prepend_ptr[0] = 0;
    client_tls_session.nx_secure_tls_remote_sequence_number[0] = 0;
    length = TEST_HASH_SIZE;
    status = _nx_secure_tls_verify_mac(&client_tls_session, receive_buffer, NX_SECURE_TLS_RECORD_HEADER_SIZE,
                                       send_packet, 0, &length);
    EXPECT_EQ(NX_SECURE_TLS_HASH_MAC_VERIFY_FAILURE, status);
    EXPECT_EQ(0, length);
    send_packet -> nx_packet_prepend_ptr[0] = 0xA5;


    length = TEST_HASH_SIZE - 1;
    status = _nx_secure_tls_verify_mac(&client_tls_session, receive_buffer, NX_SECURE_TLS_RECORD_HEADER_SIZE,
                                       send_packet, 0, &length);
    EXPECT_EQ(NX_SECURE_TLS_HASH_MAC_VERIFY_FAILURE, status);

    receive_buffer[0] = 0;
    length = TEST_HASH_SIZE;
    status = _nx_secure_tls_verify_mac(&client_tls_session, receive_buffer, NX_SECURE_TLS_RECORD_HEADER_SIZE,
                                       send_packet, 0, &length);
    EXPECT_EQ(NX_SECURE_TLS_HASH_MAC_VERIFY_FAILURE, status);

    length = 0;
    status = _nx_secure_tls_verify_mac(&client_tls_session, receive_buffer, NX_SECURE_TLS_RECORD_HEADER_SIZE,
                                       send_packet, 0, &length);
    EXPECT_EQ(NX_SECURE_TLS_HASH_MAC_VERIFY_FAILURE, status);


    /* Test Line 137 */
    receive_buffer[0] = NX_SECURE_TLS_APPLICATION_DATA;
    length = TEST_HASH_SIZE;
    client_tls_session.nx_secure_tls_remote_sequence_number[0] = 0xFFFFFFFF;
    status = _nx_secure_tls_verify_mac(&client_tls_session, receive_buffer, NX_SECURE_TLS_RECORD_HEADER_SIZE,
                                       send_packet, 0, &length);
    EXPECT_EQ(NX_SUCCESS, status);

    /* Test Line 142 */
    receive_buffer[0] = NX_SECURE_TLS_APPLICATION_DATA;
    length = TEST_HASH_SIZE;
    client_tls_session.nx_secure_tls_remote_sequence_number[0] = 0xFFFFFFFF;
    client_tls_session.nx_secure_tls_remote_sequence_number[1] = 0xFFFFFFFF;
    status = _nx_secure_tls_verify_mac(&client_tls_session, receive_buffer, NX_SECURE_TLS_RECORD_HEADER_SIZE,
                                       send_packet, 0, &length);
    EXPECT_EQ(NX_NOT_SUCCESSFUL, status);
    client_tls_session.nx_secure_tls_remote_sequence_number[0] = 0;
    client_tls_session.nx_secure_tls_remote_sequence_number[1] = 0;


    /* Test line 160 */
    length = TEST_HASH_SIZE + 1;
    status = _nx_secure_tls_verify_mac(&client_tls_session, receive_buffer, 7, send_packet, 0, &length);    
    EXPECT_EQ(NX_SECURE_TLS_HASH_MAC_VERIFY_FAILURE, status);


    /* Test line 178 */
    client_tls_session.nx_secure_tls_remote_sequence_number[0] = 0xFFFFFFFF;
    status = _nx_secure_tls_verify_mac(&client_tls_session, receive_buffer, 0, send_packet, 0, &length);    
    EXPECT_EQ(NX_SECURE_TLS_PADDING_CHECK_FAILED, status);

    /* Test line 184 */
    client_tls_session.nx_secure_tls_remote_sequence_number[0] = 0xFFFFFFFF;
    client_tls_session.nx_secure_tls_remote_sequence_number[1] = 0xFFFFFFFF;
    status = _nx_secure_tls_verify_mac(&client_tls_session, receive_buffer, 0, send_packet, 0, &length);
    EXPECT_EQ(NX_NOT_SUCCESSFUL, status);
    client_tls_session.nx_secure_tls_remote_sequence_number[1] = 0;

    /* Test line 205 */
    client_tls_session.nx_secure_tls_remote_sequence_number[0] = 0;    
    status = _nx_secure_tls_verify_mac(&client_tls_session, receive_buffer, 0, send_packet, 0, &length);    
    EXPECT_EQ(NX_SECURE_TLS_PADDING_CHECK_FAILED, status);

    /* Test Line 212 */
    send_packet -> nx_packet_append_ptr = send_packet->nx_packet_prepend_ptr + 15;
    send_packet -> nx_packet_length = 15;
    length = 30;
    status = _nx_secure_tls_verify_mac(&client_tls_session, receive_buffer, 0, send_packet, 0, &length);
    EXPECT_EQ(NX_SECURE_TLS_PADDING_CHECK_FAILED, status);

}
