/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* _nx_secure_x509_asn1_tlv_block_parse() must not read the buffer it is given
   when it is told the buffer holds nothing.

   The status cannot show this. A zero length returns
   NX_SECURE_X509_ASN1_LENGTH_TOO_LONG whether or not the tag is read first,
   because the guard that returns it was always present and only the load sat
   above it. The read is the whole defect, so the test is built so that
   performing it faults: the buffer pointer is null, which the parser must
   never dereference once the length says there is nothing to parse.

   The second case is the shape that reaches this from the wire. A certificate
   too short to hold a block drives the parser to a zero remainder through
   _nx_secure_x509_certificate_parse(). It is asserted for the status alone,
   since an over-read of a static array is not observable. */

#include <stdio.h>
#include "tx_api.h"
#include "nx_api.h"
#include "nx_secure_tls_api.h"
#include "nx_secure_x509.h"
#include "tls_test_utility.h"

extern void test_control_return(UINT status);

#define DEMO_STACK_SIZE 4096

static TX_THREAD           thread_0;
static NX_SECURE_X509_CERT certificate;
static ULONG               thread_0_stack[DEMO_STACK_SIZE / sizeof(ULONG)];

/* Two bytes declare a block whose contents are absent, so the parser is called
   again with nothing left. */
static const UCHAR short_cert_der[2] = {0x30, 0x00};

static ULONG error_counter;

static void thread_0_entry(ULONG thread_input);

void test_application_define(void *first_unused_memory)
{
    error_counter = 0;
    tx_thread_create(&thread_0, "thread 0", thread_0_entry, 0,
                     thread_0_stack, sizeof(thread_0_stack),
                     16, 16, 4, TX_AUTO_START);
}

static void thread_0_entry(ULONG thread_input)
{
UINT         status;
ULONG        buffer_length;
USHORT       tlv_type;
USHORT       tlv_tag_class;
ULONG        tlv_length;
const UCHAR *tlv_data;
ULONG        header_length;

    printf("NetX Secure Test:   X.509 ASN.1 Zero Length Test.................");

    nx_system_initialize();

    /* A null buffer is safe to hand over only because the length forbids
       touching it. Reading the tag first dereferences it. */
    buffer_length = 0;
    status = _nx_secure_x509_asn1_tlv_block_parse(NX_NULL, &buffer_length,
                                                  &tlv_type, &tlv_tag_class,
                                                  &tlv_length, &tlv_data,
                                                  &header_length);
    EXPECT_EQ(NX_SECURE_X509_ASN1_LENGTH_TOO_LONG, status);

    /* The same refusal with a real buffer, so the guard is not answering the
       null pointer rather than the length. */
    buffer_length = 0;
    status = _nx_secure_x509_asn1_tlv_block_parse(short_cert_der, &buffer_length,
                                                  &tlv_type, &tlv_tag_class,
                                                  &tlv_length, &tlv_data,
                                                  &header_length);
    EXPECT_EQ(NX_SECURE_X509_ASN1_LENGTH_TOO_LONG, status);

    /* The wire-reachable shape: a certificate with no room for a block. */
    memset(&certificate, 0, sizeof(certificate));
    status = _nx_secure_x509_certificate_initialize(&certificate,
                                                    (UCHAR *)short_cert_der,
                                                    sizeof(short_cert_der),
                                                    NX_NULL, 0, NX_NULL, 0,
                                                    NX_SECURE_X509_KEY_TYPE_NONE);
    EXPECT_EQ(NX_SECURE_X509_INVALID_CERTIFICATE, status);

    if (error_counter)
    {
        printf("ERROR!\n");
        test_control_return(1);
    }
    else
    {
        printf("SUCCESS!\n");
        test_control_return(0);
    }
}
