/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Codex (GPT-Sol-6).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* Check the digest passed to ECDSA for TLS 1.0 and TLS 1.1 CertificateVerify. */

#include "nx_api.h"
#include "nx_secure_tls_api.h"
#include "tls_test_utility.h"
#include "ecc_certs.c"

extern VOID test_control_return(UINT status);

#if !defined(NX_SECURE_TLS_CLIENT_DISABLED) && !defined(NX_SECURE_TLS_SERVER_DISABLED) && \
    defined(NX_SECURE_ENABLE_ECC_CIPHERSUITE) && !defined(NX_SECURE_DISABLE_X509) && \
    (NX_SECURE_TLS_TLS_1_0_ENABLED || NX_SECURE_TLS_TLS_1_1_ENABLED)

#define THREAD_STACK_SIZE 2048
#define METADATA_SIZE     16000
#define PACKET_SIZE       256

static TX_THREAD test_thread;
static ULONG test_thread_stack[THREAD_STACK_SIZE / sizeof(ULONG)];
static NX_SECURE_TLS_SESSION test_session;
static UCHAR test_metadata[METADATA_SIZE];
static NX_SECURE_X509_CERT local_certificate;
static NX_SECURE_X509_CERT remote_certificate;
static NX_PACKET test_packet;
static UCHAR packet_data[PACKET_SIZE];
static UCHAR verify_message[3] = {0, 1, 0x30};
static UINT sign_checks;
static UINT verify_checks;

static UCHAR transcript[] = "tls10 certificate verify";
static const UCHAR transcript_sha1[20] =
{
    0xbb, 0xc7, 0x9d, 0x30, 0xd9, 0x8b, 0x02, 0xe6, 0xd9, 0x5d,
    0x8f, 0x23, 0xad, 0x21, 0x5a, 0xe2, 0xb3, 0x5b, 0xe3, 0x00
};

static NX_CRYPTO_METHOD public_cipher_method;
static NX_CRYPTO_METHOD certificate_hash_method;
static NX_SECURE_X509_CRYPTO certificate_methods[] =
{
    {NX_SECURE_TLS_X509_TYPE_ECDSA_SHA_256, &public_cipher_method, &certificate_hash_method}
};
static NX_CRYPTO_METHOD curve_method;
static const NX_CRYPTO_METHOD *curves[] = {&curve_method};
static USHORT groups[] = {19};
extern const NX_SECURE_TLS_CRYPTO nx_crypto_tls_ciphers;

/* Accept an EC curve selection and check that signing and verification use SHA-1. */
static UINT test_crypto_operation(UINT op, VOID *handler, struct NX_CRYPTO_METHOD_STRUCT *method,
                                  UCHAR *key, NX_CRYPTO_KEY_SIZE key_size_in_bits, UCHAR *input,
                                  ULONG input_length_in_byte, UCHAR *iv_ptr, UCHAR *output,
                                  ULONG output_length_in_byte, VOID *crypto_metadata,
                                  ULONG crypto_metadata_size, VOID *packet_ptr,
                                  VOID (*nx_crypto_hw_process_callback)(VOID *packet_ptr, UINT status))
{
NX_CRYPTO_EXTENDED_OUTPUT signature;

    NX_PARAMETER_NOT_USED(handler);
    NX_PARAMETER_NOT_USED(method);
    NX_PARAMETER_NOT_USED(key);
    NX_PARAMETER_NOT_USED(key_size_in_bits);
    NX_PARAMETER_NOT_USED(iv_ptr);
    NX_PARAMETER_NOT_USED(crypto_metadata);
    NX_PARAMETER_NOT_USED(crypto_metadata_size);
    NX_PARAMETER_NOT_USED(packet_ptr);
    NX_PARAMETER_NOT_USED(nx_crypto_hw_process_callback);

    if (op == NX_CRYPTO_EC_CURVE_SET)
    {
        return(NX_CRYPTO_SUCCESS);
    }

    if ((input == NX_NULL) || (input_length_in_byte != sizeof(transcript_sha1)) ||
        (memcmp(input, transcript_sha1, sizeof(transcript_sha1)) != 0))
    {
        return(NX_CRYPTO_NOT_SUCCESSFUL);
    }

    if (op == NX_CRYPTO_AUTHENTICATE)
    {
        if ((output == NX_NULL) || (output_length_in_byte != sizeof(signature)))
        {
            return(NX_CRYPTO_NOT_SUCCESSFUL);
        }
        memcpy(&signature, output, sizeof(signature));
        if (signature.nx_crypto_extended_output_length_in_byte < 1)
        {
            return(NX_CRYPTO_NOT_SUCCESSFUL);
        }
        signature.nx_crypto_extended_output_data[0] = 0x30;
        signature.nx_crypto_extended_output_actual_size = 1;
        memcpy(output, &signature, sizeof(signature));
        sign_checks++;
        return(NX_CRYPTO_SUCCESS);
    }

    if (op == NX_CRYPTO_VERIFY)
    {
        verify_checks++;
        return(NX_CRYPTO_SUCCESS);
    }

    return(NX_CRYPTO_NOT_SUCCESSFUL);
}

/* Prepare the certificate store and handshake transcript for one protocol version. */
static VOID test_session_setup(USHORT version)
{
UINT status;

    status = nx_secure_tls_session_create(&test_session, &nx_crypto_tls_ciphers,
                                          test_metadata, sizeof(test_metadata));
    EXPECT_EQ(NX_SUCCESS, status);

    status = nx_secure_x509_certificate_initialize(&local_certificate,
                                                    ECTestServer9_192_der, sizeof(ECTestServer9_192_der),
                                                    NX_NULL, 0, ECTestServer9_192_key_der,
                                                    sizeof(ECTestServer9_192_key_der), NX_SECURE_X509_KEY_TYPE_EC_DER);
    EXPECT_EQ(NX_SUCCESS, status);
    status = nx_secure_x509_certificate_initialize(&remote_certificate,
                                                    ECTestServer9_192_der, sizeof(ECTestServer9_192_der),
                                                    NX_NULL, 0, NX_NULL, 0, NX_SECURE_X509_KEY_TYPE_NONE);
    EXPECT_EQ(NX_SUCCESS, status);

    local_certificate.nx_secure_x509_cipher_table = certificate_methods;
    local_certificate.nx_secure_x509_cipher_table_size = 1;
    local_certificate.nx_secure_x509_certificate_is_identity_cert = NX_TRUE;
    remote_certificate.nx_secure_x509_cipher_table = certificate_methods;
    remote_certificate.nx_secure_x509_cipher_table_size = 1;

    status = _nx_secure_x509_store_certificate_add(&local_certificate,
        &test_session.nx_secure_tls_credentials.nx_secure_tls_certificate_store,
        NX_SECURE_X509_CERT_LOCATION_LOCAL);
    EXPECT_EQ(NX_SUCCESS, status);
    status = _nx_secure_x509_store_certificate_add(&remote_certificate,
        &test_session.nx_secure_tls_credentials.nx_secure_tls_certificate_store,
        NX_SECURE_X509_CERT_LOCATION_REMOTE);
    EXPECT_EQ(NX_SUCCESS, status);

    test_session.nx_secure_tls_protocol_version = version;
    test_session.nx_secure_tls_ecc.nx_secure_tls_ecc_supported_groups_count = 1;
    test_session.nx_secure_tls_ecc.nx_secure_tls_ecc_supported_groups = groups;
    test_session.nx_secure_tls_ecc.nx_secure_tls_ecc_curves = curves;

    status = _nx_secure_tls_handshake_hash_init(&test_session);
    EXPECT_EQ(NX_SUCCESS, status);
    status = _nx_secure_tls_handshake_hash_update(&test_session, transcript,
                                                  sizeof(transcript) - 1);
    EXPECT_EQ(NX_SUCCESS, status);
}

/* Check both directions of CertificateVerify with the selected legacy version. */
static VOID test_version(USHORT version)
{
UINT status;

    test_session_setup(version);
    memset(&test_packet, 0, sizeof(test_packet));
    test_packet.nx_packet_data_start = packet_data;
    test_packet.nx_packet_prepend_ptr = packet_data;
    test_packet.nx_packet_append_ptr = packet_data;
    test_packet.nx_packet_data_end = packet_data + sizeof(packet_data);

    status = _nx_secure_tls_process_certificate_verify(&test_session, verify_message,
                                                        sizeof(verify_message));
    EXPECT_EQ(NX_SUCCESS, status);
    status = _nx_secure_tls_send_certificate_verify(&test_session, &test_packet);
    EXPECT_EQ(NX_SECURE_TLS_SUCCESS, status);
    status = nx_secure_tls_session_delete(&test_session);
    EXPECT_EQ(NX_SUCCESS, status);
}

/* Run the TLS 1.0 and TLS 1.1 cases when each version is enabled. */
static VOID test_thread_entry(ULONG thread_input)
{
    NX_PARAMETER_NOT_USED(thread_input);

    printf("NetX Secure Test:   TLS Legacy ECDSA Certificate Verify Test..............");
    public_cipher_method.nx_crypto_operation = test_crypto_operation;

#if (NX_SECURE_TLS_TLS_1_0_ENABLED)
    test_version(NX_SECURE_TLS_VERSION_TLS_1_0);
#endif
#if (NX_SECURE_TLS_TLS_1_1_ENABLED)
    test_version(NX_SECURE_TLS_VERSION_TLS_1_1);
#endif

    EXPECT_EQ((UINT)(NX_SECURE_TLS_TLS_1_0_ENABLED + NX_SECURE_TLS_TLS_1_1_ENABLED), sign_checks);
    EXPECT_EQ((UINT)(NX_SECURE_TLS_TLS_1_0_ENABLED + NX_SECURE_TLS_TLS_1_1_ENABLED), verify_checks);
    printf("SUCCESS!\n");
    test_control_return(0);
}

#ifdef CTEST
void test_application_define(void *first_unused_memory);
void test_application_define(void *first_unused_memory)
#else
VOID nx_secure_tls_legacy_ecdsa_certificate_verify_test_application_define(void *first_unused_memory)
#endif
{
    NX_PARAMETER_NOT_USED(first_unused_memory);
    tx_thread_create(&test_thread, "test thread", test_thread_entry, 0,
                     test_thread_stack, sizeof(test_thread_stack),
                     7, 7, TX_NO_TIME_SLICE, TX_AUTO_START);
}

#else

#ifdef CTEST
void test_application_define(void *first_unused_memory);
void test_application_define(void *first_unused_memory)
#else
VOID nx_secure_tls_legacy_ecdsa_certificate_verify_test_application_define(void *first_unused_memory)
#endif
{
    NX_PARAMETER_NOT_USED(first_unused_memory);
    printf("NetX Secure Test:   TLS Legacy ECDSA Certificate Verify Test..............N/A\n");
    test_control_return(3);
}

#endif
