/***************************************************************************/
/* Copyright (c) 2024 Microsoft Corporation                                */
/* Copyright (c) 2026 Eclipse ThreadX contributors                         */
/*                                                                         */
/* This program and the accompanying materials are made available under    */
/* the terms of the MIT License which is available at                      */
/* https://opensource.org/licenses/MIT.                                    */
/*                                                                         */
/* SPDX-License-Identifier: MIT                                            */
/***************************************************************************/

// Some portions generated by Claude (Opus 5).

/* Regression test for TLS 1.3 client authentication with an RSA certificate.

   RFC 8446 section 4.4.3 forbids RSASSA-PKCS1-v1_5 in CertificateVerify, so a
   client holding an RSA certificate has to sign with RSASSA-PSS. This test
   covers the two functions that make that work:

     _nx_secure_tls_process_certificate_request() has to answer a TLS 1.3
     CertificateRequest by selecting rsa_pss_rsae_sha256 for an RSA local
     certificate -- and only when the server actually offered it.

     _nx_secure_tls_send_certificate_verify() has to emit the SignatureScheme
     on the wire and sign the RFC 8446 section 4.4.3 content with PSS.

   The signature is not inspected structurally: the test applies the
   certificate's own public key to it and runs the result through
   _nx_crypto_rsa_pss_verify() against the content the client was supposed to
   sign, which is what a peer does. All three rsae schemes are exercised.

   The two sides are driven directly rather than over a socket. A NetX Duo
   server never offers rsa_pss_rsae_sha256 in its own CertificateRequest --
   nx_secure_tls_send_certificate_request.c derives the list from the
   configured ECC curves -- so a NetX-to-NetX handshake cannot reach this path,
   and a full handshake test would need the server side extended first. */

#include "nx_api.h"
#include "nx_secure_tls_api.h"
#include "nx_crypto_rsa.h"
#include "tls_test_utility.h"
#include "test_device_cert.c"

extern VOID test_control_return(UINT status);

#if !defined(NX_SECURE_TLS_CLIENT_DISABLED) && !defined(NX_SECURE_DISABLE_X509) && \
    defined(NX_SECURE_ENABLE_ECC_CIPHERSUITE) && (NX_SECURE_TLS_TLS_1_3_ENABLED)

#define THREAD_STACK_SIZE           2048
#define METADATA_SIZE               16000
#define NX_PACKET_POOL_SIZE         ((1536 + sizeof(NX_PACKET)) * 8)

/* Content signed for CertificateVerify: 64 octets of 0x20, the 33-byte context
   string, its 0-byte separator, then the transcript hash (RFC 8446 4.4.3). */
#define CONTENT_PREFIX_LENGTH       (64u + 34u)
#define TRANSCRIPT_HASH_LENGTH      32u

/* Larger than any modulus _nx_secure_tls_send_certificate_verify can buffer, so
   the certificate check in front of the signature paths has to reject it. */
#define OVERSIZED_MODULUS_LENGTH    1024

static TX_THREAD                thread_0;
static ULONG                    thread_0_stack[THREAD_STACK_SIZE / sizeof(ULONG)];
static UCHAR                    tls_session_metadata[METADATA_SIZE];
static NX_PACKET_POOL           pool_0;
static ULONG                    packet_pool_area[NX_PACKET_POOL_SIZE / sizeof(ULONG) + 64 / sizeof(ULONG)];

extern const NX_SECURE_TLS_CRYPTO nx_crypto_tls_ciphers_ecc;
extern NX_CRYPTO_METHOD           crypto_method_sha256;
extern NX_CRYPTO_METHOD           crypto_method_sha384;
extern NX_CRYPTO_METHOD           crypto_method_sha512;

/* Software RSA, used to apply the certificate's public key to the signature. */
static NX_CRYPTO_METHOD verify_method_rsa =
{
    NX_CRYPTO_KEY_EXCHANGE_RSA,               /* RSA crypto algorithm                   */
    0,                                        /* Key size in bits                       */
    0,                                        /* IV size in bits                        */
    0,                                        /* ICV size in bits, not used.            */
    0,                                        /* Block size in bytes.                   */
    sizeof(NX_CRYPTO_RSA),                    /* Metadata size in bytes                 */
    _nx_crypto_method_rsa_init,               /* RSA initialization routine.            */
    NX_CRYPTO_NULL,                           /* RSA cleanup routine, not used.         */
    _nx_crypto_method_rsa_operation           /* RSA operation                          */
};

static NX_CRYPTO_RSA            rsa_ctx;
static UCHAR                    recovered_em[600];
static UCHAR                    signed_content[CONTENT_PREFIX_LENGTH + TRANSCRIPT_HASH_LENGTH];
static UCHAR                    content_hash[64];
static UCHAR                    verify_hash_metadata[1500];
static UCHAR                    verify_scratch[600];
static UCHAR                    last_signature[600];
static UCHAR                    first_signature[600];

/* A TLS 1.3 CertificateRequest carrying a signature_algorithms extension:

     00                certificate_request_context, empty
     00 0e             extensions, 14 bytes
       00 0d           signature_algorithms
       00 0a           10 bytes
         00 08         supported_signature_algorithms, 8 bytes
         ....          four SignatureScheme code points                */
static UCHAR certificate_request_with_pss[] =
{
    0x00,
    0x00, 0x0e,
    0x00, 0x0d,
    0x00, 0x0a,
    0x00, 0x08,
    0x04, 0x03,          /* ecdsa_secp256r1_sha256 */
    0x08, 0x04,          /* rsa_pss_rsae_sha256    */
    0x05, 0x03,          /* ecdsa_secp384r1_sha384 */
    0x08, 0x06           /* rsa_pss_rsae_sha512    */
};

/* The same message with every RSASSA-PSS scheme removed. */
static UCHAR certificate_request_without_pss[] =
{
    0x00,
    0x00, 0x0e,
    0x00, 0x0d,
    0x00, 0x0a,
    0x00, 0x08,
    0x04, 0x03,          /* ecdsa_secp256r1_sha256 */
    0x05, 0x03,          /* ecdsa_secp384r1_sha384 */
    0x06, 0x03,          /* ecdsa_secp521r1_sha512 */
    0x04, 0x01           /* rsa_pkcs1_sha256       */
};

/* Rebuild the content the client signs and reduce it with the signature
   scheme's hash, giving the mHash that the PSS encoding commits to. */
static VOID build_content_hash(const UCHAR *transcript_hash,
                               const NX_CRYPTO_METHOD *hash_method,
                               UCHAR *output)
{
UINT   status;
VOID  *handler = NX_CRYPTO_NULL;

    memset(&signed_content[0], 0x20, 64);
    memcpy(&signed_content[64], "TLS 1.3, client CertificateVerify", 33);
    signed_content[64 + 33] = 0x00;
    memcpy(&signed_content[CONTENT_PREFIX_LENGTH], transcript_hash, TRANSCRIPT_HASH_LENGTH);

    if (hash_method -> nx_crypto_init)
    {
        status = hash_method -> nx_crypto_init((NX_CRYPTO_METHOD *)hash_method, NX_CRYPTO_NULL, 0,
                                               &handler, verify_hash_metadata,
                                               sizeof(verify_hash_metadata));
        EXPECT_EQ(NX_CRYPTO_SUCCESS, status);
    }

    status = hash_method -> nx_crypto_operation(NX_CRYPTO_HASH_INITIALIZE, handler,
                                                (NX_CRYPTO_METHOD *)hash_method, NX_CRYPTO_NULL, 0,
                                                NX_CRYPTO_NULL, 0, NX_CRYPTO_NULL,
                                                NX_CRYPTO_NULL, 0,
                                                verify_hash_metadata, sizeof(verify_hash_metadata),
                                                NX_CRYPTO_NULL, NX_CRYPTO_NULL);
    EXPECT_EQ(NX_CRYPTO_SUCCESS, status);

    status = hash_method -> nx_crypto_operation(NX_CRYPTO_HASH_UPDATE, handler,
                                                (NX_CRYPTO_METHOD *)hash_method, NX_CRYPTO_NULL, 0,
                                                signed_content, sizeof(signed_content), NX_CRYPTO_NULL,
                                                NX_CRYPTO_NULL, 0,
                                                verify_hash_metadata, sizeof(verify_hash_metadata),
                                                NX_CRYPTO_NULL, NX_CRYPTO_NULL);
    EXPECT_EQ(NX_CRYPTO_SUCCESS, status);

    status = hash_method -> nx_crypto_operation(NX_CRYPTO_HASH_CALCULATE, handler,
                                                (NX_CRYPTO_METHOD *)hash_method, NX_CRYPTO_NULL, 0,
                                                NX_CRYPTO_NULL, 0, NX_CRYPTO_NULL,
                                                output, 64,
                                                verify_hash_metadata, sizeof(verify_hash_metadata),
                                                NX_CRYPTO_NULL, NX_CRYPTO_NULL);
    EXPECT_EQ(NX_CRYPTO_SUCCESS, status);
}

/* Drive one CertificateVerify and check it the way a peer would. */
static VOID check_certificate_verify(NX_SECURE_TLS_SESSION *tls_session,
                                     NX_SECURE_X509_CERT *certificate,
                                     UINT signature_scheme,
                                     const NX_CRYPTO_METHOD *hash_method,
                                     UINT hash_length)
{
UINT       status;
UINT       modulus_length;
NX_PACKET *packet;
UCHAR     *body;

    modulus_length = certificate -> nx_secure_x509_public_key.rsa_public_key.nx_secure_rsa_public_modulus_length;
    EXPECT_TRUE(modulus_length <= sizeof(last_signature));

    status = nx_packet_allocate(&pool_0, &packet, NX_TCP_PACKET, NX_WAIT_FOREVER);
    EXPECT_EQ(NX_SUCCESS, status);

    body = packet -> nx_packet_append_ptr;
    EXPECT_EQ(signature_scheme, tls_session -> nx_secure_tls_signature_algorithm);

    status = _nx_secure_tls_send_certificate_verify(tls_session, packet);
    EXPECT_EQ(NX_SECURE_TLS_SUCCESS, status);

    /* SignatureScheme, then the signature length, then the signature itself. */
    EXPECT_EQ((UCHAR)(signature_scheme >> 8), body[0]);
    EXPECT_EQ((UCHAR)(signature_scheme & 0xFF), body[1]);
    EXPECT_EQ((UCHAR)(modulus_length >> 8), body[2]);
    EXPECT_EQ((UCHAR)(modulus_length & 0xFF), body[3]);
    EXPECT_EQ(4 + modulus_length, packet -> nx_packet_length);

    /* Apply the public key to recover the encoded message. */
    status = verify_method_rsa.nx_crypto_init(&verify_method_rsa,
                                              (UCHAR *)certificate -> nx_secure_x509_public_key.rsa_public_key.nx_secure_rsa_public_modulus,
                                              (NX_CRYPTO_KEY_SIZE)(modulus_length << 3),
                                              NX_CRYPTO_NULL, &rsa_ctx, sizeof(rsa_ctx));
    EXPECT_EQ(NX_CRYPTO_SUCCESS, status);

    status = verify_method_rsa.nx_crypto_operation(NX_CRYPTO_ENCRYPT, NX_CRYPTO_NULL,
                                                   &verify_method_rsa,
                                                   (UCHAR *)certificate -> nx_secure_x509_public_key.rsa_public_key.nx_secure_rsa_public_exponent,
                                                   (NX_CRYPTO_KEY_SIZE)(certificate -> nx_secure_x509_public_key.rsa_public_key.nx_secure_rsa_public_exponent_length << 3),
                                                   &body[4], modulus_length, NX_CRYPTO_NULL,
                                                   recovered_em, sizeof(recovered_em),
                                                   &rsa_ctx, sizeof(rsa_ctx),
                                                   NX_CRYPTO_NULL, NX_CRYPTO_NULL);
    EXPECT_EQ(NX_CRYPTO_SUCCESS, status);

    /* The encoding must commit to exactly the content RFC 8446 4.4.3 defines. */
    build_content_hash(tls_session -> nx_secure_tls_key_material.nx_secure_tls_transcript_hashes[NX_SECURE_TLS_TRANSCRIPT_IDX_CERTIFICATE],
                       hash_method, content_hash);

    status = _nx_crypto_rsa_pss_verify(content_hash, hash_length,
                                       recovered_em, (modulus_length << 3) - 1u,
                                       hash_method,
                                       verify_hash_metadata, sizeof(verify_hash_metadata),
                                       verify_scratch, sizeof(verify_scratch));
    EXPECT_EQ(NX_CRYPTO_SUCCESS, status);

    memcpy(last_signature, &body[4], modulus_length);

    /* And it must not verify against a different transcript. */
    content_hash[0] = (UCHAR)(content_hash[0] ^ 0x01u);
    status = _nx_crypto_rsa_pss_verify(content_hash, hash_length,
                                       recovered_em, (modulus_length << 3) - 1u,
                                       hash_method,
                                       verify_hash_metadata, sizeof(verify_hash_metadata),
                                       verify_scratch, sizeof(verify_scratch));
    EXPECT_EQ(NX_CRYPTO_NOT_SUCCESSFUL, status);

    nx_packet_release(packet);
}

static VOID ntest_0_entry(ULONG thread_input)
{
UINT   status;
UINT   saved_modulus_length;
NX_SECURE_TLS_SESSION tls_session;
NX_SECURE_X509_CERT   local_certificate;
const NX_SECURE_TLS_CIPHERSUITE_INFO *ciphersuite;
USHORT priority;
NX_PACKET *packet;

    printf("NetX Secure Test:   TLS 1.3 RSA Client Authentication Test.............");

    nx_system_initialize();

    status = nx_packet_pool_create(&pool_0, "NetX Main Packet Pool", 1536,
                                   (ULONG *)(((int)packet_pool_area + 64) & ~63), NX_PACKET_POOL_SIZE);
    EXPECT_EQ(NX_SUCCESS, status);

    status = nx_secure_tls_session_create(&tls_session, &nx_crypto_tls_ciphers_ecc,
                                          tls_session_metadata, sizeof(tls_session_metadata));
    EXPECT_EQ(NX_SUCCESS, status);

    memset(&local_certificate, 0, sizeof(local_certificate));
    status = nx_secure_x509_certificate_initialize(&local_certificate,
                                                   test_device_cert_der, test_device_cert_der_len,
                                                   NX_NULL, 0,
                                                   test_device_cert_key_der, test_device_cert_key_der_len,
                                                   NX_SECURE_X509_KEY_TYPE_RSA_PKCS1_DER);
    EXPECT_EQ(NX_SUCCESS, status);

    /* This also hands the certificate its cipher table and metadata area. */
    status = nx_secure_tls_local_certificate_add(&tls_session, &local_certificate);
    EXPECT_EQ(NX_SUCCESS, status);

    EXPECT_EQ(NX_SECURE_TLS_X509_TYPE_RSA, local_certificate.nx_secure_x509_public_algorithm);

    /* A negotiated TLS 1.3 session: the record-layer version stays at TLS 1.2. */
    tls_session.nx_secure_tls_1_3 = 1;
    tls_session.nx_secure_tls_protocol_version = NX_SECURE_TLS_VERSION_TLS_1_2;
    tls_session.nx_secure_tls_socket_type = NX_SECURE_TLS_SESSION_TYPE_CLIENT;

    status = _nx_secure_tls_ciphersuite_lookup(&tls_session, TLS_AES_128_GCM_SHA256,
                                               &ciphersuite, &priority);
    EXPECT_EQ(NX_SUCCESS, status);
    tls_session.nx_secure_tls_session_ciphersuite = ciphersuite;

    memset(tls_session.nx_secure_tls_key_material.nx_secure_tls_transcript_hashes[NX_SECURE_TLS_TRANSCRIPT_IDX_CERTIFICATE],
           0x5A, TRANSCRIPT_HASH_LENGTH);

    /* ---- CertificateRequest: an RSA certificate selects rsa_pss_rsae_sha256. ---- */

    tls_session.nx_secure_tls_signature_algorithm = 0;
    status = _nx_secure_tls_process_certificate_request(&tls_session,
                                                        certificate_request_with_pss,
                                                        sizeof(certificate_request_with_pss));
    EXPECT_EQ(NX_SUCCESS, status);
    EXPECT_EQ(NX_SECURE_TLS_SIGNATURE_RSA_PSS_RSAE_SHA256,
              tls_session.nx_secure_tls_signature_algorithm);
    EXPECT_EQ(NX_SECURE_TLS_CLIENT_STATE_CERTIFICATE_REQUEST, tls_session.nx_secure_tls_client_state);

    /* A server that does not offer it must be refused, not signed for anyway. */
    tls_session.nx_secure_tls_signature_algorithm = 0;
    status = _nx_secure_tls_process_certificate_request(&tls_session,
                                                        certificate_request_without_pss,
                                                        sizeof(certificate_request_without_pss));
    EXPECT_EQ(NX_SECURE_TLS_UNSUPPORTED_CERT_SIGN_ALG, status);
    EXPECT_EQ(0, tls_session.nx_secure_tls_signature_algorithm);

    /* ---- CertificateVerify: a PSS signature a peer can verify. ---- */

    /* Restore what the accepted CertificateRequest selected, and sign with that
       rather than with a value set by hand: this is the client's own choice
       travelling from one function to the other.

       A successful verification below is also what fails if the PKCS#1 v1.5
       padding loop in _nx_secure_tls_send_certificate_verify ever runs for TLS
       1.3 again - it would overwrite the PSS encoding with 0xFF bytes. */
    tls_session.nx_secure_tls_signature_algorithm = 0;
    status = _nx_secure_tls_process_certificate_request(&tls_session,
                                                        certificate_request_with_pss,
                                                        sizeof(certificate_request_with_pss));
    EXPECT_EQ(NX_SUCCESS, status);

    check_certificate_verify(&tls_session, &local_certificate,
                             NX_SECURE_TLS_SIGNATURE_RSA_PSS_RSAE_SHA256,
                             &crypto_method_sha256, 32);
    memcpy(first_signature, last_signature,
           local_certificate.nx_secure_x509_public_key.rsa_public_key.nx_secure_rsa_public_modulus_length);

    /* Same content, same key, same scheme: PSS draws a fresh salt every time, so
       the two signatures must differ and both must verify. A constant salt, or a
       generator that never advances, shows up here. */
    check_certificate_verify(&tls_session, &local_certificate,
                             NX_SECURE_TLS_SIGNATURE_RSA_PSS_RSAE_SHA256,
                             &crypto_method_sha256, 32);
    EXPECT_TRUE(memcmp(first_signature, last_signature,
                       local_certificate.nx_secure_x509_public_key.rsa_public_key.nx_secure_rsa_public_modulus_length) != 0);

    tls_session.nx_secure_tls_signature_algorithm = NX_SECURE_TLS_SIGNATURE_RSA_PSS_RSAE_SHA384;
    check_certificate_verify(&tls_session, &local_certificate,
                             NX_SECURE_TLS_SIGNATURE_RSA_PSS_RSAE_SHA384,
                             &crypto_method_sha384, 48);

    tls_session.nx_secure_tls_signature_algorithm = NX_SECURE_TLS_SIGNATURE_RSA_PSS_RSAE_SHA512;
    check_certificate_verify(&tls_session, &local_certificate,
                             NX_SECURE_TLS_SIGNATURE_RSA_PSS_RSAE_SHA512,
                             &crypto_method_sha512, 64);

    /* An unknown SignatureScheme is rejected before anything is signed. */
    status = nx_packet_allocate(&pool_0, &packet, NX_TCP_PACKET, NX_WAIT_FOREVER);
    EXPECT_EQ(NX_SUCCESS, status);
    tls_session.nx_secure_tls_signature_algorithm = NX_SECURE_TLS_SIGNATURE_RSA_SHA256;
    status = _nx_secure_tls_send_certificate_verify(&tls_session, packet);
    EXPECT_EQ(NX_SECURE_TLS_UNSUPPORTED_CERT_SIGN_ALG, status);
    EXPECT_EQ(0, packet -> nx_packet_length);
    nx_packet_release(packet);

    /* A modulus larger than the signing buffers is rejected as an invalid
       certificate rather than overrunning them. */
    status = nx_packet_allocate(&pool_0, &packet, NX_TCP_PACKET, NX_WAIT_FOREVER);
    EXPECT_EQ(NX_SUCCESS, status);
    saved_modulus_length = local_certificate.nx_secure_x509_public_key.rsa_public_key.nx_secure_rsa_public_modulus_length;
    local_certificate.nx_secure_x509_public_key.rsa_public_key.nx_secure_rsa_public_modulus_length = OVERSIZED_MODULUS_LENGTH;
    tls_session.nx_secure_tls_signature_algorithm = NX_SECURE_TLS_SIGNATURE_RSA_PSS_RSAE_SHA256;
    status = _nx_secure_tls_send_certificate_verify(&tls_session, packet);
    EXPECT_EQ(NX_SECURE_TLS_INVALID_CERTIFICATE, status);
    EXPECT_EQ(0, packet -> nx_packet_length);
    local_certificate.nx_secure_x509_public_key.rsa_public_key.nx_secure_rsa_public_modulus_length = (USHORT)saved_modulus_length;
    nx_packet_release(packet);

    nx_secure_tls_session_delete(&tls_session);
    nx_packet_pool_delete(&pool_0);

    printf("SUCCESS!\n");
    test_control_return(0);
}

#ifdef CTEST
void test_application_define(void *first_unused_memory);
void test_application_define(void *first_unused_memory)
#else
VOID nx_secure_tls_1_3_rsa_client_auth_test_application_define(void *first_unused_memory)
#endif
{
    tx_thread_create(&thread_0, "thread 0", ntest_0_entry, 0,
                     thread_0_stack, sizeof(thread_0_stack),
                     7, 7, TX_NO_TIME_SLICE, TX_AUTO_START);
}

#else
#ifdef CTEST
void test_application_define(void *first_unused_memory);
void test_application_define(void *first_unused_memory)
#else
VOID nx_secure_tls_1_3_rsa_client_auth_test_application_define(void *first_unused_memory)
#endif
{
    printf("NetX Secure Test:   TLS 1.3 RSA Client Authentication Test.............N/A\n");
    test_control_return(3);
}
#endif
