/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Codex (GPT-Sol-6).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* Check ownership of decrypted TLS 1.3 post-handshake packets. */

#include "nx_api.h"
#include "nx_secure_tls_api.h"
#include "nx_secure_tls.h"

extern VOID test_control_return(UINT status);

#if (NX_SECURE_TLS_TLS_1_3_ENABLED)

#define TEST_PACKET_SIZE 256
#define TEST_PACKET_COUNT 8
#define TEST_POOL_SIZE (TEST_PACKET_COUNT * (TEST_PACKET_SIZE + sizeof(NX_PACKET)))
#define TEST_STACK_SIZE 2048

static TX_THREAD test_thread;
static ULONG test_thread_stack[TEST_STACK_SIZE / sizeof(ULONG)];
static NX_PACKET_POOL test_pool;
static ULONG test_pool_memory[TEST_POOL_SIZE / sizeof(ULONG)];
static NX_SECURE_TLS_SESSION test_session;
static NX_SECURE_TLS_CIPHERSUITE_INFO test_ciphersuite;
static NX_CRYPTO_METHOD test_cipher;
static UCHAR test_record_buffer[64];
static UCHAR test_iv[12];

/* Copy a synthetic plaintext record through the decryption interface. */
static UINT test_crypto_operation(UINT operation, VOID *handler,
                                  NX_CRYPTO_METHOD *method, UCHAR *key,
                                  NX_CRYPTO_KEY_SIZE key_size_in_bits,
                                  UCHAR *input, ULONG input_length,
                                  UCHAR *iv, UCHAR *output,
                                  ULONG output_length, VOID *metadata,
                                  ULONG metadata_size, VOID *packet,
                                  VOID (*callback)(VOID *packet, UINT status))
{
ULONG i;

    NX_PARAMETER_NOT_USED(handler);
    NX_PARAMETER_NOT_USED(method);
    NX_PARAMETER_NOT_USED(key);
    NX_PARAMETER_NOT_USED(key_size_in_bits);
    NX_PARAMETER_NOT_USED(iv);
    NX_PARAMETER_NOT_USED(metadata);
    NX_PARAMETER_NOT_USED(metadata_size);
    NX_PARAMETER_NOT_USED(packet);
    NX_PARAMETER_NOT_USED(callback);

    if (operation == NX_CRYPTO_DECRYPT_UPDATE)
    {
        if ((input == NX_NULL) || (output == NX_NULL) ||
            (input_length > output_length))
        {
            return(NX_CRYPTO_PTR_ERROR);
        }
        for (i = 0; i < input_length; i++)
        {
            output[i] = input[i];
        }
    }
    return(NX_CRYPTO_SUCCESS);
}

/* Queue one encrypted TLS record with the given inner content type. */
static UINT test_queue_record(UCHAR inner_type)
{
NX_PACKET *packet;
UCHAR record[26] = {NX_SECURE_TLS_APPLICATION_DATA, 0x03, 0x03,
                    0x00, 0x15, 0x04, 0x00, 0x00, 0x00, 0x00};
UINT status;

    record[9] = inner_type;
    status = nx_packet_allocate(&test_pool, &packet, NX_TCP_PACKET, NX_NO_WAIT);
    if (status == NX_SUCCESS)
    {
        status = nx_packet_data_append(packet, record, sizeof(record),
                                       &test_pool, NX_NO_WAIT);
        if (status == NX_SUCCESS)
        {
            test_session.nx_secure_record_queue_header = packet;
        }
        else
        {
            nx_packet_release(packet);
        }
    }
    return(status);
}

/* Verify that a post-handshake packet stays owned by the TLS session. */
static VOID test_thread_entry(ULONG thread_input)
{
NX_PACKET *received = NX_NULL;
ULONG available;
UINT status;

    NX_PARAMETER_NOT_USED(thread_input);
    printf("NetX Secure Test:   TLS 1.3 Post-Handshake Packet Test.................");

    nx_system_initialize();
    status = nx_packet_pool_create(&test_pool, "TLS packet pool", TEST_PACKET_SIZE,
                                   test_pool_memory, TEST_POOL_SIZE);
    if (status == NX_SUCCESS)
    {
        nx_secure_tls_initialize();
        available = test_pool.nx_packet_pool_available;

        test_cipher.nx_crypto_algorithm = NX_CRYPTO_ENCRYPTION_AES_GCM_16;
        test_cipher.nx_crypto_block_size_in_bytes = 1;
        test_cipher.nx_crypto_ICV_size_in_bits = 128;
        test_cipher.nx_crypto_operation = test_crypto_operation;
        test_ciphersuite.nx_secure_tls_session_cipher = &test_cipher;
        test_session.nx_secure_tls_session_ciphersuite = &test_ciphersuite;
        test_session.nx_secure_tls_packet_pool = &test_pool;
        test_session.nx_secure_tls_packet_buffer = test_record_buffer;
        test_session.nx_secure_tls_packet_buffer_size = sizeof(test_record_buffer);
        test_session.nx_secure_tls_socket_type = NX_SECURE_TLS_SESSION_TYPE_CLIENT;
        test_session.nx_secure_tls_client_state = NX_SECURE_TLS_CLIENT_STATE_HANDSHAKE_FINISHED;
        /* TLS 1.3 records use the TLS 1.2 legacy record version. */
        test_session.nx_secure_tls_protocol_version = NX_SECURE_TLS_VERSION_TLS_1_2;
        test_session.nx_secure_tls_1_3 = NX_TRUE;
        test_session.nx_secure_tls_remote_session_active = NX_TRUE;
        test_session.nx_secure_tls_key_material.nx_secure_tls_server_iv = test_iv;

        status = test_queue_record(NX_SECURE_TLS_HANDSHAKE);
        if (status == NX_SUCCESS)
        {
            status = _nx_secure_tls_session_receive_records(&test_session, &received,
                                                            NX_NO_WAIT);
            if ((status != NX_SECURE_TLS_POST_HANDSHAKE_RECEIVED) ||
                (received != NX_NULL) ||
                (test_session.nx_secure_record_decrypted_packet == NX_NULL))
            {
                status = NX_NOT_SUCCESSFUL;
            }
        }
        if (status == NX_SECURE_TLS_POST_HANDSHAKE_RECEIVED)
        {
            status = test_queue_record(NX_SECURE_TLS_APPLICATION_DATA);
            if (status == NX_SUCCESS)
            {
                status = _nx_secure_tls_session_receive_records(&test_session,
                                                                &received, NX_NO_WAIT);
                if ((status != NX_SUCCESS) || (received == NX_NULL) ||
                    (test_session.nx_secure_record_decrypted_packet != NX_NULL))
                {
                    status = NX_NOT_SUCCESSFUL;
                }
            }
        }
        if (received != NX_NULL)
        {
            nx_packet_release(received);
        }
        if ((status == NX_SUCCESS) &&
            (test_pool.nx_packet_pool_available != available))
        {
            status = NX_NOT_SUCCESSFUL;
        }
    }

    if (status == NX_SUCCESS)
    {
        printf("SUCCESS!\n");
        test_control_return(0);
    }
    else
    {
        printf("ERROR: 0x%x\n", status);
        test_control_return(1);
    }
}

/* Start the packet ownership test in a ThreadX thread. */
#ifdef CTEST
void test_application_define(void *first_unused_memory);
void test_application_define(void *first_unused_memory)
#else
VOID nx_secure_tls_1_3_post_handshake_packet_test_application_define(VOID *first_unused_memory)
#endif
{
    NX_PARAMETER_NOT_USED(first_unused_memory);
    tx_thread_create(&test_thread, "TLS packet test", test_thread_entry, 0,
                     test_thread_stack, sizeof(test_thread_stack),
                     1, 1, TX_NO_TIME_SLICE, TX_AUTO_START);
}

#else

/* Report that TLS 1.3 is unavailable in this build. */
#ifdef CTEST
void test_application_define(void *first_unused_memory);
void test_application_define(void *first_unused_memory)
#else
VOID nx_secure_tls_1_3_post_handshake_packet_test_application_define(VOID *first_unused_memory)
#endif
{
    NX_PARAMETER_NOT_USED(first_unused_memory);
    printf("NetX Secure Test:   TLS 1.3 Post-Handshake Packet Test.................N/A\n");
    test_control_return(3);
}

#endif
