/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5.5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* This test checks that _nx_secure_tls_send_record does not touch a packet chain once
   nx_tcp_socket_send has accepted it.

   The server sends one application record that spans several packets and more than one MSS. TCP
   sends the leading segments from copies, trims the original chain down to the last segment and
   queues it until the peer acknowledges it, at which point the IP thread releases it. Queued or
   released, the chain keeps its links and data pointers, so the test can still read it afterwards.
   Under NX_SECURE_KEY_CLEAR, a wipe after a successful send zeroes the bytes those pointers
   describe, which on a busy system belong to whichever thread has reallocated the packets.

   The chain comes from a pool that only the server's sends allocate from, so nothing else can
   reallocate those packets before they are inspected. */

#include   "nx_api.h"
#include   "nx_packet.h"
#include   "nx_secure_tls_api.h"
#include   "test_ca_cert.c"
#include   "test_device_cert.c"

extern VOID    test_control_return(UINT status);

#if !defined(NX_SECURE_TLS_CLIENT_DISABLED) && !defined(NX_SECURE_TLS_SERVER_DISABLED) && \
    !defined(NX_SECURE_DISABLE_X509) && !defined(NX_DISABLE_PACKET_CHAIN)

#define NUM_PACKETS                 24
#define PACKET_SIZE                 1536
#define PACKET_POOL_SIZE            (NUM_PACKETS * (PACKET_SIZE + sizeof(NX_PACKET)))
#define SEND_NUM_PACKETS            12
#define SEND_POOL_SIZE              (SEND_NUM_PACKETS * (PACKET_SIZE + sizeof(NX_PACKET)))
#define THREAD_STACK_SIZE           1024
#define ARP_CACHE_SIZE              1024
#define METADATA_SIZE               16000
#define CERT_BUFFER_SIZE            2048
#define SERVER_PORT                 4433

/* Two full packets and part of a third, and more than twice the MSS of the 1500-byte driver. */
#define MESSAGE_SIZE                3500

static TX_THREAD                thread_0;
static TX_THREAD                thread_1;
static NX_PACKET_POOL           pool_0;
static NX_PACKET_POOL           send_pool;
static NX_IP                    ip_0;
static UINT                     error_counter;

static NX_TCP_SOCKET            client_socket_0;
static NX_TCP_SOCKET            server_socket_0;
static NX_SECURE_TLS_SESSION    tls_client_session_0;
static NX_SECURE_TLS_SESSION    tls_server_session_0;
static NX_SECURE_X509_CERT      client_trusted_ca;
static NX_SECURE_X509_CERT      client_remote_cert;
static NX_SECURE_X509_CERT      server_local_certificate;

static ULONG                    pool_0_memory[PACKET_POOL_SIZE / sizeof(ULONG)];
static ULONG                    send_pool_memory[SEND_POOL_SIZE / sizeof(ULONG)];
static ULONG                    thread_0_stack[THREAD_STACK_SIZE / sizeof(ULONG)];
static ULONG                    thread_1_stack[THREAD_STACK_SIZE / sizeof(ULONG)];
static ULONG                    ip_0_stack[THREAD_STACK_SIZE / sizeof(ULONG)];
static ULONG                    arp_cache[ARP_CACHE_SIZE];
static UCHAR                    client_metadata[METADATA_SIZE];
static UCHAR                    server_metadata[METADATA_SIZE];
static UCHAR                    client_cert_buffer[CERT_BUFFER_SIZE];
static UCHAR                    tls_packet_buffer[2][4000];

static UCHAR                    message[MESSAGE_SIZE];
static UCHAR                    received[MESSAGE_SIZE];

extern const NX_SECURE_TLS_CRYPTO nx_crypto_tls_ciphers;

static VOID    ntest_0_entry(ULONG thread_input);
static VOID    ntest_1_entry(ULONG thread_input);
extern VOID    _nx_ram_network_driver_1500(struct NX_IP_DRIVER_STRUCT *driver_req);

#define ERROR_COUNTER(status) _ERROR_COUNTER(status, __FILE__, __LINE__)

static VOID    _ERROR_COUNTER(UINT status, const char *file, int line)
{
    printf("Error (status = 0x%x) at %s:%d\n", status, file, line);
    error_counter++;
}

#ifdef CTEST
void test_application_define(void *first_unused_memory);
void test_application_define(void *first_unused_memory)
#else
VOID    nx_secure_tls_send_record_key_clear_test_application_define(void *first_unused_memory)
#endif
{
UINT     status;

    NX_PARAMETER_NOT_USED(first_unused_memory);

    error_counter = 0;

    /* Create the server thread.  */
    tx_thread_create(&thread_0, "thread 0", ntest_0_entry, 0,
                     thread_0_stack, sizeof(thread_0_stack),
                     7, 7, TX_NO_TIME_SLICE, TX_AUTO_START);

    /* Create the client thread.  */
    tx_thread_create(&thread_1, "thread 1", ntest_1_entry, 0,
                     thread_1_stack, sizeof(thread_1_stack),
                     8, 8, TX_NO_TIME_SLICE, TX_AUTO_START);

    nx_system_initialize();

    /* The IP instance and the loopback path allocate from pool_0; only the server's sends allocate
       from send_pool. */
    status =  nx_packet_pool_create(&pool_0, "NetX Main Packet Pool", PACKET_SIZE,
                                    pool_0_memory, PACKET_POOL_SIZE);
    if (status)
    {
        ERROR_COUNTER(status);
    }

    status =  nx_packet_pool_create(&send_pool, "Server Send Pool", PACKET_SIZE,
                                    send_pool_memory, SEND_POOL_SIZE);
    if (status)
    {
        ERROR_COUNTER(status);
    }

    status = nx_ip_create(&ip_0, "NetX IP Instance 0", IP_ADDRESS(1, 2, 3, 4), 0xFFFFFF00UL,
                          &pool_0, _nx_ram_network_driver_1500,
                          ip_0_stack, sizeof(ip_0_stack), 1);
    if (status)
    {
        ERROR_COUNTER(status);
    }

    status =  nx_arp_enable(&ip_0, (VOID *)arp_cache, sizeof(arp_cache));
    if (status)
    {
        ERROR_COUNTER(status);
    }

    status =  nx_tcp_enable(&ip_0);
    if (status)
    {
        ERROR_COUNTER(status);
    }

    nx_secure_tls_initialize();
}

static VOID client_tls_setup(NX_SECURE_TLS_SESSION *tls_session_ptr)
{
UINT status;

    status = nx_secure_tls_session_create(tls_session_ptr, &nx_crypto_tls_ciphers,
                                          client_metadata, sizeof(client_metadata));
    if (status)
    {
        ERROR_COUNTER(status);
    }

    memset(&client_remote_cert, 0, sizeof(client_remote_cert));
    status = nx_secure_tls_remote_certificate_allocate(tls_session_ptr, &client_remote_cert,
                                                       client_cert_buffer, sizeof(client_cert_buffer));
    if (status)
    {
        ERROR_COUNTER(status);
    }

    status = nx_secure_x509_certificate_initialize(&client_trusted_ca, test_ca_cert_der,
                                                   test_ca_cert_der_len, NX_NULL, 0, NX_NULL, 0,
                                                   NX_SECURE_X509_KEY_TYPE_NONE);
    if (status)
    {
        ERROR_COUNTER(status);
    }

    status = nx_secure_tls_trusted_certificate_add(tls_session_ptr, &client_trusted_ca);
    if (status)
    {
        ERROR_COUNTER(status);
    }

    status = nx_secure_tls_session_packet_buffer_set(tls_session_ptr, tls_packet_buffer[0],
                                                     sizeof(tls_packet_buffer[0]));
    if (status)
    {
        ERROR_COUNTER(status);
    }
}

static VOID server_tls_setup(NX_SECURE_TLS_SESSION *tls_session_ptr)
{
UINT status;

    status = nx_secure_tls_session_create(tls_session_ptr, &nx_crypto_tls_ciphers,
                                          server_metadata, sizeof(server_metadata));
    if (status)
    {
        ERROR_COUNTER(status);
    }

    memset(&server_local_certificate, 0, sizeof(server_local_certificate));
    status = nx_secure_x509_certificate_initialize(&server_local_certificate,
                                                   test_device_cert_der, test_device_cert_der_len,
                                                   NX_NULL, 0, test_device_cert_key_der,
                                                   test_device_cert_key_der_len,
                                                   NX_SECURE_X509_KEY_TYPE_RSA_PKCS1_DER);
    if (status)
    {
        ERROR_COUNTER(status);
    }

    status = nx_secure_tls_local_certificate_add(tls_session_ptr, &server_local_certificate);
    if (status)
    {
        ERROR_COUNTER(status);
    }

    status = nx_secure_tls_session_packet_buffer_set(tls_session_ptr, tls_packet_buffer[1],
                                                     sizeof(tls_packet_buffer[1]));
    if (status)
    {
        ERROR_COUNTER(status);
    }
}

static void ntest_0_entry(ULONG thread_input)
{
UINT       status;
UINT       chain_length;
ULONG      stale_bytes;
ULONG      nonzero_bytes;
UCHAR     *byte_ptr;
NX_PACKET *packet_ptr;
NX_PACKET *current_packet;

    NX_PARAMETER_NOT_USED(thread_input);

    printf("NetX Secure Test:   TLS Send Record Key Clear Test.....................");

    status = nx_tcp_socket_create(&ip_0, &server_socket_0, "Server socket", NX_IP_NORMAL,
                                  NX_DONT_FRAGMENT, NX_IP_TIME_TO_LIVE, 8192, NX_NULL, NX_NULL);
    if (status)
    {
        ERROR_COUNTER(status);
    }

    status = nx_tcp_server_socket_listen(&ip_0, SERVER_PORT, &server_socket_0, 5, NX_NULL);
    if (status)
    {
        ERROR_COUNTER(status);
    }

    server_tls_setup(&tls_server_session_0);

    status = nx_tcp_server_socket_accept(&server_socket_0, NX_WAIT_FOREVER);
    if (status)
    {
        ERROR_COUNTER(status);
    }

    status = nx_secure_tls_session_start(&tls_server_session_0, &server_socket_0, NX_WAIT_FOREVER);
    if (status)
    {
        ERROR_COUNTER(status);
    }

    status = nx_secure_tls_packet_allocate(&tls_server_session_0, &send_pool, &packet_ptr, NX_NO_WAIT);
    if (status)
    {
        ERROR_COUNTER(status);
    }

    status = nx_packet_data_append(packet_ptr, message, sizeof(message), &send_pool, NX_NO_WAIT);
    if (status)
    {
        ERROR_COUNTER(status);
    }

    chain_length = 0;
    for (current_packet = packet_ptr; current_packet != NX_NULL;
         current_packet = current_packet -> nx_packet_next)
    {
        chain_length++;
    }

    /* The record must span several packets, as in the case that exposed the defect. */
    if (chain_length < 3)
    {
        ERROR_COUNTER(chain_length);
    }

    status = nx_secure_tls_session_send(&tls_server_session_0, packet_ptr, NX_IP_PERIODIC_RATE);
    if (status)
    {
        ERROR_COUNTER(status);
    }

    /* TCP must have queued or released the chain, or the check below proves nothing. */
    if (packet_ptr -> nx_packet_union_next.nx_packet_tcp_queue_next == (NX_PACKET *)NX_PACKET_ALLOCATED)
    {
        ERROR_COUNTER(NX_NOT_SUCCESSFUL);
    }

    /* The chain still describes the last segment: its headers and the tail of the encrypted
       record. That cannot be all zeros. A wipe after the send would have cleared exactly these
       bytes. */
    stale_bytes = 0;
    nonzero_bytes = 0;
    for (current_packet = packet_ptr; current_packet != NX_NULL;
         current_packet = current_packet -> nx_packet_next)
    {
        for (byte_ptr = current_packet -> nx_packet_prepend_ptr;
             byte_ptr < current_packet -> nx_packet_append_ptr; byte_ptr++)
        {
            stale_bytes++;
            if (*byte_ptr != 0)
            {
                nonzero_bytes++;
            }
        }
    }

    if ((stale_bytes == 0) || (nonzero_bytes == 0))
    {
        ERROR_COUNTER(NX_NOT_SUCCESSFUL);
    }

    /* Wait for the client to receive and check the record, and for TCP to release its
       acknowledged copies. */
    tx_thread_sleep(NX_IP_PERIODIC_RATE);

    /* Every packet taken from send_pool, including TCP's copies, has been returned. The
       session end below allocates its alert from send_pool, so check before it. */
    if (send_pool.nx_packet_pool_available != send_pool.nx_packet_pool_total)
    {
        ERROR_COUNTER(send_pool.nx_packet_pool_available);
    }

    nx_secure_tls_session_end(&tls_server_session_0, NX_NO_WAIT);
    nx_secure_tls_session_delete(&tls_server_session_0);

    nx_tcp_socket_disconnect(&server_socket_0, NX_NO_WAIT);
    nx_tcp_server_socket_unaccept(&server_socket_0);
    nx_tcp_server_socket_unlisten(&ip_0, SERVER_PORT);

    if (error_counter)
    {
        printf("ERROR!\n");
        test_control_return(1);
    }
    else
    {
        printf("SUCCESS!\n");
        test_control_return(0);
    }
}

static void ntest_1_entry(ULONG thread_input)
{
UINT        i;
UINT        status;
ULONG       received_length;
ULONG       fragment_length;
NX_PACKET  *packet_ptr;
NXD_ADDRESS server_address;

    NX_PARAMETER_NOT_USED(thread_input);

    for (i = 0; i < sizeof(message); i++)
    {
        message[i] = (UCHAR)(i + 1);
    }

    server_address.nxd_ip_version = NX_IP_VERSION_V4;
    server_address.nxd_ip_address.v4 = IP_ADDRESS(127, 0, 0, 1);

    status = nx_tcp_socket_create(&ip_0, &client_socket_0, "Client socket", NX_IP_NORMAL,
                                  NX_DONT_FRAGMENT, NX_IP_TIME_TO_LIVE, 8192, NX_NULL, NX_NULL);
    if (status)
    {
        ERROR_COUNTER(status);
    }

    status = nx_tcp_client_socket_bind(&client_socket_0, NX_ANY_PORT, NX_NO_WAIT);
    if (status)
    {
        ERROR_COUNTER(status);
    }

    client_tls_setup(&tls_client_session_0);

    status = nxd_tcp_client_socket_connect(&client_socket_0, &server_address, SERVER_PORT,
                                           NX_WAIT_FOREVER);
    if (status)
    {
        ERROR_COUNTER(status);
    }

    status = nx_secure_tls_session_start(&tls_client_session_0, &client_socket_0, NX_WAIT_FOREVER);
    if (status)
    {
        ERROR_COUNTER(status);
    }

    /* The record arrives intact: the wipe, if any, only ever touched the released chain. */
    received_length = 0;
    while (received_length < sizeof(received))
    {
        status = nx_secure_tls_session_receive(&tls_client_session_0, &packet_ptr, NX_IP_PERIODIC_RATE);
        if (status)
        {
            ERROR_COUNTER(status);
            break;
        }

        status = nx_packet_data_extract_offset(packet_ptr, 0, &received[received_length],
                                               sizeof(received) - received_length, &fragment_length);
        nx_packet_release(packet_ptr);
        if (status)
        {
            ERROR_COUNTER(status);
            break;
        }

        received_length += fragment_length;
    }

    if ((received_length != sizeof(message)) || memcmp(message, received, sizeof(message)))
    {
        ERROR_COUNTER(NX_NOT_SUCCESSFUL);
    }

    nx_secure_tls_session_end(&tls_client_session_0, NX_NO_WAIT);
    nx_secure_tls_session_delete(&tls_client_session_0);

    nx_tcp_socket_disconnect(&client_socket_0, NX_NO_WAIT);
    nx_tcp_client_socket_unbind(&client_socket_0);
    nx_tcp_socket_delete(&client_socket_0);
}
#else
#ifdef CTEST
void test_application_define(void *first_unused_memory);
void test_application_define(void *first_unused_memory)
#else
VOID    nx_secure_tls_send_record_key_clear_test_application_define(void *first_unused_memory)
#endif
{

    printf("NetX Secure Test:   TLS Send Record Key Clear Test.....................N/A\n");
    test_control_return(3);
}
#endif
