/***************************************************************************/
/* Copyright (c) 2024 Microsoft Corporation                                */
/* Copyright (c) 2026 Eclipse ThreadX contributors                         */
/*                                                                         */
/* This program and the accompanying materials are made available under    */
/* the terms of the MIT License which is available at                      */
/* https://opensource.org/licenses/MIT.                                    */
/*                                                                         */
/* SPDX-License-Identifier: MIT                                            */
/***************************************************************************/

// Some portions generated by Claude (Opus 5).

/* Regression test for the RSASSA-PSS primitives in nx_crypto_rsa.c:
   _nx_crypto_rsa_pss_sign(), _nx_crypto_rsa_pss_verify() and the MGF1 helper
   they share. These implement EMSA-PSS-ENCODE and EMSA-PSS-VERIFY from
   RFC 8017 section 9.1, with the salt length pinned to the hash length as
   RFC 8446 section 4.2.3 requires for TLS 1.3.

   The signing side generates its salt internally, so its output is not
   reproducible and cannot be compared against a stored vector directly. This
   test gets byte-exactness anyway by recovering the salt from the encoded
   message the function produced and re-encoding with an independent
   EMSA-PSS-ENCODE written here from the RFC (ref_pss_encode below). That
   reference encoder is not taken on trust: it has to reproduce, byte for byte,
   encoded messages recovered from real OpenSSL signatures before it is used to
   judge anything.

   Vector provenance:
     - pss_sha256_* and pss_sha512_* are RSASSA-PSS signatures produced by
       OpenSSL 3.3.2 over freshly generated RSA-2048 keys, with the encoded
       message recovered by applying the public key to the signature. They are
       known-answer tests for the verification path.
     - pss_boundary_* cover emLen == hLen + sLen + 2, where PS is empty. No
       OpenSSL key of the required size is involved; these come from the same
       RFC 8017 encoder, cross-checked against the OpenSSL vectors above.

   One branch stays uncovered: the failure return after NX_CRYPTO_RBG() in
   _nx_crypto_rsa_pss_sign(). NX_CRYPTO_RBG is a macro resolved at compile
   time, so a test cannot substitute a generator that fails; reaching it needs
   a build configuration that overrides the macro. Everything else in the three
   functions is exercised, including every crypto-call failure return, which
   section 7 reaches by failing each call the functions make, one at a time. */

#include <stdio.h>

#include "nx_crypto_rsa.h"

#ifndef NX_CRYPTO_STANDALONE_ENABLE
#include "nx_secure_tls.h"
#endif
#include "tls_test_utility.h"

/* Injected failure code, distinct from every status the code under test returns. */
#define WRAP_FAILURE                233

/* RSA-2048 in bits and bytes, and the corresponding emBits (modBits - 1). */
#define RSA_2048_MODULUS_SIZE       256
#define RSA_2048_EM_BITS            2047

/* Boundary encodings: emLen == hLen + sLen + 2 == 130 for SHA-512. 1039 leaves
   one unused bit in the leading byte, 1040 leaves none. */
#define BOUNDARY_EM_LEN             130
#define BOUNDARY_EM_BITS_PARTIAL    1039
#define BOUNDARY_EM_BITS_EXACT      1040

extern NX_CRYPTO_METHOD crypto_method_sha256;
extern NX_CRYPTO_METHOD crypto_method_sha512;

/* Software RSA method, used only to recover EM from the OpenSSL signatures. */
static NX_CRYPTO_METHOD test_crypto_method_rsa =
{
    NX_CRYPTO_KEY_EXCHANGE_RSA,               /* RSA crypto algorithm                   */
    0,                                        /* Key size in bits                       */
    0,                                        /* IV size in bits                        */
    0,                                        /* ICV size in bits, not used.            */
    0,                                        /* Block size in bytes.                   */
    sizeof(NX_CRYPTO_RSA),                    /* Metadata size in bytes                 */
    _nx_crypto_method_rsa_init,               /* RSA initialization routine.            */
    NX_CRYPTO_NULL,                           /* RSA cleanup routine, not used.         */
    _nx_crypto_method_rsa_operation           /* RSA operation                          */
};

static const UCHAR pss_public_exponent[] = {0x01, 0x00, 0x01};

static const UCHAR pss_zero8[8] = {0, 0, 0, 0, 0, 0, 0, 0};

#include "nx_secure_rsa_pss_test_data.c"

static NX_CRYPTO_RSA  rsa_ctx;
static ULONG          rsa_output[RSA_2048_MODULUS_SIZE / sizeof(ULONG)];

static UCHAR          pss_metadata[1500];
static UCHAR          ref_metadata[1500];
static UCHAR          scratch[600];
static UCHAR          em_buffer[RSA_2048_MODULUS_SIZE];
static UCHAR          ref_em[RSA_2048_MODULUS_SIZE];
static UCHAR          recovered_salt[64];

/* Failure-injection state for the wrapper method below. */
static NX_CRYPTO_METHOD wrap_method;
static UINT             wrap_call_count;
static UINT             wrap_fail_at;

#ifndef NX_CRYPTO_STANDALONE_ENABLE
static TX_THREAD thread_0;
#endif

static VOID thread_0_entry(ULONG thread_input);

#ifdef CTEST
void test_application_define(void *first_unused_memory);
void test_application_define(void *first_unused_memory)
#else
void nx_secure_rsa_pss_test_application_define(void *first_unused_memory)
#endif
{
#ifndef NX_CRYPTO_STANDALONE_ENABLE
    tx_thread_create(&thread_0, "Thread 0", thread_0_entry, 0,
                     first_unused_memory, 4096,
                     16, 16, 4, TX_AUTO_START);
#else
    thread_0_entry(0);
#endif
}

/* ------------------------------------------------------------------------ */
/* Independent RFC 8017 reference encoder.                                   */
/* ------------------------------------------------------------------------ */

/* Hash up to three concatenated segments. Drives the method the same way the
   code under test does, but keeps its own metadata so the two never share a
   context. */
static UINT ref_hash(const NX_CRYPTO_METHOD *method,
                     const UCHAR *seg1, UINT len1,
                     const UCHAR *seg2, UINT len2,
                     const UCHAR *seg3, UINT len3,
                     UCHAR *output)
{
UINT   status;
VOID  *handler = NX_CRYPTO_NULL;

    if (method -> nx_crypto_init)
    {
        status = method -> nx_crypto_init((NX_CRYPTO_METHOD *)method, NX_CRYPTO_NULL, 0,
                                          &handler, ref_metadata, sizeof(ref_metadata));
        if (status != NX_CRYPTO_SUCCESS)
        {
            return(status);
        }
    }

    status = method -> nx_crypto_operation(NX_CRYPTO_HASH_INITIALIZE, handler,
                                           (NX_CRYPTO_METHOD *)method, NX_CRYPTO_NULL, 0,
                                           NX_CRYPTO_NULL, 0, NX_CRYPTO_NULL,
                                           NX_CRYPTO_NULL, 0,
                                           ref_metadata, sizeof(ref_metadata),
                                           NX_CRYPTO_NULL, NX_CRYPTO_NULL);
    if (status != NX_CRYPTO_SUCCESS)
    {
        return(status);
    }

    if (len1 != 0)
    {
        status = method -> nx_crypto_operation(NX_CRYPTO_HASH_UPDATE, handler,
                                               (NX_CRYPTO_METHOD *)method, NX_CRYPTO_NULL, 0,
                                               (UCHAR *)seg1, len1, NX_CRYPTO_NULL,
                                               NX_CRYPTO_NULL, 0,
                                               ref_metadata, sizeof(ref_metadata),
                                               NX_CRYPTO_NULL, NX_CRYPTO_NULL);
        if (status != NX_CRYPTO_SUCCESS)
        {
            return(status);
        }
    }

    if (len2 != 0)
    {
        status = method -> nx_crypto_operation(NX_CRYPTO_HASH_UPDATE, handler,
                                               (NX_CRYPTO_METHOD *)method, NX_CRYPTO_NULL, 0,
                                               (UCHAR *)seg2, len2, NX_CRYPTO_NULL,
                                               NX_CRYPTO_NULL, 0,
                                               ref_metadata, sizeof(ref_metadata),
                                               NX_CRYPTO_NULL, NX_CRYPTO_NULL);
        if (status != NX_CRYPTO_SUCCESS)
        {
            return(status);
        }
    }

    if (len3 != 0)
    {
        status = method -> nx_crypto_operation(NX_CRYPTO_HASH_UPDATE, handler,
                                               (NX_CRYPTO_METHOD *)method, NX_CRYPTO_NULL, 0,
                                               (UCHAR *)seg3, len3, NX_CRYPTO_NULL,
                                               NX_CRYPTO_NULL, 0,
                                               ref_metadata, sizeof(ref_metadata),
                                               NX_CRYPTO_NULL, NX_CRYPTO_NULL);
        if (status != NX_CRYPTO_SUCCESS)
        {
            return(status);
        }
    }

    return(method -> nx_crypto_operation(NX_CRYPTO_HASH_CALCULATE, handler,
                                         (NX_CRYPTO_METHOD *)method, NX_CRYPTO_NULL, 0,
                                         NX_CRYPTO_NULL, 0, NX_CRYPTO_NULL,
                                         output, 64,
                                         ref_metadata, sizeof(ref_metadata),
                                         NX_CRYPTO_NULL, NX_CRYPTO_NULL));
}

/* MGF1 from RFC 8017 appendix B.2.1. */
static VOID ref_mgf1(const NX_CRYPTO_METHOD *method,
                     const UCHAR *seed, UINT seed_length,
                     UCHAR *mask, UINT mask_length)
{
UINT  hash_len = (UINT)(method -> nx_crypto_ICV_size_in_bits >> 3);
UINT  counter = 0;
UINT  offset = 0;
UINT  copy_len;
UCHAR counter_bytes[4];
UCHAR block[64];

    while (offset < mask_length)
    {
        counter_bytes[0] = (UCHAR)((counter >> 24) & 0xFFu);
        counter_bytes[1] = (UCHAR)((counter >> 16) & 0xFFu);
        counter_bytes[2] = (UCHAR)((counter >>  8) & 0xFFu);
        counter_bytes[3] = (UCHAR)( counter        & 0xFFu);

        EXPECT_EQ(NX_CRYPTO_SUCCESS, ref_hash(method, seed, seed_length,
                                              counter_bytes, 4, NX_CRYPTO_NULL, 0, block));

        copy_len = mask_length - offset;
        if (copy_len > hash_len)
        {
            copy_len = hash_len;
        }
        memcpy(&mask[offset], block, copy_len);
        offset += copy_len;
        counter++;
    }
}

/* EMSA-PSS-ENCODE from RFC 8017 section 9.1.1, with the salt supplied. */
static VOID ref_pss_encode(const NX_CRYPTO_METHOD *method,
                           const UCHAR *message_hash, UINT hash_length,
                           const UCHAR *salt, UINT salt_length,
                           UINT em_bits, UCHAR *em)
{
UINT  em_len = (em_bits + 7u) >> 3;
UINT  db_len = em_len - hash_length - 1u;
UINT  i;
UCHAR zero_bits;
UCHAR h[64];
UCHAR db[RSA_2048_MODULUS_SIZE];
UCHAR mask[RSA_2048_MODULUS_SIZE];

    EXPECT_EQ(NX_CRYPTO_SUCCESS, ref_hash(method, pss_zero8, 8, message_hash, hash_length,
                                          salt, salt_length, h));

    memset(db, 0, db_len);
    db[db_len - salt_length - 1u] = 0x01u;
    memcpy(&db[db_len - salt_length], salt, salt_length);

    ref_mgf1(method, h, hash_length, mask, db_len);

    for (i = 0; i < db_len; i++)
    {
        em[i] = (UCHAR)(db[i] ^ mask[i]);
    }

    zero_bits = (UCHAR)(8u * em_len - em_bits);
    if (zero_bits)
    {
        em[0] &= (UCHAR)(0xFFu >> zero_bits);
    }

    memcpy(&em[db_len], h, hash_length);
    em[em_len - 1u] = 0xBCu;
}

/* Undo the DB masking of an encoded message and hand back the salt it carries. */
static VOID ref_recover_salt(const NX_CRYPTO_METHOD *method, const UCHAR *em,
                             UINT hash_length, UINT salt_length, UINT em_bits,
                             UCHAR *salt)
{
UINT  em_len = (em_bits + 7u) >> 3;
UINT  db_len = em_len - hash_length - 1u;
UINT  i;
UCHAR zero_bits;
UCHAR db[RSA_2048_MODULUS_SIZE];
UCHAR mask[RSA_2048_MODULUS_SIZE];

    ref_mgf1(method, &em[db_len], hash_length, mask, db_len);

    for (i = 0; i < db_len; i++)
    {
        db[i] = (UCHAR)(em[i] ^ mask[i]);
    }

    zero_bits = (UCHAR)(8u * em_len - em_bits);
    if (zero_bits)
    {
        db[0] &= (UCHAR)(0xFFu >> zero_bits);
    }

    /* PS must be all zeros and the separator must be present, otherwise the
       encoding the signer produced is malformed and nothing below is meaningful. */
    for (i = 0; i < db_len - salt_length - 1u; i++)
    {
        EXPECT_EQ(0x00, db[i]);
    }
    EXPECT_EQ(0x01, db[db_len - salt_length - 1u]);

    memcpy(salt, &db[db_len - salt_length], salt_length);
}

/* ------------------------------------------------------------------------ */
/* Failure-injection wrapper around SHA-256.                                 */
/* ------------------------------------------------------------------------ */

static UINT wrap_init(struct NX_CRYPTO_METHOD_STRUCT *method,
                      UCHAR *key, NX_CRYPTO_KEY_SIZE key_size_in_bits,
                      VOID **handle,
                      VOID *crypto_metadata, ULONG crypto_metadata_size)
{
    wrap_call_count++;
    if (wrap_call_count == wrap_fail_at)
    {
        return(WRAP_FAILURE);
    }

    return(crypto_method_sha256.nx_crypto_init(method, key, key_size_in_bits, handle,
                                               crypto_metadata, crypto_metadata_size));
}

static UINT wrap_operation(UINT op, VOID *handler,
                           struct NX_CRYPTO_METHOD_STRUCT *method,
                           UCHAR *key, NX_CRYPTO_KEY_SIZE key_size_in_bits,
                           UCHAR *input, ULONG input_length_in_byte,
                           UCHAR *iv_ptr,
                           UCHAR *output, ULONG output_length_in_byte,
                           VOID *crypto_metadata, ULONG crypto_metadata_size,
                           VOID *packet_ptr,
                           VOID (*nx_crypto_hw_process_callback)(VOID *packet_ptr, UINT status))
{
    wrap_call_count++;
    if (wrap_call_count == wrap_fail_at)
    {
        return(WRAP_FAILURE);
    }

    return(crypto_method_sha256.nx_crypto_operation(op, handler, method, key, key_size_in_bits,
                                                    input, input_length_in_byte, iv_ptr,
                                                    output, output_length_in_byte,
                                                    crypto_metadata, crypto_metadata_size,
                                                    packet_ptr, nx_crypto_hw_process_callback));
}

/* ------------------------------------------------------------------------ */
/* Helpers used by the test body.                                            */
/* ------------------------------------------------------------------------ */

/* Apply the public key to an OpenSSL signature to recover the encoded message. */
static VOID recover_em(const UCHAR *modulus, const UCHAR *signature, UCHAR *em)
{
UINT status;

    status = test_crypto_method_rsa.nx_crypto_init(&test_crypto_method_rsa,
                                                   (UCHAR *)modulus,
                                                   RSA_2048_MODULUS_SIZE << 3,
                                                   NX_CRYPTO_NULL,
                                                   &rsa_ctx, sizeof(rsa_ctx));
    EXPECT_EQ(NX_CRYPTO_SUCCESS, status);

    status = test_crypto_method_rsa.nx_crypto_operation(NX_CRYPTO_ENCRYPT, NX_CRYPTO_NULL,
                                                        &test_crypto_method_rsa,
                                                        (UCHAR *)pss_public_exponent,
                                                        sizeof(pss_public_exponent) << 3,
                                                        (UCHAR *)signature,
                                                        RSA_2048_MODULUS_SIZE,
                                                        NX_CRYPTO_NULL,
                                                        (UCHAR *)rsa_output,
                                                        sizeof(rsa_output),
                                                        &rsa_ctx, sizeof(rsa_ctx),
                                                        NX_CRYPTO_NULL, NX_CRYPTO_NULL);
    EXPECT_EQ(NX_CRYPTO_SUCCESS, status);

    memcpy(em, (UCHAR *)rsa_output, RSA_2048_MODULUS_SIZE);
}

/* Sign, then check the result byte for byte against the reference encoder using
   the salt the signer chose, and check that verification accepts it. */
static VOID check_sign_round_trip(const NX_CRYPTO_METHOD *method, UINT hash_length,
                                  const UCHAR *message_hash, UINT em_bits)
{
UINT  status;
UINT  em_len = (em_bits + 7u) >> 3;
UINT  i;
UCHAR tampered_hash[64];

    /* Fill the whole buffer, so anything written past emLen shows up below. */
    memset(em_buffer, 0xA5, sizeof(em_buffer));
    status = _nx_crypto_rsa_pss_sign(message_hash, hash_length,
                                     em_buffer, (UINT)sizeof(em_buffer), em_bits,
                                     method, pss_metadata, sizeof(pss_metadata),
                                     scratch, sizeof(scratch));
    EXPECT_EQ(NX_CRYPTO_SUCCESS, status);

    /* Exactly emLen bytes, not one more. */
    for (i = em_len; i < (UINT)sizeof(em_buffer); i++)
    {
        EXPECT_EQ(0xA5, em_buffer[i]);
    }

    /* Byte-exact against an independent encoder fed the same salt. */
    ref_recover_salt(method, em_buffer, hash_length, hash_length, em_bits, recovered_salt);
    ref_pss_encode(method, message_hash, hash_length, recovered_salt, hash_length,
                   em_bits, ref_em);
    EXPECT_EQ(0, memcmp(em_buffer, ref_em, em_len));

    /* The trailer and the unused leading bits are part of the contract. */
    EXPECT_EQ(0xBC, em_buffer[em_len - 1u]);
    if (8u * em_len != em_bits)
    {
        EXPECT_EQ(0, em_buffer[0] & (UCHAR)(0xFFu << (8u - (8u * em_len - em_bits))));
    }

    status = _nx_crypto_rsa_pss_verify(message_hash, hash_length, em_buffer, em_bits,
                                       method, pss_metadata, sizeof(pss_metadata),
                                       scratch, sizeof(scratch));
    EXPECT_EQ(NX_CRYPTO_SUCCESS, status);

    /* A different message must not verify against this encoding. */
    memcpy(tampered_hash, message_hash, hash_length);
    tampered_hash[0] = (UCHAR)(tampered_hash[0] ^ 0x01u);
    status = _nx_crypto_rsa_pss_verify(tampered_hash, hash_length, em_buffer, em_bits,
                                       method, pss_metadata, sizeof(pss_metadata),
                                       scratch, sizeof(scratch));
    EXPECT_EQ(NX_CRYPTO_NOT_SUCCESSFUL, status);
}

/* Flip one bit of a valid encoding and require rejection. */
static VOID check_tampered_em(const NX_CRYPTO_METHOD *method, UINT hash_length,
                              const UCHAR *message_hash, const UCHAR *valid_em,
                              UINT em_bits, UINT offset, UCHAR xor_mask)
{
UINT  status;
UINT  em_len = (em_bits + 7u) >> 3;

    memcpy(em_buffer, valid_em, em_len);
    em_buffer[offset] = (UCHAR)(em_buffer[offset] ^ xor_mask);

    status = _nx_crypto_rsa_pss_verify(message_hash, hash_length, em_buffer, em_bits,
                                       method, pss_metadata, sizeof(pss_metadata),
                                       scratch, sizeof(scratch));
    EXPECT_EQ(NX_CRYPTO_NOT_SUCCESSFUL, status);
}

static VOID thread_0_entry(ULONG thread_input)
{
UINT  status;
UINT  i;
UINT  total_calls;
UINT  db_len;
UCHAR openssl_em[RSA_2048_MODULUS_SIZE];
NX_CRYPTO_METHOD broken_method;

    printf("NetX Secure Test:   RSA-PSS Test.......................................");

    /* ---- 1. Known-answer tests against OpenSSL signatures. ---- */

    recover_em(pss_sha256_modulus, pss_sha256_signature, openssl_em);
    EXPECT_EQ(0, memcmp(openssl_em, pss_sha256_em, RSA_2048_MODULUS_SIZE));

    status = _nx_crypto_rsa_pss_verify(pss_sha256_mhash, sizeof(pss_sha256_mhash),
                                       openssl_em, RSA_2048_EM_BITS,
                                       &crypto_method_sha256,
                                       pss_metadata, sizeof(pss_metadata),
                                       scratch, sizeof(scratch));
    EXPECT_EQ(NX_CRYPTO_SUCCESS, status);

    recover_em(pss_sha512_modulus, pss_sha512_signature, openssl_em);
    EXPECT_EQ(0, memcmp(openssl_em, pss_sha512_em, RSA_2048_MODULUS_SIZE));

    status = _nx_crypto_rsa_pss_verify(pss_sha512_mhash, sizeof(pss_sha512_mhash),
                                       openssl_em, RSA_2048_EM_BITS,
                                       &crypto_method_sha512,
                                       pss_metadata, sizeof(pss_metadata),
                                       scratch, sizeof(scratch));
    EXPECT_EQ(NX_CRYPTO_SUCCESS, status);

    /* The reference encoder has to reproduce OpenSSL's output from the salt
       OpenSSL used. Everything that leans on it below depends on this. */
    ref_recover_salt(&crypto_method_sha256, pss_sha256_em, sizeof(pss_sha256_mhash),
                     sizeof(pss_sha256_mhash), RSA_2048_EM_BITS, recovered_salt);
    EXPECT_EQ(0, memcmp(recovered_salt, pss_sha256_salt, sizeof(pss_sha256_salt)));
    ref_pss_encode(&crypto_method_sha256, pss_sha256_mhash, sizeof(pss_sha256_mhash),
                   pss_sha256_salt, sizeof(pss_sha256_salt), RSA_2048_EM_BITS, ref_em);
    EXPECT_EQ(0, memcmp(ref_em, pss_sha256_em, RSA_2048_MODULUS_SIZE));

    ref_pss_encode(&crypto_method_sha512, pss_sha512_mhash, sizeof(pss_sha512_mhash),
                   pss_sha512_salt, sizeof(pss_sha512_salt), RSA_2048_EM_BITS, ref_em);
    EXPECT_EQ(0, memcmp(ref_em, pss_sha512_em, RSA_2048_MODULUS_SIZE));

    /* ---- 2. Boundary encodings: emLen == hLen + sLen + 2, PS empty. ---- */

    status = _nx_crypto_rsa_pss_verify(pss_boundary_mhash, sizeof(pss_boundary_mhash),
                                       pss_boundary_em_1039, BOUNDARY_EM_BITS_PARTIAL,
                                       &crypto_method_sha512,
                                       pss_metadata, sizeof(pss_metadata),
                                       scratch, sizeof(scratch));
    EXPECT_EQ(NX_CRYPTO_SUCCESS, status);

    status = _nx_crypto_rsa_pss_verify(pss_boundary_mhash, sizeof(pss_boundary_mhash),
                                       pss_boundary_em_1040, BOUNDARY_EM_BITS_EXACT,
                                       &crypto_method_sha512,
                                       pss_metadata, sizeof(pss_metadata),
                                       scratch, sizeof(scratch));
    EXPECT_EQ(NX_CRYPTO_SUCCESS, status);

    /* Pin the reference encoder at these emBits too. The OpenSSL vectors above
       only cover emBits 2047, where one leading bit is unused and PS is long;
       these two add the empty-PS case with and without unused leading bits. */
    ref_pss_encode(&crypto_method_sha512, pss_boundary_mhash, sizeof(pss_boundary_mhash),
                   pss_boundary_salt, sizeof(pss_boundary_salt),
                   BOUNDARY_EM_BITS_PARTIAL, ref_em);
    EXPECT_EQ(0, memcmp(ref_em, pss_boundary_em_1039, BOUNDARY_EM_LEN));

    ref_pss_encode(&crypto_method_sha512, pss_boundary_mhash, sizeof(pss_boundary_mhash),
                   pss_boundary_salt, sizeof(pss_boundary_salt),
                   BOUNDARY_EM_BITS_EXACT, ref_em);
    EXPECT_EQ(0, memcmp(ref_em, pss_boundary_em_1040, BOUNDARY_EM_LEN));

    /* ---- 3. Signing: byte-exact encoding, then a sign/verify round trip. ---- */

    check_sign_round_trip(&crypto_method_sha256, 32, pss_sha256_mhash, RSA_2048_EM_BITS);
    check_sign_round_trip(&crypto_method_sha256, 32, pss_sha256_mhash, RSA_2048_EM_BITS - 7u);
    check_sign_round_trip(&crypto_method_sha512, 64, pss_sha512_mhash, RSA_2048_EM_BITS);
    check_sign_round_trip(&crypto_method_sha512, 64, pss_boundary_mhash, BOUNDARY_EM_BITS_PARTIAL);
    check_sign_round_trip(&crypto_method_sha512, 64, pss_boundary_mhash, BOUNDARY_EM_BITS_EXACT);

    /* ---- 4. Verification must reject a damaged encoding. ---- */

    db_len = RSA_2048_MODULUS_SIZE - sizeof(pss_sha256_mhash) - 1u;

    /* Trailer other than 0xBC. */
    check_tampered_em(&crypto_method_sha256, 32, pss_sha256_mhash, pss_sha256_em,
                      RSA_2048_EM_BITS, RSA_2048_MODULUS_SIZE - 1u, 0xFFu);

    /* Unused leading bits set. emBits 2047 leaves exactly one. */
    check_tampered_em(&crypto_method_sha256, 32, pss_sha256_mhash, pss_sha256_em,
                      RSA_2048_EM_BITS, 0, 0x80u);

    /* A byte of PS turned non-zero. */
    check_tampered_em(&crypto_method_sha256, 32, pss_sha256_mhash, pss_sha256_em,
                      RSA_2048_EM_BITS, 1, 0x01u);

    /* The 0x01 separator destroyed. */
    check_tampered_em(&crypto_method_sha256, 32, pss_sha256_mhash, pss_sha256_em,
                      RSA_2048_EM_BITS, db_len - sizeof(pss_sha256_mhash) - 1u, 0x01u);

    /* A salt byte changed: structure still valid, H no longer matches. */
    check_tampered_em(&crypto_method_sha256, 32, pss_sha256_mhash, pss_sha256_em,
                      RSA_2048_EM_BITS, db_len - 1u, 0x01u);

    /* ---- 5. Parameter checking. ---- */

    /* Output buffer smaller than emLen. */
    status = _nx_crypto_rsa_pss_sign(pss_sha256_mhash, 32,
                                     em_buffer, RSA_2048_MODULUS_SIZE - 1u, RSA_2048_EM_BITS,
                                     &crypto_method_sha256, pss_metadata, sizeof(pss_metadata),
                                     scratch, sizeof(scratch));
    EXPECT_EQ(NX_CRYPTO_INVALID_BUFFER_SIZE, status);

    /* emLen below hLen + sLen + 2, on both sides. */
    status = _nx_crypto_rsa_pss_sign(pss_boundary_mhash, 64,
                                     em_buffer, (UINT)sizeof(em_buffer),
                                     (BOUNDARY_EM_LEN - 1u) << 3,
                                     &crypto_method_sha512, pss_metadata, sizeof(pss_metadata),
                                     scratch, sizeof(scratch));
    EXPECT_EQ(NX_CRYPTO_NOT_SUCCESSFUL, status);

    status = _nx_crypto_rsa_pss_verify(pss_boundary_mhash, 64,
                                       pss_boundary_em_1039, (BOUNDARY_EM_LEN - 1u) << 3,
                                       &crypto_method_sha512, pss_metadata, sizeof(pss_metadata),
                                       scratch, sizeof(scratch));
    EXPECT_EQ(NX_CRYPTO_NOT_SUCCESSFUL, status);

    /* Scratch one byte short of what each side needs. */
    status = _nx_crypto_rsa_pss_sign(pss_sha256_mhash, 32,
                                     em_buffer, (UINT)sizeof(em_buffer), RSA_2048_EM_BITS,
                                     &crypto_method_sha256, pss_metadata, sizeof(pss_metadata),
                                     scratch, RSA_2048_MODULUS_SIZE - 2u);
    EXPECT_EQ(NX_CRYPTO_INVALID_BUFFER_SIZE, status);

    status = _nx_crypto_rsa_pss_verify(pss_sha256_mhash, 32,
                                       pss_sha256_em, RSA_2048_EM_BITS,
                                       &crypto_method_sha256, pss_metadata, sizeof(pss_metadata),
                                       scratch, RSA_2048_MODULUS_SIZE - 2u);
    EXPECT_EQ(NX_CRYPTO_INVALID_BUFFER_SIZE, status);

    /* Exactly enough must be accepted, or the checks are off by one in the
       direction that refuses valid input. Both sides need db_len + hLen bytes
       of scratch, and signing needs emLen bytes of output. */
    status = _nx_crypto_rsa_pss_sign(pss_sha256_mhash, 32,
                                     em_buffer, RSA_2048_MODULUS_SIZE, RSA_2048_EM_BITS,
                                     &crypto_method_sha256, pss_metadata, sizeof(pss_metadata),
                                     scratch, RSA_2048_MODULUS_SIZE - 1u);
    EXPECT_EQ(NX_CRYPTO_SUCCESS, status);

    status = _nx_crypto_rsa_pss_verify(pss_sha256_mhash, 32,
                                       pss_sha256_em, RSA_2048_EM_BITS,
                                       &crypto_method_sha256, pss_metadata, sizeof(pss_metadata),
                                       scratch, RSA_2048_MODULUS_SIZE - 1u);
    EXPECT_EQ(NX_CRYPTO_SUCCESS, status);

    /* ---- 6. MGF1 rejects a hash it cannot buffer. ---- */

    broken_method = crypto_method_sha256;
    broken_method.nx_crypto_ICV_size_in_bits = 0;
    status = _nx_crypto_rsa_pss_verify(pss_sha256_mhash, 32,
                                       pss_sha256_em, RSA_2048_EM_BITS,
                                       &broken_method, pss_metadata, sizeof(pss_metadata),
                                       scratch, sizeof(scratch));
    EXPECT_EQ(NX_CRYPTO_INVALID_BUFFER_SIZE, status);

    /* 65 bytes: one more than the MGF1 block buffer holds. */
    broken_method.nx_crypto_ICV_size_in_bits = 520;
    status = _nx_crypto_rsa_pss_verify(pss_sha256_mhash, 32,
                                       pss_sha256_em, RSA_2048_EM_BITS,
                                       &broken_method, pss_metadata, sizeof(pss_metadata),
                                       scratch, sizeof(scratch));
    EXPECT_EQ(NX_CRYPTO_INVALID_BUFFER_SIZE, status);

    /* ---- 7. Every crypto call is checked and its failure propagated. ---- */

    wrap_method = crypto_method_sha256;
    wrap_method.nx_crypto_init = wrap_init;
    wrap_method.nx_crypto_operation = wrap_operation;

    /* Count the calls a successful signature makes, then fail each in turn. */
    wrap_fail_at = 0;
    wrap_call_count = 0;
    status = _nx_crypto_rsa_pss_sign(pss_sha256_mhash, 32,
                                     em_buffer, (UINT)sizeof(em_buffer), RSA_2048_EM_BITS,
                                     &wrap_method, pss_metadata, sizeof(pss_metadata),
                                     scratch, sizeof(scratch));
    EXPECT_EQ(NX_CRYPTO_SUCCESS, status);
    total_calls = wrap_call_count;
    EXPECT_TRUE(total_calls > 0);

    for (i = 1; i <= total_calls; i++)
    {
        wrap_fail_at = i;
        wrap_call_count = 0;
        status = _nx_crypto_rsa_pss_sign(pss_sha256_mhash, 32,
                                         em_buffer, (UINT)sizeof(em_buffer), RSA_2048_EM_BITS,
                                         &wrap_method, pss_metadata, sizeof(pss_metadata),
                                         scratch, sizeof(scratch));
        EXPECT_EQ(WRAP_FAILURE, status);
    }

    /* Same sweep on the verification side. */
    wrap_fail_at = 0;
    wrap_call_count = 0;
    status = _nx_crypto_rsa_pss_verify(pss_sha256_mhash, 32,
                                       pss_sha256_em, RSA_2048_EM_BITS,
                                       &wrap_method, pss_metadata, sizeof(pss_metadata),
                                       scratch, sizeof(scratch));
    EXPECT_EQ(NX_CRYPTO_SUCCESS, status);
    total_calls = wrap_call_count;
    EXPECT_TRUE(total_calls > 0);

    for (i = 1; i <= total_calls; i++)
    {
        wrap_fail_at = i;
        wrap_call_count = 0;
        status = _nx_crypto_rsa_pss_verify(pss_sha256_mhash, 32,
                                           pss_sha256_em, RSA_2048_EM_BITS,
                                           &wrap_method, pss_metadata, sizeof(pss_metadata),
                                           scratch, sizeof(scratch));
        EXPECT_EQ(WRAP_FAILURE, status);
    }

    /* A method without an init routine: both sides must skip it and still work. */
    wrap_method.nx_crypto_init = NX_CRYPTO_NULL;
    wrap_fail_at = 0;
    wrap_call_count = 0;
    status = _nx_crypto_rsa_pss_sign(pss_sha256_mhash, 32,
                                     em_buffer, (UINT)sizeof(em_buffer), RSA_2048_EM_BITS,
                                     &wrap_method, pss_metadata, sizeof(pss_metadata),
                                     scratch, sizeof(scratch));
    EXPECT_EQ(NX_CRYPTO_SUCCESS, status);

    status = _nx_crypto_rsa_pss_verify(pss_sha256_mhash, 32, em_buffer, RSA_2048_EM_BITS,
                                       &wrap_method, pss_metadata, sizeof(pss_metadata),
                                       scratch, sizeof(scratch));
    EXPECT_EQ(NX_CRYPTO_SUCCESS, status);

    printf("SUCCESS!\n");
    test_control_return(0);
}
