/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* An RSA public key larger than NX_CRYPTO_MAX_RSA_MODULUS_SIZE must be refused
   when the certificate is parsed, and again by the RSA method if a caller
   reaches it with such a key. Both buffers it would otherwise overrun are
   fixed-size statics sized for the 4096-bit maximum. */

#include <stdio.h>
#include "tx_api.h"
#include "nx_api.h"
#include "nx_secure_tls_api.h"
#include "nx_crypto_rsa.h"
#include "tls_test_utility.h"
#include "nx_secure_x509_oversized_rsa_key_test_data.h"

extern void test_control_return(UINT status);
extern NX_SECURE_TLS_CRYPTO nx_crypto_tls_ciphers;

#define DEMO_STACK_SIZE 4096

static TX_THREAD             thread_0;
static NX_SECURE_TLS_SESSION session;
static NX_SECURE_X509_CERT   certificate;
static NX_CRYPTO_RSA         rsa_context;
static NX_CRYPTO_METHOD      rsa_method;
static UCHAR                 oversized_modulus[1024];
static CHAR                  crypto_metadata[16000];
static ULONG                 thread_0_stack[DEMO_STACK_SIZE / sizeof(ULONG)];

static ULONG error_counter;

static void thread_0_entry(ULONG thread_input);

void test_application_define(void *first_unused_memory)
{
    error_counter = 0;
    tx_thread_create(&thread_0, "thread 0", thread_0_entry, 0,
                     thread_0_stack, sizeof(thread_0_stack),
                     16, 16, 4, TX_AUTO_START);
}

static void thread_0_entry(ULONG thread_input)
{
UINT  status;
VOID *handler = NX_CRYPTO_NULL;

    printf("NetX Secure Test:   X.509 Oversized RSA Key Test.................");

    nx_system_initialize();

    status = _nx_secure_tls_session_create(&session, &nx_crypto_tls_ciphers,
                                           crypto_metadata, sizeof(crypto_metadata));
    EXPECT_EQ(NX_SUCCESS, status);

    /* An 8192-bit certificate must be rejected at parse time. Before the fix it
       parsed cleanly and its modulus reached the verification buffers. */
    memset(&certificate, 0, sizeof(certificate));
    status = _nx_secure_x509_certificate_initialize(&certificate,
                                                    (UCHAR *)oversized_cert_der,
                                                    oversized_cert_der_len,
                                                    NX_NULL, 0, NX_NULL, 0,
                                                    NX_SECURE_X509_KEY_TYPE_NONE);
    EXPECT_EQ(NX_SECURE_X509_INVALID_CERTIFICATE, status);

    /* The key must not have been recorded. */
    EXPECT_EQ(0, certificate.nx_secure_x509_public_key.rsa_public_key.nx_secure_rsa_public_modulus_length);

    /* The RSA method refuses the same key size on its own, so a caller that
       reaches it another way cannot overrun the scratch buffer either. */
    memset(oversized_modulus, 0xFF, sizeof(oversized_modulus));
    status = _nx_crypto_method_rsa_init(&rsa_method, oversized_modulus,
                                        (NX_CRYPTO_KEY_SIZE)(sizeof(oversized_modulus) << 3),
                                        &handler,
                                        (VOID *)&rsa_context, sizeof(rsa_context));
    EXPECT_EQ(NX_CRYPTO_UNSUPPORTED_KEY_SIZE, status);

    /* A key of exactly the supported maximum is still accepted. */
    status = _nx_crypto_method_rsa_init(&rsa_method, oversized_modulus,
                                        (NX_CRYPTO_KEY_SIZE)NX_CRYPTO_MAX_RSA_MODULUS_SIZE,
                                        &handler,
                                        (VOID *)&rsa_context, sizeof(rsa_context));
    EXPECT_EQ(NX_CRYPTO_SUCCESS, status);

    nx_secure_tls_session_delete(&session);

    if (error_counter)
    {
        printf("ERROR!\n");
        test_control_return(1);
    }
    else
    {
        printf("SUCCESS!\n");
        test_control_return(0);
    }
}
