/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* This test checks that two TLS sessions can build and check a CertificateVerify signature at the
   same time. The working buffers used to be file-scope statics in
   nx_secure_tls_send_certificate_verify.c and nx_secure_tls_process_certificate_verify.c, so a
   session preempted part way through resumed with another session's handshake hash: the signing side
   signed the wrong transcript and the verifying side rejected a valid peer signature. See
   eclipse-threadx/netxduo issue #430.

   Both phases preempt one session inside the CertificateVerify routine at exactly the point where
   the handshake hash has been written but not yet consumed, run a second session to completion, and
   then check the first session's result.

   The RSA method is a stand-in, so no private key is needed: on the signing side it records the
   PKCS#1 block it was handed, and on the verifying side it plays a recorded block back as the
   decrypted signature. */

#include "nx_api.h"
#include "nx_secure_tls_api.h"
#include "tls_test_utility.h"

#include "test_ca_cert.c"

extern VOID    test_control_return(UINT status);

#if !defined(NX_SECURE_DISABLE_X509) && (NX_SECURE_TLS_TLS_1_2_ENABLED)

#define THREAD_STACK_SIZE           2048
#define METADATA_SIZE               16000
#define PACKET_BUFFER_SIZE          2048
#define CAPTURE_SIZE                600

/* Capture slot for each of the two sessions that run concurrently. The thread doing the work picks
   its own slot, so the captures stay correct even when one thread preempts the other. */
#define SESSION_A                   0
#define SESSION_B                   1

/* What the stand-in RSA method should do when it is called. */
#define PHASE_SIGN                  0   /* Record the block that was handed to it. */
#define PHASE_VERIFY                1   /* Play back the block recorded during PHASE_SIGN. */

static TX_THREAD                thread_0;
static TX_THREAD                thread_1;
static ULONG                    thread_0_stack[THREAD_STACK_SIZE / sizeof(ULONG)];
static ULONG                    thread_1_stack[THREAD_STACK_SIZE / sizeof(ULONG)];

/* Signing sessions. */
static NX_SECURE_TLS_SESSION    tls_session_a;
static NX_SECURE_TLS_SESSION    tls_session_b;
static UCHAR                    metadata_a[METADATA_SIZE];
static UCHAR                    metadata_b[METADATA_SIZE];
static NX_SECURE_X509_CERT      certificate_a;
static NX_SECURE_X509_CERT      certificate_b;
static NX_PACKET                packet_a;
static NX_PACKET                packet_b;
static UCHAR                    packet_buffer_a[PACKET_BUFFER_SIZE];
static UCHAR                    packet_buffer_b[PACKET_BUFFER_SIZE];

/* Verifying sessions. They carry the same transcripts as the signing sessions above, so the blocks
   recorded during PHASE_SIGN are exactly what they must accept. */
static NX_SECURE_TLS_SESSION    tls_session_c;
static NX_SECURE_TLS_SESSION    tls_session_d;
static UCHAR                    metadata_c[METADATA_SIZE];
static UCHAR                    metadata_d[METADATA_SIZE];
static NX_SECURE_X509_CERT      certificate_c;
static NX_SECURE_X509_CERT      certificate_d;
static UCHAR                    verify_message_c[PACKET_BUFFER_SIZE];
static UCHAR                    verify_message_d[PACKET_BUFFER_SIZE];
static UINT                     verify_message_length;

/* The PKCS#1 block each session handed to the public cipher. It carries the DER prefix and the
   handshake hash, so it changes as soon as the hash is corrupted. */
static UCHAR                    captured_block[2][CAPTURE_SIZE];
static ULONG                    captured_length[2];
static UCHAR                    reference_block[2][CAPTURE_SIZE];
static ULONG                    reference_length[2];

/* Result of the work thread_1 did, checked by thread_0 once it regains control. */
static UINT                     thread_1_status;

static UINT                     error_counter;
static UINT                     crypto_phase;

/* Set while the session in thread_0 is working, so the hash stand-in preempts exactly once and at
   one known point. */
static UINT                     preemption_armed;
static UINT                     preemption_fired;

extern const NX_SECURE_TLS_CRYPTO nx_crypto_tls_ciphers;
static NX_SECURE_TLS_CRYPTO       test_ciphers;

/* Stand-in for the SHA-256 handshake hash method. Everything is delegated to the real method; the
   only addition is the preemption after the digest has been written. */
static NX_CRYPTO_METHOD           test_hash_method;
static const NX_CRYPTO_METHOD    *real_hash_method;

/* Stand-in for the RSA method, so the test needs no private key. */
static NX_CRYPTO_METHOD           test_public_cipher_method;
static NX_CRYPTO_METHOD           test_x509_hash_method;

static NX_SECURE_X509_CRYPTO      test_x509_cipher_table[] =
{
    /* OID identifier,                     public cipher,                hash method */
    {NX_SECURE_TLS_X509_TYPE_RSA_SHA_256, &test_public_cipher_method,   &test_x509_hash_method},
};

static VOID    ntest_0_entry(ULONG thread_input);
static VOID    ntest_1_entry(ULONG thread_input);


/* Return the capture slot belonging to the calling thread. */
static UINT  current_session_index(VOID)
{
    if (tx_thread_identify() == &thread_1)
    {
        return(SESSION_B);
    }

    return(SESSION_A);
}


/* PHASE_SIGN: record the block handed to the public cipher, then produce a filler output so the
   caller succeeds. PHASE_VERIFY: play the recorded block back as the decrypted signature. */
static UINT  test_public_cipher_operation(UINT op, VOID *handler,
                                          struct NX_CRYPTO_METHOD_STRUCT *method,
                                          UCHAR *key, NX_CRYPTO_KEY_SIZE key_size_in_bits,
                                          UCHAR *input, ULONG input_length_in_byte,
                                          UCHAR *iv_ptr, UCHAR *output, ULONG output_length_in_byte,
                                          VOID *crypto_metadata, ULONG crypto_metadata_size,
                                          VOID *packet_ptr,
                                          VOID (*nx_crypto_hw_process_callback)(VOID *packet_ptr, UINT status))
{
UINT index;

    NX_PARAMETER_NOT_USED(op);
    NX_PARAMETER_NOT_USED(handler);
    NX_PARAMETER_NOT_USED(method);
    NX_PARAMETER_NOT_USED(key);
    NX_PARAMETER_NOT_USED(key_size_in_bits);
    NX_PARAMETER_NOT_USED(iv_ptr);
    NX_PARAMETER_NOT_USED(crypto_metadata);
    NX_PARAMETER_NOT_USED(crypto_metadata_size);
    NX_PARAMETER_NOT_USED(packet_ptr);
    NX_PARAMETER_NOT_USED(nx_crypto_hw_process_callback);

    index = current_session_index();

    if (crypto_phase == PHASE_SIGN)
    {
        if ((input == NX_NULL) || (input_length_in_byte > CAPTURE_SIZE))
        {
            captured_length[index] = 0;
            error_counter++;
            return(NX_CRYPTO_NOT_SUCCESSFUL);
        }

        memcpy(captured_block[index], input, input_length_in_byte);
        captured_length[index] = input_length_in_byte;

        if ((output != NX_NULL) && (output_length_in_byte >= input_length_in_byte))
        {
            memset(output, 0xA5, input_length_in_byte);
        }
    }
    else
    {
        if ((output == NX_NULL) || (output_length_in_byte < reference_length[index]))
        {
            error_counter++;
            return(NX_CRYPTO_NOT_SUCCESSFUL);
        }

        memcpy(output, reference_block[index], reference_length[index]);
    }

    return(NX_CRYPTO_SUCCESS);
}


/* Delegate to the real SHA-256 method. Once the digest has been written into the CertificateVerify
   hash buffer, hand the CPU to the higher-priority thread so that the other session runs a complete
   CertificateVerify operation before this one gets to use its digest. */
static UINT  test_hash_operation(UINT op, VOID *handler,
                                 struct NX_CRYPTO_METHOD_STRUCT *method,
                                 UCHAR *key, NX_CRYPTO_KEY_SIZE key_size_in_bits,
                                 UCHAR *input, ULONG input_length_in_byte,
                                 UCHAR *iv_ptr, UCHAR *output, ULONG output_length_in_byte,
                                 VOID *crypto_metadata, ULONG crypto_metadata_size,
                                 VOID *packet_ptr,
                                 VOID (*nx_crypto_hw_process_callback)(VOID *packet_ptr, UINT status))
{
UINT status;

    NX_PARAMETER_NOT_USED(method);

    status = real_hash_method -> nx_crypto_operation(op, handler, (NX_CRYPTO_METHOD *)real_hash_method,
                                                     key, key_size_in_bits,
                                                     input, input_length_in_byte,
                                                     iv_ptr, output, output_length_in_byte,
                                                     crypto_metadata, crypto_metadata_size,
                                                     packet_ptr, nx_crypto_hw_process_callback);

    if ((status == NX_CRYPTO_SUCCESS) && (op == NX_CRYPTO_HASH_CALCULATE) &&
        (preemption_armed == NX_TRUE) && (tx_thread_identify() == &thread_0))
    {
        preemption_armed = NX_FALSE;
        preemption_fired = NX_TRUE;

        /* thread_1 runs at a higher priority, so this preempts immediately and does not return
           until thread_1 has finished its own CertificateVerify operation. */
        tx_thread_resume(&thread_1);
    }

    return(status);
}


/* Give the session what the CertificateVerify routines need: an RSA certificate in the requested
   store whose signature methods resolve to the stand-ins above, an initialized handshake hash fed
   with session-specific content, and TLS 1.2 as the negotiated version. */
static VOID  session_setup(NX_SECURE_TLS_SESSION *tls_session, UCHAR *metadata, ULONG metadata_size,
                           NX_SECURE_X509_CERT *certificate, UINT location,
                           UCHAR *transcript, UINT transcript_length)
{
UINT status;

    status = nx_secure_tls_session_create(tls_session, &test_ciphers, metadata, metadata_size);
    EXPECT_EQ(NX_SUCCESS, status);

    status = nx_secure_x509_certificate_initialize(certificate, test_ca_cert_der, test_ca_cert_der_len,
                                                   NX_NULL, 0, NX_NULL, 0, NX_SECURE_X509_KEY_TYPE_NONE);
    EXPECT_EQ(NX_SUCCESS, status);

    certificate -> nx_secure_x509_cipher_table = test_x509_cipher_table;
    certificate -> nx_secure_x509_cipher_table_size = 1;

    /* No private key is loaded because the RSA method is a stand-in, so mark the certificate as this
       device's identity by hand. That is what _nx_secure_x509_local_device_certificate_get looks
       for; it is harmless for a certificate in the remote store. */
    certificate -> nx_secure_x509_certificate_is_identity_cert = NX_TRUE;

    status = _nx_secure_x509_store_certificate_add(certificate,
                                                  &tls_session -> nx_secure_tls_credentials.nx_secure_tls_certificate_store,
                                                  location);
    EXPECT_EQ(NX_SUCCESS, status);

#if (NX_SECURE_TLS_TLS_1_3_ENABLED)
    /* Exercise the TLS 1.2 path in every build configuration. */
    tls_session -> nx_secure_tls_1_3 = NX_FALSE;
#endif
    tls_session -> nx_secure_tls_protocol_version = NX_SECURE_TLS_VERSION_TLS_1_2;

    status = _nx_secure_tls_handshake_hash_init(tls_session);
    EXPECT_EQ(NX_SUCCESS, status);

    /* Distinct transcripts, so the two sessions must produce different signature blocks. */
    status = _nx_secure_tls_handshake_hash_update(tls_session, transcript, transcript_length);
    EXPECT_EQ(NX_SUCCESS, status);
}


static VOID  packet_reset(NX_PACKET *packet, UCHAR *buffer)
{
    memset(packet, 0, sizeof(NX_PACKET));
    packet -> nx_packet_data_start = buffer;
    packet -> nx_packet_prepend_ptr = buffer;
    packet -> nx_packet_append_ptr = buffer;
    packet -> nx_packet_data_end = buffer + PACKET_BUFFER_SIZE;
    packet -> nx_packet_length = 0;
}


/* Build the CertificateVerify message body the TLS 1.2 RSA verify path expects. The signature bytes
   themselves are never looked at, because the stand-in RSA method ignores its input. */
static UINT  verify_message_build(UCHAR *buffer, UINT signature_length)
{
    memset(buffer, 0, PACKET_BUFFER_SIZE);
    buffer[0] = NX_SECURE_TLS_HASH_ALGORITHM_SHA256;
    buffer[1] = NX_SECURE_TLS_SIGNATURE_ALGORITHM_RSA;
    buffer[2] = (UCHAR)(signature_length >> 8);
    buffer[3] = (UCHAR)(signature_length);

    return(4 + signature_length);
}


#ifdef CTEST
void test_application_define(void *first_unused_memory);
void test_application_define(void *first_unused_memory)
#else
VOID    nx_secure_tls_certificate_verify_concurrency_test_application_define(void *first_unused_memory)
#endif
{

    error_counter = 0;

    tx_thread_create(&thread_0, "thread 0", ntest_0_entry, 0,
                     thread_0_stack, sizeof(thread_0_stack),
                     16, 16, TX_NO_TIME_SLICE, TX_AUTO_START);

    /* Higher priority than thread_0 and started by hand, so resuming it preempts the operation
       running in thread_0. */
    tx_thread_create(&thread_1, "thread 1", ntest_1_entry, 0,
                     thread_1_stack, sizeof(thread_1_stack),
                     8, 8, TX_NO_TIME_SLICE, TX_DONT_START);
}


static VOID  ntest_1_entry(ULONG thread_input)
{

    NX_PARAMETER_NOT_USED(thread_input);

    /* Sign on session B while session A sits suspended part way through its own signing. */
    packet_reset(&packet_b, packet_buffer_b);
    thread_1_status = _nx_secure_tls_send_certificate_verify(&tls_session_b, &packet_b);

    /* Hand control back to thread_0 until it needs the second phase. */
    tx_thread_suspend(&thread_1);

    /* Verify on session D while session C sits suspended part way through its own verification. */
    thread_1_status = _nx_secure_tls_process_certificate_verify(&tls_session_d, verify_message_d,
                                                               verify_message_length);
}


static VOID  ntest_0_entry(ULONG thread_input)
{
UINT  status;
UINT  modulus_length;
UCHAR transcript_a[] = "session A handshake transcript";
UCHAR transcript_b[] = "session B handshake transcript";

    NX_PARAMETER_NOT_USED(thread_input);

    printf("NetX Secure Test:   TLS Certificate Verify Concurrency Test...............");

    /* Take a copy of the crypto table so the handshake hash method can be wrapped without touching
       the shared const table. */
    memcpy(&test_ciphers, &nx_crypto_tls_ciphers, sizeof(NX_SECURE_TLS_CRYPTO));

    real_hash_method = nx_crypto_tls_ciphers.nx_secure_tls_handshake_hash_sha256_method;
    memcpy(&test_hash_method, real_hash_method, sizeof(NX_CRYPTO_METHOD));
    test_hash_method.nx_crypto_operation = test_hash_operation;
    test_ciphers.nx_secure_tls_handshake_hash_sha256_method = &test_hash_method;

    memset(&test_public_cipher_method, 0, sizeof(NX_CRYPTO_METHOD));
    test_public_cipher_method.nx_crypto_operation = test_public_cipher_operation;
    memset(&test_x509_hash_method, 0, sizeof(NX_CRYPTO_METHOD));

    session_setup(&tls_session_a, metadata_a, sizeof(metadata_a), &certificate_a,
                  NX_SECURE_X509_CERT_LOCATION_LOCAL, transcript_a, sizeof(transcript_a) - 1);
    session_setup(&tls_session_b, metadata_b, sizeof(metadata_b), &certificate_b,
                  NX_SECURE_X509_CERT_LOCATION_LOCAL, transcript_b, sizeof(transcript_b) - 1);

    /* The whole point of the fix is that the buffers are no longer shared, so make sure the two
       sessions really were handed different scratch areas. */
    EXPECT_TRUE(tls_session_a.nx_secure_tls_certificate_verify_scratch !=
                tls_session_b.nx_secure_tls_certificate_verify_scratch);
    EXPECT_TRUE(tls_session_a.nx_secure_tls_certificate_verify_scratch_size >=
                (ULONG)NX_SECURE_TLS_CERTIFICATE_VERIFY_SCRATCH_SIZE);

    /* ---- Phase 1: signing ---- */

    crypto_phase = PHASE_SIGN;
    preemption_armed = NX_FALSE;

    /* Reference pass: each session signs on its own, with nothing else running. Both runs happen in
       thread_0, so both land in slot A and are copied out one at a time. */
    packet_reset(&packet_a, packet_buffer_a);
    status = _nx_secure_tls_send_certificate_verify(&tls_session_a, &packet_a);
    EXPECT_EQ(NX_SECURE_TLS_SUCCESS, status);
    memcpy(reference_block[SESSION_A], captured_block[SESSION_A], CAPTURE_SIZE);
    reference_length[SESSION_A] = captured_length[SESSION_A];
    EXPECT_TRUE(reference_length[SESSION_A] > 0);

    packet_reset(&packet_b, packet_buffer_b);
    status = _nx_secure_tls_send_certificate_verify(&tls_session_b, &packet_b);
    EXPECT_EQ(NX_SECURE_TLS_SUCCESS, status);
    memcpy(reference_block[SESSION_B], captured_block[SESSION_A], CAPTURE_SIZE);
    reference_length[SESSION_B] = captured_length[SESSION_A];
    EXPECT_TRUE(reference_length[SESSION_B] > 0);

    /* Different transcripts must give different signed blocks, otherwise the comparison below would
       pass even with the buffers shared. */
    EXPECT_TRUE(memcmp(reference_block[SESSION_A], reference_block[SESSION_B], CAPTURE_SIZE) != 0);

    /* Interleaved pass: session A is preempted inside the signing operation, session B signs to
       completion, then session A resumes and finishes. */
    memset(captured_block, 0, sizeof(captured_block));
    memset(captured_length, 0, sizeof(captured_length));
    thread_1_status = NX_NOT_SUCCESSFUL;
    preemption_armed = NX_TRUE;
    preemption_fired = NX_FALSE;

    packet_reset(&packet_a, packet_buffer_a);
    status = _nx_secure_tls_send_certificate_verify(&tls_session_a, &packet_a);
    EXPECT_EQ(NX_SECURE_TLS_SUCCESS, status);
    EXPECT_EQ(NX_SECURE_TLS_SUCCESS, thread_1_status);

    /* Without the preemption the test proves nothing, so treat a missed hook as a failure. */
    EXPECT_EQ(NX_TRUE, preemption_fired);

    /* Both sessions must have signed their own transcript. Before the fix, session A resumed with
       session B's handshake hash (or with zeroes under NX_SECURE_KEY_CLEAR) and this comparison
       failed. */
    EXPECT_EQ(reference_length[SESSION_A], captured_length[SESSION_A]);
    EXPECT_EQ(reference_length[SESSION_B], captured_length[SESSION_B]);
    EXPECT_TRUE(memcmp(reference_block[SESSION_A], captured_block[SESSION_A], CAPTURE_SIZE) == 0);
    EXPECT_TRUE(memcmp(reference_block[SESSION_B], captured_block[SESSION_B], CAPTURE_SIZE) == 0);

    /* ---- Phase 2: verifying ---- */

    session_setup(&tls_session_c, metadata_c, sizeof(metadata_c), &certificate_c,
                  NX_SECURE_X509_CERT_LOCATION_REMOTE, transcript_a, sizeof(transcript_a) - 1);
    session_setup(&tls_session_d, metadata_d, sizeof(metadata_d), &certificate_d,
                  NX_SECURE_X509_CERT_LOCATION_REMOTE, transcript_b, sizeof(transcript_b) - 1);

    EXPECT_TRUE(tls_session_c.nx_secure_tls_certificate_verify_scratch !=
                tls_session_d.nx_secure_tls_certificate_verify_scratch);

    modulus_length = certificate_c.nx_secure_x509_public_key.rsa_public_key.nx_secure_rsa_public_modulus_length;
    EXPECT_EQ(reference_length[SESSION_A], (ULONG)modulus_length);

    verify_message_length = verify_message_build(verify_message_c, modulus_length);
    verify_message_build(verify_message_d, modulus_length);

    crypto_phase = PHASE_VERIFY;

    /* Reference pass: each session verifies on its own. Both runs happen in thread_0, so both are
       served slot A's recorded block; run session C, whose transcript matches that block. */
    preemption_armed = NX_FALSE;
    status = _nx_secure_tls_process_certificate_verify(&tls_session_c, verify_message_c,
                                                      verify_message_length);
    EXPECT_EQ(NX_SUCCESS, status);

    /* Interleaved pass: session C is preempted inside the verification, session D verifies to
       completion, then session C resumes and finishes. Before the fix, session C compared session
       D's handshake hash (or zeroes under NX_SECURE_KEY_CLEAR) against its own decrypted signature
       and rejected a valid signature. */
    thread_1_status = NX_NOT_SUCCESSFUL;
    preemption_armed = NX_TRUE;
    preemption_fired = NX_FALSE;

    status = _nx_secure_tls_process_certificate_verify(&tls_session_c, verify_message_c,
                                                      verify_message_length);
    EXPECT_EQ(NX_SUCCESS, status);
    EXPECT_EQ(NX_SUCCESS, thread_1_status);
    EXPECT_EQ(NX_TRUE, preemption_fired);

    /* ---- Phase 3: a modulus larger than the signature buffer is rejected ---- */

    /* The buffers are now sized by a macro the application can lower, so both routines must refuse a
       certificate whose key does not fit instead of running off the end of the buffer. */
    preemption_armed = NX_FALSE;

    certificate_a.nx_secure_x509_public_key.rsa_public_key.nx_secure_rsa_public_modulus_length =
        (USHORT)(NX_SECURE_TLS_CERTIFICATE_VERIFY_SIGNATURE_SIZE + 1);
    crypto_phase = PHASE_SIGN;
    packet_reset(&packet_a, packet_buffer_a);
    status = _nx_secure_tls_send_certificate_verify(&tls_session_a, &packet_a);
    EXPECT_EQ(NX_SECURE_TLS_INVALID_CERTIFICATE, status);

    certificate_c.nx_secure_x509_public_key.rsa_public_key.nx_secure_rsa_public_modulus_length =
        (USHORT)(NX_SECURE_TLS_CERTIFICATE_VERIFY_SIGNATURE_SIZE + 1);
    crypto_phase = PHASE_VERIFY;
    verify_message_length = verify_message_build(verify_message_c,
                                                 NX_SECURE_TLS_CERTIFICATE_VERIFY_SIGNATURE_SIZE + 1);
    status = _nx_secure_tls_process_certificate_verify(&tls_session_c, verify_message_c,
                                                      verify_message_length);
    EXPECT_EQ(NX_SECURE_TLS_INVALID_CERTIFICATE, status);

    if (error_counter)
    {
        printf("ERROR!\n");
        test_control_return(1);
    }
    else
    {
        printf("SUCCESS!\n");
        test_control_return(0);
    }
}

#else

#ifdef CTEST
void test_application_define(void *first_unused_memory);
void test_application_define(void *first_unused_memory)
#else
VOID    nx_secure_tls_certificate_verify_concurrency_test_application_define(void *first_unused_memory)
#endif
{

    printf("NetX Secure Test:   TLS Certificate Verify Concurrency Test...............N/A\n");
    test_control_return(3);
}
#endif
