/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 * 
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 * 
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 * 
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* This tests the packet buffer bounds of the TLS 1.3 HelloRetryRequest cookie
   extension in nx_secure_tls_send_clienthello_extensions.c.  */

#include "nx_api.h"
#include "nx_secure_tls_api.h"
#include "nx_secure_tls.h"
#include "tls_test_utility.h"

extern VOID    test_control_return(UINT status);

#if !defined(NX_SECURE_TLS_CLIENT_DISABLED) && defined(NX_SECURE_ENABLE_ECC_CIPHERSUITE) && (NX_SECURE_TLS_TLS_1_3_ENABLED)

/* Six bytes of extension type, extension length and cookie length precede the cookie. */
#define COOKIE_HEADER_SIZE          6
#define COOKIE_SIZE                 64
#define BUFFER_SIZE                 512
#define GUARD_BYTE                  0xA5

static NX_SECURE_TLS_SESSION    tls_session;
static UCHAR                    packet_buffer[BUFFER_SIZE];
static UCHAR                    cookie_data[COOKIE_SIZE];

/* Put the session into the HelloRetry state a second ClientHello is built from. */
static VOID cookie_session_setup(UINT cookie_length)
{
    memset(&tls_session, 0, sizeof(tls_session));
    tls_session.nx_secure_tls_socket_type = NX_SECURE_TLS_SESSION_TYPE_CLIENT;
    tls_session.nx_secure_tls_1_3 = NX_TRUE;
    tls_session.nx_secure_tls_protocol_version = NX_SECURE_TLS_VERSION_TLS_1_3;
    tls_session.nx_secure_tls_client_state = NX_SECURE_TLS_CLIENT_STATE_HELLO_RETRY;
    tls_session.nx_secure_tls_cookie = cookie_data;
    tls_session.nx_secure_tls_cookie_length = cookie_length;

    memset(packet_buffer, GUARD_BYTE, sizeof(packet_buffer));
    memset(cookie_data, 0x5A, sizeof(cookie_data));
}

/* Confirm the builder left every byte from offset onwards alone. */
static UINT buffer_untouched_from(ULONG offset)
{
ULONG i;

    for (i = offset; i < BUFFER_SIZE; i++)
    {
        if (packet_buffer[i] != GUARD_BYTE)
        {
            return(NX_FALSE);
        }
    }

    return(NX_TRUE);
}

#ifdef CTEST
void test_application_define(void *first_unused_memory);
void test_application_define(void *first_unused_memory)
#else
void nx_secure_tls_1_3_hello_retry_cookie_overflow_test_application_define(void *first_unused_memory)
#endif
{
UINT   status;
ULONG  packet_offset;
ULONG  extensions_length;
ULONG  prefix_length;
ULONG  required_size;

    printf("NetX Secure Test:   TLS 1.3 HelloRetry Cookie Overflow Test............");

    /* Measure what the extensions ahead of the cookie consume, so the boundary
       cases below do not depend on the enabled version list. */
    cookie_session_setup(0);
    packet_offset = 0;
    extensions_length = 0;
    status = _nx_secure_tls_send_clienthello_extensions(&tls_session, packet_buffer,
                                                        &packet_offset, &extensions_length,
                                                        BUFFER_SIZE);
    EXPECT_EQ(NX_SUCCESS, status);
    prefix_length = packet_offset;
    EXPECT_TRUE((prefix_length + COOKIE_HEADER_SIZE + COOKIE_SIZE) < BUFFER_SIZE);

    required_size = prefix_length + COOKIE_HEADER_SIZE + COOKIE_SIZE;

    /* The largest cookie a peer can announce cannot reach the buffer. */
    cookie_session_setup(0xFFFF);
    packet_offset = 0;
    extensions_length = 0;
    status = _nx_secure_tls_send_clienthello_extensions(&tls_session, packet_buffer,
                                                        &packet_offset, &extensions_length,
                                                        BUFFER_SIZE);
    EXPECT_EQ(NX_SECURE_TLS_PACKET_BUFFER_TOO_SMALL, status);
    EXPECT_EQ(0, tls_session.nx_secure_tls_cookie_length);
    EXPECT_TRUE(tls_session.nx_secure_tls_cookie == NX_NULL);
    EXPECT_TRUE(buffer_untouched_from(prefix_length) == NX_TRUE);

    /* An exact fit is accepted and consumes the whole extension. */
    cookie_session_setup(COOKIE_SIZE);
    packet_offset = 0;
    extensions_length = 0;
    status = _nx_secure_tls_send_clienthello_extensions(&tls_session, packet_buffer,
                                                        &packet_offset, &extensions_length,
                                                        required_size);
    EXPECT_EQ(NX_SUCCESS, status);
    EXPECT_EQ(required_size, packet_offset);
    EXPECT_EQ(0, tls_session.nx_secure_tls_cookie_length);
    EXPECT_TRUE(tls_session.nx_secure_tls_cookie == NX_NULL);
    EXPECT_TRUE(buffer_untouched_from(required_size) == NX_TRUE);

    /* One byte short is rejected before anything is written. */
    cookie_session_setup(COOKIE_SIZE);
    packet_offset = 0;
    extensions_length = 0;
    status = _nx_secure_tls_send_clienthello_extensions(&tls_session, packet_buffer,
                                                        &packet_offset, &extensions_length,
                                                        required_size - 1);
    EXPECT_EQ(NX_SECURE_TLS_PACKET_BUFFER_TOO_SMALL, status);
    EXPECT_EQ(0, tls_session.nx_secure_tls_cookie_length);
    EXPECT_TRUE(tls_session.nx_secure_tls_cookie == NX_NULL);
    EXPECT_TRUE(buffer_untouched_from(prefix_length) == NX_TRUE);

    /* Room for part of the header only is rejected before anything is written. */
    cookie_session_setup(COOKIE_SIZE);
    packet_offset = 0;
    extensions_length = 0;
    status = _nx_secure_tls_send_clienthello_extensions(&tls_session, packet_buffer,
                                                        &packet_offset, &extensions_length,
                                                        prefix_length + (COOKIE_HEADER_SIZE - 3));
    EXPECT_EQ(NX_SECURE_TLS_PACKET_BUFFER_TOO_SMALL, status);
    EXPECT_EQ(0, tls_session.nx_secure_tls_cookie_length);
    EXPECT_TRUE(tls_session.nx_secure_tls_cookie == NX_NULL);
    EXPECT_TRUE(buffer_untouched_from(prefix_length) == NX_TRUE);

    /* A KeyShare extension that does not fit ends the build. */
    cookie_session_setup(0);
    packet_offset = 0;
    extensions_length = 0;
    status = _nx_secure_tls_send_clienthello_extensions(&tls_session, packet_buffer,
                                                        &packet_offset, &extensions_length,
                                                        prefix_length - 1);
    EXPECT_EQ(NX_SECURE_TLS_PACKET_BUFFER_TOO_SMALL, status);

    printf("SUCCESS!\n");

    test_control_return(0);
}

#else

#ifdef CTEST
void test_application_define(void *first_unused_memory);
void test_application_define(void *first_unused_memory)
#else
void nx_secure_tls_1_3_hello_retry_cookie_overflow_test_application_define(void *first_unused_memory)
#endif
{

    printf("NetX Secure Test:   TLS 1.3 HelloRetry Cookie Overflow Test............N/A\n");
    test_control_return(3);
}

#endif
