/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 * 
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 * 
 * AI Disclosure: This file was largely AI-generated by Codex (gpt-5.6-sol).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 * 
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* Regression test for the ClientHello signature_algorithms extension.
   A client that offers both TLS 1.3 and TLS 1.2 must advertise RSA-PSS for
   TLS 1.3 while retaining RSA PKCS#1 v1.5 for TLS 1.2 fallback. */

#include "nx_api.h"
#include "nx_secure_tls_api.h"
#include "nx_secure_tls.h"
#include "tls_test_utility.h"

extern VOID test_control_return(UINT status);

#if !defined(NX_SECURE_TLS_CLIENT_DISABLED) && !defined(NX_SECURE_DISABLE_X509) && \
    (NX_SECURE_TLS_TLS_1_3_ENABLED)

#define TEST_PACKET_OFFSET                 3u
#define TEST_PACKET_SIZE                   32u
#define TLS_1_3_EXTENSION_SIZE             20u
#define TLS_1_2_EXTENSION_SIZE             14u
#define OVERSIZED_TABLE_ENTRY_COUNT        16383u

static NX_CRYPTO_METHOD rsa_method =
{
    NX_CRYPTO_KEY_EXCHANGE_RSA, 0, 0, 0, 0, 0, NX_NULL, NX_NULL, NX_NULL
};

static NX_CRYPTO_METHOD ecdsa_method =
{
    NX_CRYPTO_DIGITAL_SIGNATURE_ECDSA, 0, 0, 0, 0, 0, NX_NULL, NX_NULL, NX_NULL
};

static NX_CRYPTO_METHOD unsupported_method =
{
    NX_CRYPTO_DIGITAL_SIGNATURE_ANONYMOUS, 0, 0, 0, 0, 0, NX_NULL, NX_NULL, NX_NULL
};

static NX_CRYPTO_METHOD sha256_method =
{
    NX_CRYPTO_HASH_SHA256, 0, 0, 0, 0, 0, NX_NULL, NX_NULL, NX_NULL
};

static NX_CRYPTO_METHOD sha384_method =
{
    NX_CRYPTO_HASH_SHA384, 0, 0, 0, 0, 0, NX_NULL, NX_NULL, NX_NULL
};

static NX_CRYPTO_METHOD sha512_method =
{
    NX_CRYPTO_HASH_SHA512, 0, 0, 0, 0, 0, NX_NULL, NX_NULL, NX_NULL
};

static NX_SECURE_X509_CRYPTO signature_methods[] =
{
    {0, &rsa_method,         &sha256_method},
    {0, &rsa_method,         &sha384_method},
    {0, &rsa_method,         &sha512_method},
    {0, &ecdsa_method,       &sha256_method},
    {0, &unsupported_method, &sha256_method}
};

static NX_SECURE_X509_CRYPTO oversized_signature_methods[OVERSIZED_TABLE_ENTRY_COUNT];

static const USHORT supported_groups[] =
{
    (USHORT)NX_CRYPTO_EC_SECP256R1
};

static const UCHAR expected_tls_1_3_extension[TLS_1_3_EXTENSION_SIZE] =
{
    0x00, 0x0D, 0x00, 0x10, 0x00, 0x0E,
    0x08, 0x04, 0x04, 0x01,
    0x08, 0x05, 0x05, 0x01,
    0x08, 0x06, 0x06, 0x01,
    0x04, 0x03
};

static const UCHAR expected_tls_1_2_extension[TLS_1_2_EXTENSION_SIZE] =
{
    0x00, 0x0D, 0x00, 0x0A, 0x00, 0x08,
    0x04, 0x01, 0x05, 0x01, 0x06, 0x01, 0x04, 0x03
};

#endif

/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                                              */
/*                                                                        */
/*    test_application_define                                             */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    This function validates the TLS ClientHello signature algorithms    */
/*    extension for dual TLS 1.3 and TLS 1.2 operation.                   */
/*                                                                        */
/**************************************************************************/
#ifdef CTEST
void test_application_define(void *first_unused_memory)
#else
void nx_secure_tls_clienthello_signature_algorithms_test_application_define(void *first_unused_memory)
#endif
{
#if !defined(NX_SECURE_TLS_CLIENT_DISABLED) && !defined(NX_SECURE_DISABLE_X509) && \
    (NX_SECURE_TLS_TLS_1_3_ENABLED)
NX_SECURE_TLS_SESSION tls_session;
NX_SECURE_TLS_CRYPTO crypto_table;
UCHAR packet_buffer[TEST_PACKET_SIZE];
ULONG packet_offset;
USHORT extension_length;
UINT status;
UINT i;

    NX_PARAMETER_NOT_USED(first_unused_memory);

    printf("NetX Secure Test:   TLS ClientHello Signature Algorithms Test...");

    memset(&tls_session, 0, sizeof(tls_session));
    memset(&crypto_table, 0, sizeof(crypto_table));
    crypto_table.nx_secure_tls_x509_cipher_table = signature_methods;
    crypto_table.nx_secure_tls_x509_cipher_table_size =
        (USHORT)(sizeof(signature_methods) / sizeof(signature_methods[0]));
    tls_session.nx_secure_tls_crypto_table = &crypto_table;
    tls_session.nx_secure_tls_1_3 = NX_TRUE;
    tls_session.nx_secure_tls_ecc.nx_secure_tls_ecc_supported_groups = supported_groups;
    tls_session.nx_secure_tls_ecc.nx_secure_tls_ecc_supported_groups_count =
        (USHORT)(sizeof(supported_groups) / sizeof(supported_groups[0]));

    /* The old two-bytes-per-table-entry check accepted this buffer even
       though the RSA-PSS entries now require paired TLS 1.2 algorithms. */
    memset(packet_buffer, 0xA5, sizeof(packet_buffer));
    packet_offset = TEST_PACKET_OFFSET;
    extension_length = 0xA5A5u;
    status = _nx_secure_tls_send_clienthello_sig_extension(&tls_session, packet_buffer,
                                                           &packet_offset, &extension_length,
                                                           TEST_PACKET_OFFSET + TLS_1_3_EXTENSION_SIZE - 1u);
    EXPECT_EQ(NX_SECURE_TLS_PACKET_BUFFER_TOO_SMALL, status);
    EXPECT_EQ(TEST_PACKET_OFFSET, packet_offset);
    EXPECT_EQ(0xA5A5u, extension_length);
    for (i = 0; i < TEST_PACKET_SIZE; i++)
    {
        EXPECT_EQ(0xA5u, packet_buffer[i]);
    }

    /* An offset beyond the available buffer must also fail without writing. */
    packet_offset = TEST_PACKET_OFFSET;
    status = _nx_secure_tls_send_clienthello_sig_extension(&tls_session, packet_buffer,
                                                           &packet_offset, &extension_length,
                                                           TEST_PACKET_OFFSET - 1u);
    EXPECT_EQ(NX_SECURE_TLS_PACKET_BUFFER_TOO_SMALL, status);

    /* The extension must fit when exactly enough space is available. */
    packet_offset = TEST_PACKET_OFFSET;
    extension_length = 0;
    status = _nx_secure_tls_send_clienthello_sig_extension(&tls_session, packet_buffer,
                                                           &packet_offset, &extension_length,
                                                           TEST_PACKET_OFFSET + TLS_1_3_EXTENSION_SIZE);
    EXPECT_EQ(NX_SUCCESS, status);
    EXPECT_EQ(TEST_PACKET_OFFSET + TLS_1_3_EXTENSION_SIZE, packet_offset);
    EXPECT_EQ(TLS_1_3_EXTENSION_SIZE, extension_length);
    EXPECT_TRUE(memcmp(&packet_buffer[TEST_PACKET_OFFSET], expected_tls_1_3_extension,
                       TLS_1_3_EXTENSION_SIZE) == 0);
    EXPECT_EQ(0xA5u, packet_buffer[TEST_PACKET_OFFSET - 1u]);
    EXPECT_EQ(0xA5u, packet_buffer[TEST_PACKET_OFFSET + TLS_1_3_EXTENSION_SIZE]);

    /* Disabling TLS 1.3 retains the original TLS 1.2-only list. */
    memset(packet_buffer, 0xA5, sizeof(packet_buffer));
    tls_session.nx_secure_tls_1_3 = NX_FALSE;
    packet_offset = TEST_PACKET_OFFSET;
    extension_length = 0;
    status = _nx_secure_tls_send_clienthello_sig_extension(&tls_session, packet_buffer,
                                                           &packet_offset, &extension_length,
                                                           TEST_PACKET_OFFSET + TLS_1_2_EXTENSION_SIZE);
    EXPECT_EQ(NX_SUCCESS, status);
    EXPECT_EQ(TEST_PACKET_OFFSET + TLS_1_2_EXTENSION_SIZE, packet_offset);
    EXPECT_EQ(TLS_1_2_EXTENSION_SIZE, extension_length);
    EXPECT_TRUE(memcmp(&packet_buffer[TEST_PACKET_OFFSET], expected_tls_1_2_extension,
                       TLS_1_2_EXTENSION_SIZE) == 0);

    /* A configured algorithm list must fit in the 16-bit extension length. */
    for (i = 0; i < OVERSIZED_TABLE_ENTRY_COUNT; i++)
    {
        oversized_signature_methods[i].nx_secure_x509_crypto_identifier = 0;
        oversized_signature_methods[i].nx_secure_x509_public_cipher_method = &rsa_method;
        oversized_signature_methods[i].nx_secure_x509_hash_method = &sha256_method;
    }
    crypto_table.nx_secure_tls_x509_cipher_table = oversized_signature_methods;
    crypto_table.nx_secure_tls_x509_cipher_table_size = OVERSIZED_TABLE_ENTRY_COUNT;
    tls_session.nx_secure_tls_1_3 = NX_TRUE;
    packet_offset = 0;
    status = _nx_secure_tls_send_clienthello_sig_extension(&tls_session, packet_buffer,
                                                           &packet_offset, &extension_length,
                                                           0xFFFFFFFFu);
    EXPECT_EQ(NX_SECURE_TLS_PACKET_BUFFER_TOO_SMALL, status);

    printf("SUCCESS!\n");
#else
    NX_PARAMETER_NOT_USED(first_unused_memory);
#endif

    test_control_return(0);
}
